### ISSUE TITLE
Possible Typo-lesson 3 Dataframes

### ISSUE THREAD

**Issue by tylerjrichards** [datacarpentry/R-ecology-lesson#103]
`colors <- c("red", "green", "blue", "yellow")
counts <- c(50, 60, 65, 82)
new_dataframe <- as.data.frame(cbind(colors, weights))
class(new_dataframe)`

shouldn't it be counts instead of weights in the third line?

**Comment by fmichonneau** [comment]
Thanks for reporting this issue. It has now been fixed.
