### ISSUE TITLE
Broken links to R ecology lesson materials

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/R-ecology-lesson#105]
The links on the DC lessons page to the ecology introduction to R and dplyr lessons gives 404 errors. This appears to be because those modules only exist as .Rmd files (no corresponding html files in the lesson repo). Cross-posting to website and lesson repos to try to get fast fix. 

Thanks!

**Comment by fmichonneau** [comment]
Hi @ErinBecker 

It should be fixed now. Could you please double check on your end and close if it's the case? Thanks!

**Comment by ErinBecker** [comment]
Thanks @fmichonneau. All fixed!
