### ISSUE TITLE
cbind to create data frame in challenge in 03-data-frame

### ISSUE THREAD

**Issue by jhollist** [datacarpentry/R-ecology-lesson#106]
Couple of  issues with this example.  

As written example is:

```
colors <- c("red", "green", "blue", "yellow")
counts <- c(50, 60, 65, 82)
new_dataframe <- as.data.frame(cbind(colors, weights))
class(new_dataframe)
```

First, typo is line 3 of this.  should be counts and not weights.
Second, cbind returns a matrix and thus does more conversion here than I think we want to introduce.

I'd suggest re-doing this as 

```
colors <- c("red", "green", "blue", "yellow")
counts <- c(50, 60, 65, 82)
new_dataframe <- data.frame(colors, weights)
class(new_dataframe)
```

Maybe a mention of cbind and rbind here as well, but pointing out the matrix as return...

Thoughts?

I can do a PR, but won't have time for a bit.

Oh and Kudos to the July 26-27 2016 BU workshop.  They found these!!!

**Comment by fmichonneau** [comment]
hi @jhollist, I think both issues were resolved in one of the PRs I merged last night. I hope the workshop went well!

**Comment by jhollist** [comment]
Great!  I'll go ahead and close and if need be we can re-open.

And workshop is going well.  One more day and some SQL prep tonight.  Thanks for asking!
