### ISSUE TITLE
tidyverse instead of dplyr, tidyr and ggplot2?

### ISSUE THREAD

**Issue by RaoulWolf** [datacarpentry/R-ecology-lesson#116]
This might be more philosophical, but now that Wickham et al. have released their "tidyverse" package (see [RStudio Blog](https://blog.rstudio.org/2016/09/15/tidyverse-1-0-0/) and [CRAN](https://cran.r-project.org/web/packages/tidyverse/index.html)), this would present a more convenient way of obtaining the dplyr, tidyr and ggplot2 packages needed for the lesson.
Since the lesson material is already tightly knit to the tidyverse ideas, this would simplify teaching the lesson.

Again, this may be more about personal preferences; but in my opinion it could make it easier for students (or whoever is being taught), instead of installing the individual packages manually.

Looking forward to your thoughts!

**Comment by fmichonneau** [comment]
Hi @raoulwolf 
 
Thanks for your message. I have been thinking about this myself. I like the idea.  I want to look more into it as i worry that in the process we'll bring more packages and potentially more installation issues with it.  Maybe we can test it for a few workshops and see how it goes.

**Comment by fmichonneau** [comment]
I asked participants from a recent workshop to install `tidyverse` and it seemed to have gone smoothly. It would be great to repeat the experiment for a few other workshops before changing the installation instructions, but I think it is a worthwhile change.

We also need to ask to install `RSQLite` as it's not part of `tidyverse` (or `dplyr`) and is needed if learners go through the last episode of the lesson.

If someone teaches a workshop soon, and asks participants to use `tidyverse` please report back.

**Comment by fmichonneau** [comment]
tidyverse is now the listed package to install in the setup instructions
