### ISSUE TITLE
No mention of downloading "portal_mammals.sqlite" file in lesson 06 R and SQL

### ISSUE THREAD

**Issue by cwmohr** [datacarpentry/R-ecology-lesson#121]
It is my impression that one should be able to teach more or less directly the R-ecology-lessons. This is not a problem for lesson 00 - 05. However, it is a bit more difficult for lesson 06 "R and SQL", because the requirement of specific files:

In lesson 06 [(SQL databases and R)](http://www.datacarpentry.org/R-ecology-lesson/06-r-and-sql.html) , under the section _"Connecting R to sqlite database"_ there is the following R-script:

``` r
## Set dbname and driver out of convenience
myDB <- "data/portal_mammals.sqlite"
conn <- dbConnect(drv = SQLite(), dbname= myDB)
```

There is however no earlier mention for downloading the file `"portal_mammals.sqlite"`.

I therefore suggest that lesson 06 be updated, by taking into use the `download.file()` function:

``` r
## download mammals database to data folder.
download.file("https://ndownloader.figshare.com/files/2292171", "data/portal_mammals.sqlite")
```

PS: All the file can be downloaded from http://dx.doi.org/10.6084/m9.figshare.1314459.

**Comment by fmichonneau** [comment]
discussion for this issue continues in #162
