### ISSUE TITLE
referring to a warning as an error, should we change?

### ISSUE THREAD

**Issue by mfoos** [datacarpentry/R-ecology-lesson#123]
At the very bottom of 01-intro-to-R.html, there's a challenge where learners are asked to take the mean of a string vector that "appears" to contain numbers. As desired (by us) the command returns a warning, but the text refers to it as an "error". There is mention earlier in the lesson that learners should "Try to use the correct words to describe your problem" (and of course there are real differences) so I think it would be consistent to change the text to "warning". If people agree, I'll submit a PR.

**Comment by fmichonneau** [comment]
Yes please! Thanks for catching that
