### ISSUE TITLE
in the lesson `starting with data` you never create the folder to download the file to

### ISSUE THREAD

**Issue by RMHogervorst** [datacarpentry/R-ecology-lesson#130]
http://www.datacarpentry.org/R-ecology-lesson/02-starting-with-data.html

```
download.file("https://ndownloader.figshare.com/files/2292169",
              "data/portal_data_joined.csv")
```

Will give at least me, and others as well an error, because you don't have the folder `data/` yet.

suggestion to change to:

```
dir.create("data")
download.file("https://ndownloader.figshare.com/files/2292169",
              "data/portal_data_joined.csv")
```

**Comment by ksamuk** [comment]
This is secretly (and silently) handled by `source("setup.R")` in the .Rmd. But agree if you're live-coding this or copy-pasting from the html, that would throw an error.

If we want to change this this, I made a PR here #131

**Comment by fmichonneau** [comment]
Hi @RMHogervorst 

The folder creation is done manually in the first lesson: "[before we start](http://www.datacarpentry.org/R-ecology-lesson/00-before-we-start.html)". As mentioned by @ksamuk the automatic folder creation of the data folder is handled by the script setup.R that is run by the lesson maintainers to generate the html version of the lesson.

Feel free to re-open if needed.
