### ISSUE TITLE
Top navigation bar obscuring part of page

### ISSUE THREAD

**Issue by atyre2** [datacarpentry/R-ecology-lesson#139]
When I view http://www.datacarpentry.org/R-ecology-lesson//00-before-we-start.html using chrome the Navigation menu across the top of the page is obscuring some part of the main page as well as the top of the outline on the left side of the page. After poking around in the source I don't think there is anything missing, but doesn't look good.

**Comment by fmichonneau** [comment]
Could you please send a screenshot? It looks OK for me. Do you use extensions that could affect the styling of the page?


![screenshot from 2016-12-01 16-32-19](https://cloud.githubusercontent.com/assets/5502922/20813478/c6cb97de-b7e3-11e6-89a9-3561f8deb418.png)

**Comment by atyre2** [comment]
I’m not using any add-ons that I’m aware of … although that doesn’t mean they aren’t there!

--
Drew Tyre

School of Natural Resources
University of Nebraska-Lincoln
416 Hardin Hall, East Campus
3310 Holdrege Street
Lincoln, NE 68583-0974

phone: +1 402 472 4054
fax: +1 402 472 2946
email: atyre2@unl.edu
http://snr.unl.edu/tyre
http://atyre2.github.io
ORCID: orcid.org/0000-0001-9736-641X

**Comment by atyre2** [comment]
!

OK, yes, now it looks great … went into extensions and turned off everything that was there.

Thank you!

--
Drew Tyre

School of Natural Resources
University of Nebraska-Lincoln
416 Hardin Hall, East Campus
3310 Holdrege Street
Lincoln, NE 68583-0974

phone: +1 402 472 4054
fax: +1 402 472 2946
email: atyre2@unl.edu
http://snr.unl.edu/tyre
http://atyre2.github.io
ORCID: orcid.org/0000-0001-9736-641X

**Comment by fmichonneau** [comment]
Great! I'm glad it's working.
