### ISSUE TITLE
index page title not correct

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/R-ecology-lesson#151]
The front page for the lesson (http://www.datacarpentry.org/R-ecology-lesson/) has "Data Carpentry {{ page.topic }} for {{ page.domain }}" on it, and also "Data Carpentry R for data analysis for Ecology"

Since there's an index.html and index.md in the repo, it's not quite clear where the rendering is coming from. It would be good to get rid of the "Data Carpentry {{ page.topic }} for {{ page.domain }}" text though.

**Comment by ctb** [comment]
Working on it.

**Comment by ctb** [comment]
This seems to be related to the move from Jekyll 2 to Jekyll 3; see [this link](https://jekyllrb.com/docs/upgrading/2-to-3/#layout-metadata) for words that kind of make sense.
