### ISSUE TITLE
'topic' layout missing

### ISSUE THREAD

**Issue by ktoddbrown** [datacarpentry/R-ecology-lesson#156]
Layout 'topic' is missing from _layouts folder.

This was in part of an old post but I don't think it was addressed.

**Comment by ctb** [comment]
The warnings are fixed in #153 (by changing the layout to lesson)

**Comment by ktoddbrown** [comment]
Thanks.

**Comment by ctb** [comment]
(I should say I don't know if #153 is the right fix - I just wanted to shut up the warnings ;). input welcome!

**Comment by ktoddbrown** [comment]
Yes, changing the layout to something actually in the _layouts folder address this issue :D Thanks!
