### ISSUE TITLE
Update contributor documentation

### ISSUE THREAD

**Issue by ctb** [datacarpentry/R-ecology-lesson#159]
@ktoddbrown commented in https://github.com/datacarpentry/R-ecology-lesson/issues/154#issuecomment-269379137 that documenting a first-time contributor workflow for git and Jekyll would be helpful. Per @tracykteal's [comment](https://github.com/datacarpentry/R-ecology-lesson/issues/154#issuecomment-269539229) there's lots to be done here and we should move that to a separate issue, so I'm stealing her thunder and creating said issue :).

@ktoddbrown, I'd be happy to put together a tutorial much like [this one](https://angus.readthedocs.io/en/2015/week3/CTB_github_editing.html) but for Jekyll instead, and with screenshots [like these](https://2016-feb-aws.readthedocs.io/boot.html#select-ec2-virtual-servers-in-the-cloud) - relevant locations on Web pages circled in read, etc. etc. Is that the kind of thing you meant?

I'm sure there are such docs for SC and DC somewhere else and I'd be happy to be pointed at them, too :).

**Comment by ktoddbrown** [comment]
I find screenshots to be less then useful (UI's change very quickly and are rarely consistent across OS) but would be happy with a line by line walk through of the command lines needed. 

If the pipeline is changing maybe we should put this on hold for a bit. Otherwise I'd be happy to help dummy-proof the doc :)

**Comment by ctb** [comment]
On Sun, Jan 01, 2017 at 10:07:57AM -0800, Kathe Todd-Brown wrote:
> I find screenshots to be less then useful (UI's change very quickly and are rarely consistent across OS) but would be happy with a line by line walk through of the command lines needed. 

I was thinking of using screenshots of github, as this can all be done line
through github's web interface.

**Comment by tracykteal** [comment]
I wrote up a 'How to Contribute for the Bug BBQ' document that could be a good start for this documentation. https://github.com/datacarpentry/lesson-release/blob/master/how-to-contribute.md

**Comment by ashander** [comment]
Note that there is some material on the github workflow in the CONTRIBUTING.md template that's been applied to some DC lessons. (See it in sql [here](https://github.com/datacarpentry/sql-ecology-lesson/blame/gh-pages/CONTRIBUTING.md#L104-L129)) But this does not mention jekyll.

The material @tracykteal mentioned [does have good stuff on jekyll](https://github.com/datacarpentry/lesson-release/blame/master/how-to-contribute.md#L37)

I'll note that as a git/github fluent user without jekyll is to preview it on my fork. This requires making sure gh-pages is being served and resetting my fork's gh-pages to whatever feature I'm working on. Like:

```
> git checkout -b new-feature-branch upstream/gh-pages
<work on and commit to this feature branch, push it to my fork 'origin'>
> git checkout gh-pages
> git reset --hard new-feature-branch
> git push -f origin gh-pages
```
then if it looks good, I can make a PR
