### ISSUE TITLE
Which learning objectives should we assess?

### ISSUE THREAD

**Issue by kariljordan** [datacarpentry/R-ecology-lesson#161]
Greetings everyone,

I'd appreciate your feedback on my current project. We've successfully revised the learning objectives for all of the Ecology lessons to reflect what we are teaching, and now we are in the process of developing surveys to assess our learners (before and after the workshop) on their skills and self-efficacy for the tools they were taught.

Your feedback is extremely valuable. In this [document](https://docs.google.com/document/d/1uAP6wZ_m_gihOlSGsNurwSDq8SrTRCFYVyCerl2whHw/edit?usp=sharing) I've added the learning objectives for all of the Ecology lessons. I would appreciate if you'd open this document and add a +1 to the learning objectives you think are **most important** to **assess our learners**.

Additionally, I'm scheduling a virtual meeting to review the objectives, discuss your +1's, and come to a consensus. Please provide your availability [here](http://whenisgood.net/dclearningobjectives). 

Our goal isn't to change what we're teaching, but to better understand what we're teaching, and ensure our learning objectives reflect that, so that we can assess our learners.

Thank you for your feedback and your time.
Kari
 
P.S. Thank you so much to all the maintainers who helped revise the learning objectives!

@fmichonneau @adamobeng @tracykteal @mkuzak @karawoo @apawlik @ethanwhite @emhart @benmarwick @k8hertweck @markrobinsonuzh @hdashnow @ashander @hlapp @ashiklom @kallisons @steveped @karthik @ctb @lmsimp @annefou @aurielfournier @stephlabou @duffymeg @cbahlai

**Comment by ktoddbrown** [comment]
I have not taught this lesson yet but am interested in doing so in the future. Would you like feedback just from current/past instructors for this purpose?

**Comment by kariljordan** [comment]
@ktoddbrown Absolutely. Your perspective is extremely important.

**Comment by kariljordan** [comment]
Greetings,

Thank you for contributing to the conversation around Data Carpentry's Ecology lessons, and providing your availability for a meeting.

We will meet on Friday at 1pm EST via this BlueJeans link: https://bluejeans.com/124388012.

The purpose of this meeting is to discuss the learning objectives for the Ecology lessons, and to come to a consensus around which objectives are "most important" (for lack of better words) for assessment purposes.

We cannot assess learners on each of the learning objectives, so which are key for fulfilling Data Carpentry's mission and vision as it relates to our workshops?

The learning objectives are available via this [document](https://docs.google.com/document/d/1uAP6wZ_m_gihOlSGsNurwSDq8SrTRCFYVyCerl2whHw/edit). If you haven't already, please +1 the objectives you think are most important, and add any additional feedback if needed.

I look forward to speaking with you all soon.

My best,
Kari

**Comment by kariljordan** [comment]
We received a significant amount of feedback and were able to decide which learning objectives to assess our learners. Thanks!

**Comment by ashander** [comment]
Is #191 where the resulting changes were made?

**Comment by kariljordan** [comment]
@ashander I created PR's [#141](https://github.com/datacarpentry/R-ecology-lesson/pull/141) through [#147](https://github.com/datacarpentry/R-ecology-lesson/pull/147) to update all of the learning objectives. I believe @achazhardenberg created #191.
