### ISSUE TITLE
move information on R syntax from 'Before we start' to 'Intro to R'

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/R-ecology-lesson#164]
Rather than just discussing the R syntax in the Before we start, we can integrate it into the places where we introduce them in Intro to R. So we can move the paragraphs describing the syntax elements to those locations in Intro to R and remove the 'R syntax' section from Before we start.

**Comment by fmichonneau** [comment]
this is addressed by #175

**Comment by fmichonneau** [comment]
fixed by 3f53378
