### ISSUE TITLE
Make sure that the learning objectives match the content of the lesson

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#174]
Following the reorganization of the lesson, we need to check that the learning objectives match the content of the lessons. In other words that the lessons teach what they say they teach.

- [ ] Before we start
- [ ] Introduction to R
- [ ] Starting with data
- [ ] Aggregating and analyzing data with dplyr
- [ ] Data visualization with ggplot2
- [ ] R and databases

**Comment by sdtaylor** [comment]
I'm gonna go thru this really quick cause I've been staring at the lessons all day.

### Before we start

- Describe the purpose of the RStudio script, console, environment, and plot windows.  
  Yes, in "Knowing your way around Rstudio" 
- Organize files and directories for a set of analysis in an R Project.
  yes, in "Organizing your working directory"
- Use the built-in RStudio help interface to search for more information on R functions.
  **No, "Seeking Help" only describes help functions via the command line**
- Demonstrate how to provide sufficient information for troubleshooting with the R user community.
  Yes,, in "asking for help"

### Intro to R
- Define the following terms as they relate to R: script, function, working directory, assign, object, variable.
 Yes. Throughout, but working directory is in Lesson 1 "before we start"
- Call functions with zero or more named or unnamed arguments.
 Yes, in "Functions and their arguments"
- Solve mathematical operations in R.
 Yes, throughout
- Assign values to objects and variables in R.
 Yes
- Describe what vectors are and how they are manipulated in R.
 Yes
- Inspect the content of vectors in R and manipulate their content.
 Yes
- Extract values from vectors in R.
 Yes
- Employ logic (i.e. TRUE, FALSE) to subset data in a vector.
 Yes
- Analyze vectors with missing data.
 Yes


### Starting with data
- Describe what a data frame is.
 Yes, "What are data frames?"
- Summarize the contents of a data frame in R.
 Yes, "Inspecting data.frame objects"
- Load external data from a .csv file into R.
  Yes, in "presentation of survey data" and "using stringsAsFactors=False"
- Manipulate categorical data in R
 Yes, in "Factors"
- Read data from a file into a data.frame.
 Yes, but this is redundant with loading a csv file above. 
- Change how character strings are handled in a data.frame.
  Yes, in "Factors". 


### Analysing data with dplyr
- Recall the six data manipulation ‘verbs’ in the dplyr package and know what they do.
 Yes, throughout. `select` `filter` `mutate` `group_by` `summarise` and `tally` = 6
- Select subsets of columns and filter rows in a data.frame according to a condition(s).
 Yes, filter and select
- Employ the ‘pipe’ operator to link together a sequence of dplyr commands.
 Yes, in "Pipes"
- Employ the ‘mutate’ command to apply functions to existing columns and create new columns of data.
 Yes, "Mutate" section
- Export a data.frame to a .csv file.
 Yes, "Exporting data"

### Visualzating with ggplot2
- Produce scatter plots, bloxplots, and time series plots using ggplot.
 Yes, throught. 
- Set universal plot settings.
 Yes. Right before  the  first challenge. 
- Modify the aesthetics of an existing ggplot plot (including axis labels and color).
  Yes, throughout. 
- Build complex and customized plots from data in a dataframe.
  Yes, in "Faceting"

### Databases and R
- Access a database from R
 Yes, "Connecting to databases with dplyr"
- Run SQL queries in R using RSQLite and dplyr.
 Yes, throuhgout
- Create an SQLite database from existing .csv files.
 Yes,  in "Creating a new SQLite database"

**Comment by fmichonneau** [comment]
It would be great to have a second look at this before the release to make sure we didn't miss anything.

**Comment by fmichonneau** [comment]
I had a quick look and it seems OK to me
