### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#182]
it's a little out of date: the outline needs to match the content

**Comment by Rekyt** [comment]
Hey,
I would like to help here, but I read that the README file was generated from the index.hml file, in the Makefile. Is it still the case? Because I can't seem to find. I forked the project to edit the `README.md` file before realizing that `index.md` was actually up-to-date.

**Comment by fmichonneau** [comment]
Hi @Rekyt 

Thanks for your interest in improving the content of these lessons.

The README is not generated by the Makefile anymore. It's one of the info that needs to be updated (Where did you see it?, I don't see this in the current README file)

The things that need to be updated in the README:
- update the "table of content" for the lessons. We renamed a few of them, and some are missing (ggplot2 and databases)
- the way the lessons are built has also changed a little; we still use knitr, but indirectly as we are currently the `rmarkdown::render_site()` function
- we renamed the "skeleton" file a code handout

If you can do a pull request that cover any (or all) of these points, that would be great.

 Thanks!

**Comment by Rekyt** [comment]
Hi @fmichonneau,
Thanks for your quick and detailed answer.
I read that the README file was generated by the Makefile in the [CONTRIBUTING.md](https://github.com/datacarpentry/R-ecology-lesson/blob/gh-pages/CONTRIBUTING.md#file-locations-and-formats) file.
So it should also be updated I suppose ;)

I'm submitting a pull request right away.
Thanks again.

**Comment by fmichonneau** [comment]
I'll leave this open to remember to go through the README file one last time just before we release the lesson.

**Comment by ha0ye** [comment]
Will check this (and combine with other formatting fixes).
