### ISSUE TITLE
Should the lessons be renumbered to start at 01 instead of 00?

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#183]
it seems more intuitive... does anyone have any thoughts on this?

**Comment by ha0ye** [comment]
Agree numbering from 01 is more intuitive.
Working on it (will combine with other formatting fixes).

**Comment by fmichonneau** [comment]
@ha0ye it has been my general feeling as well. I'm going to leave it as it is, but if someone has strong feelings, and thinks we should start at 01, feel free to re-open.
