### ISSUE TITLE
Check content of lesson for typos and grammar

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#186]
Before release, we need to make sure that the lessons have correct grammar and no typos.

Ideally, we would need at least 2 people for each chapter.

- [ ] Before we start
- [ ] Introduction to R
- [ ] Starting with data
- [ ] Aggregating and analyzing data with dplyr
- [ ] Data visualization with ggplot2
- [ ] R and databases

**Comment by achazhardenberg** [comment]
In the introduction to R lesson, at the very end, it says: "Now that we have learned how to write scripts, and the basics of R's data structures, we are ready to start working with the Portal dataset we have been using in the other lessons, and learn about data frames."

However, no dataset named "Portal" is mentioned in the previous lesson (Before we start).

**Comment by kmpeck** [comment]
Working on this now.

**Comment by fmichonneau** [comment]
There is now a new make target:

```bash
make check-spelling
```

that does spell checking on the lessons (Rmd and md files). There are no typos at this stage, but there might be some bad grammar left. I'll do another read over in a little while
