### ISSUE TITLE
Check that the code included in the lessons works

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#187]
This issue is for the live coding examples (there will be another one for the challenges)

- [x] Before we start
- [x] Introduction to R
- [x] Starting with data
- [x] Aggregating and analyzing data with dplyr
- [x] Data visualization with ggplot2
- [x] R and databases

**Comment by sdtaylor** [comment]
Before we start is good. It only includes a few help and diagnostic commands.

**Comment by fmichonneau** [comment]
thanks @sdtaylor !

**Comment by sdtaylor** [comment]
`Introduction to R` is good

**Comment by sdtaylor** [comment]
`Starting with data` checks out

**Comment by sdtaylor** [comment]
At the end of the dplyr lesson the `write.csv()` command errors out because the `data_output` folder isn't created yet. It's mentioned in the section "Before we start" but otherwise there is no specific instruction to create it anywhere.   

The dplyr lesson is good  otherwise.

**Comment by sdtaylor** [comment]
All the code works in the ggplot2 and database sections. I made a PR with two minor adjustments on the formatting. #196

**Comment by fmichonneau** [comment]
Thanks so much for doing this @sdtaylor !

For the creation of the data_output folder in the dplyr lesson, I think it's OK to leave it as it is. There is a chunk that is being evaluated programmatically to render the lessons; and if participants forget to create the directory in the first lesson, they can do it manually here. If you (or someone else) has a different opinion on this, don't hesitate to let us know.

I'm closing as all the chunks have otherwise been shown to be accurate.
