### ISSUE TITLE
Hierarchies and coercion [instructor-training]

### ISSUE THREAD

**Issue by willpearse** [datacarpentry/R-ecology-lesson#193]
On line 346 of the lesson, one of the challenge questions is to "a diagram that represents the hierarchy of the data types?". My concern is that the word "hierarchy", as far as I can see, is only used within this lesson.

Would it be possible to replace this with something like "You've probably noticed that objects of different types get converted into a single, shared type. In R, we call converting objects from one class into another class _coercion_. These conversions happen according to a hierarchy, whereby some types get preferentially 'demoted' into other types. Could you draw this hierarchy of types?".

Sorry for not submitting a pull request, but for something this small (and which involves introducing the concept of coercion) I thought it better to bring it up as a discussion topic first!

**Comment by fmichonneau** [comment]
Hi @willpearse 

Thanks for the suggestion. I think  this wording makes things clearer.
Maybe specify that this applies within a vector: "... into a single, shared type *within a vector*."
Maybe also consider changing "demoted" to "converted" or "coerced" to keep things simpler. 

If you submit a PR, please only edit the Rmd file, and I think this text is included twice (once in the main lesson, and once in the chunk for the challenge), so please change it in both places.
