### ISSUE TITLE
"Manipulation --> Plotting" or "Plotting --> Manipulation"? [instructor-training]

### ISSUE THREAD

**Issue by willpearse** [datacarpentry/R-ecology-lesson#194]
I can't see that the session on data manipulation sufficiently modifies the data frame in the lesson that it wouldn't be possible to plot the data before manipulating it. Would it make more sense to _plot_ the data before manipulating?

This might seem trivial (and it is, I suppose!) but I wonder if it might help the students get a firmer grip on what's going on with the dataset. Ecologists love to have data they can "hold onto", and I wonder if doing it this way round would provide them with something more tangible. Indeed, given the students are subsetting the data to look at particular sections of it, it might even help them get an intuitive idea of the stories the data were telling, etc., to motivate why they're subsetting the data in the first place. Maybe if they have a clearer idea, from the plots, of why they want to be subsetting the data in the first place, it would help them out.

I find it hard to believe a lot of discussion didn't go into the ordering of the lessons, so please feel free to tell me to shut up - I won't be offended :D

**Comment by fmichonneau** [comment]
Yes, it's something we have considered and want to change (e.g., #93 ).
We are going to "release" this version of the lesson in the next couple of week so we don't want to include large changes in the structure of the lesson, but for the next iteration it's high on the list of priorities. We want to start with plotting before doing anything else to motivate the rest of the lesson content.

**Comment by willpearse** [comment]
Makes sense. Thanks!

**Comment by fmichonneau** [comment]
We are slowly working on this now, so even if it's not completed yet, I'm going to close.
