### ISSUE TITLE
revise challenges: Starting with data > Indexing and subsetting data frames

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#198]
(from @sdtaylor)
* Use nrow() to get the last 100 rows.
Covered previously? Yes/No. Students will have to use nrow() twice but otherwise this is the same as above. The first way I would try this is surveys[nrow(surveys)-100:nrow(surveys),], but this doesn't work as it evaluates 100:nrow(surveys) first and then subtracts that from nrow(surveys). To fix that there must be surveys[(nrow(surveys)-100):nrow(surveys),], which probably won't be obvious to students. Is there another answer that was intended here?

**Comment by fmichonneau** [comment]
I agree this is unnecessarily complicated. A better approach would be to use tail(). What do you think of replacing this challenge, by "use tail() to get the last 100 rows of the data frame?", a little easier, but more realistic, and could provide a good review of the possibilty of passing arguments to head and tail.

**Comment by sdtaylor** [comment]
How about "Use nrow() to get the row that is in the middle of the data.frame()?". It's not something you'd ever do, but still gets the idea across of selecting rows dynamically. The answer would be `surveys[nrow(surveys)/2,]` which works even though it returns a decimal.

**Comment by fmichonneau** [comment]
That's a good idea, I'm going to switch the challenge.
