### ISSUE TITLE
revise challenges: R and databases > Complex database queries

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#200]
(from @sdtaylor)
* Summarize counts of genus by plot_id
Previously covered? No. If I read this correctly then it would require n_distinct() which hasn't been covered yet.

**Comment by fmichonneau** [comment]
I agree the way the question is formulated is ambiguous.  I'm going to open a PR to use this challenge as an opportunity to introduce `n_distinct()`

**Comment by fmichonneau** [comment]
@sdtaylor do you think this section on `n_distinct` I included in the referenced PR is useful?

**Comment by sdtaylor** [comment]
Yep, absolutely. Maybe add a note reminding them that `n_distinct()`, like all dplyr functions, works on regular dataframes as well as sqlite connections.
