### ISSUE TITLE
find a better way to display answers to challenges

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#201]
they are in the source code of the Rmd files as comments, but GitHub doesn't show comments in the rendered version of these files on the website. Instructors need to have the files on their system (or look at the raw files) to be able to see the answers.

**Comment by ha0ye** [comment]
Will look into it (and combine with other formatting fixes).

**Comment by fmichonneau** [comment]
the answers are now included directly in the lessons, and hidden by default.
