### ISSUE TITLE
Update CONTRIBUTING

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#205]
As part of the release process, we need to make sure that CONTRIBUTING.md is up to date.

**Comment by ha0ye** [comment]
Not sure about exact details here, but I did some minor touchup in my formatting fixes. (PR #235)

**Comment by ashander** [comment]
I think @ha0ye has made some edits and it looks good. There is a broken link to LICENSE, though, which I'll fix now
