### ISSUE TITLE
Rewording lesson objectives: before we start

### ISSUE THREAD

**Issue by dvanic** [datacarpentry/R-ecology-lesson#214]
_Describe the purpose of the RStudio script, console, environment, and plot windows._

Perhaps change to:

_Describe the purpose of RStudio's Source, Console, Environment, and Plots windows._

- this is what the windows are called in RStudio (at least on my Mac), so perhaps it's best if we use the same terminology as in Rstudio so as not to confuse leareners?

_Organize files and directories for a set of analysis in an R Project._

Perhaps change to:

_Organize files and directories for a set of analys**e**s in an R Project._

or 

_Organize files and directories for an analysis in an R Project._

**Comment by fmichonneau** [comment]
good point. For the first one, maybe also replace "windows" with "panes". For the second one, maybe change "in an R project" with "as an R project".

**Comment by tracykteal** [comment]
Addressed in https://github.com/datacarpentry/R-ecology-lesson/pull/248
