### ISSUE TITLE
Phrasing: before we start - too much analyses??

### ISSUE THREAD

**Issue by dvanic** [datacarpentry/R-ecology-lesson#216]
R provides a framework that allows you to combine **analyses** across many scientific disciplines to best suit the **analyses** you want to use on your data.

Should this be paraphrased to

R provides a framework that allows you to combine statistical tests and analytical approaches developed for distinct scientific disciplines to allow you to easily customise your analysis to do exactly what you want it to do with your data.

or some other paraphrasing....

**Comment by fmichonneau** [comment]
I agree, this repetition of the word analyses is not needed.

**Comment by tracykteal** [comment]
Closed by https://github.com/datacarpentry/R-ecology-lesson/pull/249
