### ISSUE TITLE
Rewording: before we start: panels in Rstudio

### ISSUE THREAD

**Issue by dvanic** [datacarpentry/R-ecology-lesson#217]
RStudio is divided into 4 “Panes”: the editor for your scripts and documents (top-left, in the default layout), the R console (bottom-left), your environment/history (top-right), and your files/plots/packages/help/viewer (bottom-right). The placement of these panes and their content can be customized (see menu, RStudio -> Preferences -> Pane Layout). 

should it be paraphrased to call the panes by the names RStudio uses them? i.e. 

RStudio is divided into 4 “Panes”: the **Source** pane, which is the editor for your scripts and documents (top-left, in the default layout), the R **Console** (bottom-left), your **Environment**/**History** (top-right), and your **Files/Plots/Packages/Help/Viewer** (bottom-right). The placement of these panes and their content can be customized (see menu, RStudio -> Preferences -> Pane Layout).

**Comment by fmichonneau** [comment]
That would be very helpful, +1!
