### ISSUE TITLE
Should we include Mac shortcuts?

### ISSUE THREAD

**Issue by dvanic** [datacarpentry/R-ecology-lesson#218]
The shortcuts in the lesson are for Windows (ctrl + enter). Should we also include the Mac ones (Cmd + enter) for learners/instructors?

**Comment by fmichonneau** [comment]
I think that Crtl + Enter also works for mac, but it's a good idea to add them in the lesson. Any other OS-specificities may also need to be listed in the instructor guide.

**Comment by ha0ye** [comment]
Working on it (will combine with other formatting fixes).

**Comment by ashander** [comment]
awesome looks like this is closed by #235 

ps @ha0ye if you write 'closes #<number of the issue>' ([or some other similar keywords](https://help.github.com/articles/closing-issues-via-commit-messages/)) in the commit or PR it'll close the issue automatically when merged

**Comment by ha0ye** [comment]
@ashander I did not know that. Thanks!
