### ISSUE TITLE
Rewording: before we start: entering commands

### ISSUE THREAD

**Issue by dvanic** [datacarpentry/R-ecology-lesson#219]
This section assumes that you don't want to keep typing, but what if you do?

 If you’re in RStudio and this happens, click inside the console window and press Esc; this will cancel the incomplete command and return you to the > prompt.

perhaps paraphrase to 

 If you’re in RStudio and this happens, and you thought you had finished typing your command, click inside the console window and press Esc; this will cancel the incomplete command and return you to the > prompt.

**Comment by fmichonneau** [comment]
That's a good idea. Maybe even remove the "If you are in RStudio" and replace with "When this happens..." as we don't talk about how to use R in other contexts.
