### ISSUE TITLE
Rewording: introduction to R str()

### ISSUE THREAD

**Issue by dvanic** [datacarpentry/R-ecology-lesson#220]
The function str() provides an overview of the object and the elements it contains. It is a really useful function when working with large and complex objects:

Should we change this to 

The function str() provides an overview of the **structure of an** object and the elements it contains. It is a really useful function when working with large and complex objects:

This is how I remembered what str() does, and it's really helpful to remember that str() gives you the structure of an R object.

**Comment by fmichonneau** [comment]
yes, adding the mention to the word "structure" here would make things clearer.
