### ISSUE TITLE
Rewording: introduction to R - use proper "mathematical" terms?

### ISSUE THREAD

**Issue by dvanic** [datacarpentry/R-ecology-lesson#221]
Here, < stands for “smaller than”, > or “bigger than”, >= for “bigger or equal to”, and == for “equal to”. 

Isn't the more "standard" way of reading this in mathematics class "less than" "greater than" "greater than or equal to" and "less than or equal to"?

**Comment by fmichonneau** [comment]
yes, using the correct mathematical terms would be better
