### ISSUE TITLE
Introduction to R: lesson objectives: working directory

### ISSUE THREAD

**Issue by dvanic** [datacarpentry/R-ecology-lesson#222]
Learning objective is:
Define the following terms as they relate to R: script, function, working directory, assign, object, variable.

Working directories are not discussed in this lesson at all, and are instead discussed in the "before we start" previous lesson. Should this objective be split into two, and placed in this and the previous lesson?

**Comment by fmichonneau** [comment]
yes, splitting it to reflect the actual content of the lesson would be great
