### ISSUE TITLE
Manipulating and analyzing data frames: do we really need to mention plyr vs dplyr?

### ISSUE THREAD

**Issue by dvanic** [datacarpentry/R-ecology-lesson#223]
The thinking behind it was largely inspired by the package plyr which has been in use for some time but suffered from being slow in some cases. dplyr addresses this by porting much of the computation to C++. 

Is this statement necessary? Do novice learners care about dplyr vs plyr??? And that dplyr uses C++?

**Comment by fmichonneau** [comment]
I think it mattered when dplyr was still relatively new, and plyr was more widely used. But I agree it hasn't aged well. So I'm +1 on removing the mention to plyr.

I don't have strong feelings regarding the mention of C++. I feel it's important to explain why it's faster that similar operations that would be performed using the base functions in R, and some of the specificities of dplyr. I also agree that it's a level of detail that may not be necessary for beginners.

**Comment by dvanic** [comment]
I just don't know how many beginners will know that using C++ means you can carry out computations faster... Although I also think your point about it being faster than *base* R because it's in C++ is actually important, and maybe that's what we should highlight - not that it's faster than plyr, but that it's faster than base...

**Comment by fmichonneau** [comment]
fix in 3691de11b863fc55b8e196945f78b5ef93019481
