### ISSUE TITLE
Manipulating and analysing data frames: should we specify immediately that dplyr is for data frames?

### ISSUE THREAD

**Issue by dvanic** [datacarpentry/R-ecology-lesson#224]
dplyr is a package for making data manipulation easier.

should this be paraphrased to

dplyr is a package for making manipulation of data in data frames easier.

**Comment by fmichonneau** [comment]
maybe tabular data instead. dplyr can also be used on objects that are not data frames (tables in a database for instance).

**Comment by dvanic** [comment]
Agreed! I actually didn't know about this (as I don't use much SQL for work), and only saw it when working through the materials last night - dplyr is EVEN MORE AMAZING than I initially thought! :)
