### ISSUE TITLE
Manipulating and analysing data frames: should we mention tibbles?

### ISSUE THREAD

**Issue by dvanic** [datacarpentry/R-ecology-lesson#226]
When you run the example code:

    surveys %>%
      group_by(sex) %>%
      summarize(mean_weight = mean(weight, na.rm = TRUE))

R returns the following:

    # A tibble: 3 × 2
         sex mean_weight
      <fctr>       <dbl>
    1           64.74257
    2      F    42.17055
    3      M    42.99538

Should we mention the word tibble here since we're going to talk about it below (without naming it properly, and just giving the abbreviation)?

"You may also have noticed that the output from these calls doesn’t run off the screen anymore. That’s because dplyr has changed our data.frame to a tbl_df. The tbl data structure is very similar to a data frame; for our purposes the only difference is that, in addition to displaying the data type of each column under its name, it only prints the first few rows of data and only as many columns as fit on one screen. "

**Comment by fmichonneau** [comment]
yes, that's a good idea. The word tibble didn't exist yet when this lesson was created :smile:
