### ISSUE TITLE
try to use Travis to build the lessons

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#23]

**Comment by ethanwhite** [comment]
+1

**Comment by tracykteal** [comment]
also +1. Great idea. @fmichonneau are you interested in trying to implement this? I think @richfitz might be interested.

**Comment by fmichonneau** [comment]
I have a prototype working for this at https://github.com/fmichonneau/test-travis-dc

It would be great if @ethanwhite and @richfitz could review the code/approach I wrote to do it (check the `.publish_html.sh` and `.travis.yml` file).

If we go this route, it seems best to keep the Rmd files into a master branch and then have the html files (or md files if we use jekyll for the rendering) into the gh-pages branch.

I would also be interested in feedback regarding whether we should create a "dummy" user to whom the travis commits are assigned.

**Comment by ethanwhite** [comment]
Looks OK to me from a quick read. I agree on the Rmd in master, html/md in gh-pages. I think a dummy "datacarpentrybot" or equivalent user for this is a good idea.
