### ISSUE TITLE
Download file is empty.

### ISSUE THREAD

**Issue by dianitalou24** [datacarpentry/R-ecology-lesson#230]
When I typed this command it tries to download the file, but it appears to be empty. 
download.file("https://ndownloader.figshare.com/files/2292169", "data/portal_data_joined.csv")

My colleague had the same problem. To get the data I had to go directly to the URL and download the file to my computer.

**Comment by fmichonneau** [comment]
Hi @dianitalou24 

It seems to work for me today. Could you please retry, and paste here the output you get when typing this command at your R terminal? Please make sure that the "data" directory exists first (you can create it by typing `dir.create("data")` at your R terminal if it doesn't exist. Here is what I see:

```r
> download.file("https://ndownloader.figshare.com/files/2292169", "data/portal_data_joined.csv")
trying URL 'https://ndownloader.figshare.com/files/2292169'
Content type 'binary/octet-stream' length 3062750 bytes (2.9 MB)
==================================================
downloaded 2.9 MB
```

**Comment by fmichonneau** [comment]
any update on this @dianitalou24 ?

**Comment by emhart** [comment]
I bet this is actually because @fmichonneau has a `data/` in the relative path and @dianitalou24 doesn't.  See below.

```
> download.file("https://ndownloader.figshare.com/files/2292169", "data/portal_data_joined.csv")
downloaded 0 bytes

Error in download.file("https://ndownloader.figshare.com/files/2292169",  :
  cannot download all files
In addition: Warning messages:
1: In download.file("https://ndownloader.figshare.com/files/2292169",  :
  URL https://ndownloader.figshare.com/files/2292169: cannot open destfile 'data/portal_data_joined.csv', reason 'No such file or directory'
2: In download.file("https://ndownloader.figshare.com/files/2292169",  :
  downloaded length 0 != reported length 3062750
> download.file("https://ndownloader.figshare.com/files/2292169", "portal_data_joined.csv")
trying URL 'https://ndownloader.figshare.com/files/2292169'
Content type 'binary/octet-stream' length 3062750 bytes (2.9 MB)
==================================================
downloaded 2.9 MB
```

**Comment by emhart** [comment]
@dianitalou24 were you running as stand alone line or from `setup.R`?

**Comment by Pakillo** [comment]
It works for me too, but gave an error if `data` folder was not already present. I agree that might be the reason

**Comment by fmichonneau** [comment]
closing this for now as it seems that this is not directly a problem with the infrastructure or content of the lesson. Feel free to re-open if more info can be provided.
