### ISSUE TITLE
visualisation-ggplot: Changing font size to 'Arial' gives many warnings in Windows

### ISSUE THREAD

**Issue by Pakillo** [datacarpentry/R-ecology-lesson#239]
See https://rawgit.com/Pakillo/R-ecology-lesson/Pakillo-fixing-typos/04-visualization-ggplot2.html

Trying to change font to Arial
```
ggplot(data = yearly_sex_counts, aes(x = year, y = n, color = sex, group = sex)) +
    geom_line() +
    facet_wrap(~ species_id) +
    labs(title = 'Observed species in time',
        x = 'Year of observation',
        y = 'Number of species') +
    theme_bw() +
    theme(text=element_text(size=16, family="Arial"))
```

gives many (!) warnings as the font cannot be found in Windows:

#> Warning in grid.Call(L_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
#> font family not found in Windows font database

I suspect this will happen to many/most Windows users... I know this can be fixed, but perhaps it's better avoiding getting into that trouble?

> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10    digest_0.6.12   rprojroot_1.2   assertthat_0.1  R6_2.2.0        DBI_0.6         backports_1.0.5
 [8] magrittr_1.5    evaluate_0.10   stringi_1.1.3   lazyeval_0.2.0  rmarkdown_1.4   tools_3.3.3     stringr_1.2.0  
[15] yaml_2.1.14     htmltools_0.3.5 knitr_1.15.1    tibble_1.2

**Comment by fmichonneau** [comment]
yes, I agree... this is unnecessarily confusing, and many of our learners use Windows. It's probably best to drop this.

**Comment by fmichonneau** [comment]
Could someone with Windows confirm they are also seeing these warnings?

**Comment by catherinehulshof** [comment]
I can confirm. I am also seeing these warnings on Windows.

**Comment by fmichonneau** [comment]
I looked a little into this and there is no easy fix as far as I can tell. My understanding is that one would need to install 3 packages as described in the README of https://github.com/wch/extrafont This seems like an overkill for a DC workshop.

I can see 2 options:

1. leave it as it is, and list this as a potential problem in the instructor guide
2. remove the mention to changing the fonts

I'm leaning slightly towards option 1, but I don't have strong feelings.

**Comment by Pakillo** [comment]
I vote for option 2. I think it's an unnecessary complication for an introductory workshop like this. I think it's fine to just change font size, label orientation etc. to show how to modify themes/plot appearance. I don't think changing the font type is worth the complications in this case. 
But that's just my opinion, of course! Do what you find best :)

**Comment by tracykteal** [comment]
I also agree with option 2. We could put in a sentence like "It's also possible to change the fonts and you can install packages such as ... that give you access to different fonts".
