### ISSUE TITLE
data frame vs. dataframe

### ISSUE THREAD

**Issue by zmml** [datacarpentry/R-ecology-lesson#242]
The spelling of "data frame" is inconsistent throughout the lessons - sometimes it's written as "data frame" and sometimes it's written as "dataframe" (ex. [04-visualization-ggplot2](https://github.com/datacarpentry/R-ecology-lesson/edit/gh-pages/04-visualization-ggplot2.Rmd) line 31 vs. line 57). Same with "dataset" vs. "data set"

**Comment by fmichonneau** [comment]
it should be "data frame". If you can make a PR to fix this that would be great!

**Comment by ashander** [comment]
I'll fix this

**Comment by benmarwick** [comment]
#251 fixes 04-visualization-ggplot2.Rmd

**Comment by ashander** [comment]
OK thanks @benmarwick are you also working on the other aspects of this issue?

**Comment by benmarwick** [comment]
"dataset" vs. "data set" is all yours :) Sorry about the duplicated effort.

**Comment by fmichonneau** [comment]
I'm +1 for dataset

**Comment by ashander** [comment]
no worries. hard to avoid it w/ distributed work
