### ISSUE TITLE
Mac vs. Windows compatibility for RStudio navigation instructions

### ISSUE THREAD

**Issue by kmpeck** [datacarpentry/R-ecology-lesson#243]
Check files for compatibility for RStudio menu instructions. 

For example, in 00-before-we-start, the instructions for changing the pane layouts is:
RStudio -> Preferences -> Pane Layout

This is only applicable for Macs. For Windows, the instructions would be
RStudio -> View -> Panes -> Pane Layout...

Should we consider putting both in?

**Comment by fmichonneau** [comment]
Yes that seems useful.

I'm on Linux and the second one is available to me. I notice however, that I can also access this menu from Tools > Global Options > Panel Layout.

Would this latter option also be the same on Mac and Windows?
