### ISSUE TITLE
Add paragraph on how to use RStudio interface to seek help

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#254]
Related to #174 

Currently in lesson "Before we start", one of the learning objectives is "Use the built-in RStudio help interface to search for more information on R functions." However, in the lesson we don't use the RStudio help at all, just the command line. It would be good to add a section on how to use the help interface with screenshots.

**Comment by cjieming** [comment]
Hi I am new here, trying to complete the instructor checkout. I can help with this. Do you mean something like to add a description about how to type a query into the Rstudio search bar for functions (see attached screenshot)?
<img width="339" alt="rstudiohelp" src="https://cloud.githubusercontent.com/assets/1273131/24942137/ea2a3794-1f03-11e7-83fd-aec91f9f1a78.png">

**Comment by fmichonneau** [comment]
Hi @cjieming 

Yes, a screenshot like the one you suggest and a sentence or two would be great.

We are planning on releasing the lesson in the next couple of days, so if you can send this soon that would be really helpful. Don't hesitate to let me know if you need any assistance.

**Comment by cjieming** [comment]
Hi @fmichonneau, how about I create a section under "Seeking help", name it exactly "Use the built-in RStudio help interface to search for more information on R functions". I will first add the screenshot above, with caption "RStudio help interface". Then the following description:
"One of the most fastest ways to get help, is to use the RStudio help interface. This panel by default can be found at the lower right hand panel of RStudio. As seen in the screenshot, by typing the word "Mean", RStudio tries to also give a number of suggestions that you might be interested in. The description is then displayed window." 
Let me know this is ok and I will edit and send a pull request.

**Comment by fmichonneau** [comment]
yes, that looks good! Just make sure the first sentence starts with "One of the fastest ways..."

**Comment by cjieming** [comment]
Hi I have a pull request here: #259
