### ISSUE TITLE
Formatting Dates in R

### ISSUE THREAD

**Issue by DanielleQuinn** [datacarpentry/R-ecology-lesson#263]
I see that in an early segment of this lesson "Data Organization in Spreadsheets", there is a great discussion on how to handle dates in spreadsheets. I think a natural and important extension of this is what then to do with your nicely organized (year / month / day / hour / minute / second) variables once your data have been imported into R.

Wickham provides a great package {lubridate} to format these variables into Date objects recognized as such by R. This package also provides functions that can be used to deal with things like times zones, daylight savings, leap years, weekdays, etc.

Has there been any discussion about adding a piece to the Data Analysis and Visualization in R about Dates in R?

Thanks,
Danielle

**Comment by fmichonneau** [comment]
Thanks for the suggestion Danielle. I think it's a good idea, and we could do a better job at connecting concepts across lessons. I don't think we have room to go too much into details of date manipulations, but a brief mention that demonstrates how to get started would be very welcome. A challenge is going to find a good place in the lesson to introduce this. Do you have a suggestion?

**Comment by DanielleQuinn** [comment]
If the students have already separated the date / datetime components in their spreadsheet, a nice challenge might be to use dmy() [for date] or dmy_hms() [for datetime] to parse that information together into a Date object and add it to their dataframe as a column called 'date'.

It's a simple but powerful process : )

**Comment by fmichonneau** [comment]
Hi @DanielleQuinn 

That sounds good to me! It seems that we could motivate this by making a plot with this new date column (at least, I know that's why I typically have to create such date columns). I'm not sure what it would like (given the timing of the sampling), but if you could come up with a pull request for this that would be great. From there, we'd be happy to provide feedback to include it in the lessons.

Thanks!

**Comment by fmichonneau** [comment]
closed by 95683668b225e99c94cb8205dd9c7abc1e66e185
