### ISSUE TITLE
A short blurb to introduce the tidyverse is needed

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#267]
we need to explain better what is the tidyverse and the tidyverse package. It doesn't have to be long but I think there are 3 concepts that need be untangled:

- what is the tidyverse?
- what is the tidyverse package?
- technical: why installing tidyverse allows you to call library(dplyr)?

**Comment by anarchivist** [comment]
I'm taking a look at this a bit more closely in anticipation of making a pull request to propose some changes. It appears that the tidyverse is referenced in four key places: the index page, the intro to R, the manipulating data frames page, and the visualization page. 

Also, it looks like there's not really in-depth description of packages and how they work, other than a brief acknowledgement of the R package ecosystem in the "before we start" page.

Do you think it would be worthwhile to include a larger context-setting section on packages and how they work in this lesson? If so, where might be a logical place to incorporate it?

**Comment by fmichonneau** [comment]
Thanks for being willing to tackle this!

Yes, I think a short(ish) section on introducing packages in general and tidyverse in particular would be great.

I could easily be convinced otherwise but I think that including this at the end of the "Intro to R" section would be a good fit. The "before we start" is already pretty long and doesn't include a lot of challenges, so adding more technicality at the beginning would delay further the "real" beginning of the lesson. We could also include it later in the lesson, but including it at the end of intro to R would also allow us to switch to `read_csv` from readr in the starting with data.

**Comment by ewallace** [comment]
I would love to get involved in this too (am doing instructor checkout). Having seen this lesson in action a couple of times, I think communicating the point of the tidyverse, and of the dplyr verbs, 

@anarchivist what can I do to most usefully complement your work?
