### ISSUE TITLE
Use readr to read and write csv files

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#268]
Now that we have packages from the tidyverse available, I think we should consider swtiching to readr::read_csv and readr::write_csv. Thoughts?

**Comment by kathy0305** [comment]
Yes, it only makes sense to do so; we need to be consistent.
Tasks:

- Convert all files/ lesson that contain read.csv or write.csv to read_csv and write_csv.
- Lesson "Starting with Data": What are Data Frames, include tibbles explanation
- Lesson "Starting with Data": stringsAsFactors=FALSE lesson. Delete/update

Questions: 
- Should we still refer to them as  Data Frames or as tibbles ?? tibbles are data frames, so maybe keep the data frame references??
- Should we tackle read_table??

**Comment by aurielfournier** [comment]
I am fine with that. But I think we would atleast still need some kind of mention/discussion of read/write.csv. Since learners will see it all the time in examples/others code, and I would want them to be aware off it, and esp of the stringsAsFactors. 

I'm a heavy tidyverse user, but I still use read.csv. so maybe I'm just being a grumpy late adopter.

**Comment by kathy0305** [comment]
Yep I agree 100%. I struggled with that idea myself when I designed my workshops that are based on tidyverse, the workshops is for R Newbies. I didnt want my students to come back to me and ask about $ and read.csv ...and base R stuff. So I have a base R introductions too.

**Comment by WeeBeasties** [comment]
Is anyone currently working on this? I'm completing instructor training and this looks like a way that I could make a meaningful contribution. I currently use both base R and the tidyverse to load data into my projects. So, I'm comfortable enough take it on.

**Comment by kathy0305** [comment]
I am working on updating it! my apologies for not logging the issues here. Francois and I have been communicating through email, to figure out the best way to do this.  We came to a consensus last week, and I'll be updating them this week.

**Comment by WeeBeasties** [comment]
I kind of assumed so (but I try to assume very little in life). I definitely didn't want to duplicate effort or step on toes. There's plenty to be done; I'll find another way to chip in. Cheers!

**Comment by kathy0305** [comment]
I am in the same boat, wanted to make sure I don't go overboard with the changes and wanted to get the green light before I assume things.  I actually have the changes ready to go, just tweaking few things. I'll appreciate another pair of eyes after that .
