### ISSUE TITLE
ggplot2 challenges switch between weight and hindfoot_length

### ISSUE THREAD

**Issue by jebyrnes** [datacarpentry/R-ecology-lesson#270]
I find the challenges in general for this lesson might need some restructuring. In particular, this one 

> In many types of data, it is important to consider the *scale* of the
> observations.  For example, it may be worth changing the scale of the axis to
> better distribute the observations in the space of the plot.  Changing the scale
> of the axes is done similarly to adding/modifying other components (i.e., by
> incrementally adding commands). Try making these modifications:
>
> - Represent weight on the log10 scale; see `scale_y_log10()`.
>
> - Create boxplot for `hindfoot_length`.
>
> - Add color to the datapoints on your boxplot according to the plot from which
>   the sample was taken (`plot_id`).

is odd - it implicitly asks to switch to weight, then asks for a boxplot of `hindfoot_length`, which is what all of the previous sections of class was about, and then datapoints are asked for without referencing `geom_jitter`. Students were confused in looking at the lesson, and I had to rewrite on the fly.

**Comment by aurielfournier** [comment]
This is a good catch. Thank you!

Would you be willing to reorder the text so it doesn't switch back and forth and add in the geom_jitter reference?

**Comment by csjohns** [comment]
Reviewing this lesson, there is also confusion about variable to be plotted on the y-axis earlier in the boxplot lesson as well, with the text referencing "the distribution of weight within each species" but the aesthetics in the ggplot() call setting the y-axis to hindfoot_length.

I'm happy to tidy up both the lesson and the challenge text (I'm finishing my instructor training checkout)

**Comment by aurielfournier** [comment]
That would be wonderful! Please make the changes and submit as a pull request :)
