### ISSUE TITLE
Issue on windows computers with src_sqlite

### ISSUE THREAD

**Issue by jebyrnes** [datacarpentry/R-ecology-lesson#272]
In the SQL in R lesson, windows computers fail loading the database with an error:
" database disk image is malformed"

During our class, we fixed it by adding
`mode = wb` to the download.file call

    download.file(url = "https://ndownloader.figshare.com/files/2292171",
                  destfile = "data/portal_mammals.sqlite", mode="wb")

**Comment by fmichonneau** [comment]
good call. I'm going to add the mode argument. Thanks!
