### ISSUE TITLE
Replace link to style guide

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#275]
Hadley wrote a comprehensive style guide for the tidyverse: http://style.tidyverse.org/
that we may want to link to. It looks very comprehensive, but it might be intimidating for beginners to think they have to ingest all of this content.

**Comment by aurielfournier** [comment]
Oh this is great. But yes a lot to take in. Would need some appropriate text to give it context, and a 'warning lots of info contained here'
