### ISSUE TITLE
Feedback and proposed improvement to starting with data in R

### ISSUE THREAD

**Issue by InaGee** [datacarpentry/R-ecology-lesson#283]
Hello, 
this is a contribution following the software carpentry instructor training.

Feedback:
I very much enjoyed the lesson "starting with data in R" because it follows the steps I would take to teach absolute beginners in R. Starting directly by importing data, explaining data frames and manipulating data are key tasks everyone needs to use in R. This gives the user an applicable task compared to doing some random calculations for a start. Also, the explanation of dataframes has been done in a comprehensive and easy to follow way.

Improvement:
One thing I struggled with as a beginner was the import of data. Using read.csv() is a great function and I would recommend to add a little trouble shooting section in case read.csv() does not give you the imported data you want. As a foreign R user the option dec = "," is very helpful because if you want to import a table written in German you often struggle with the default decimal sign. Following this comment the secification of the separator (sep = ";") can be useful handling data tables from foreign sources.  Also, if the first row in your table contains one fewer field than the number of columns set header = TRUE so that R can identify what the header is. 

I hope this was a helpful comment,
Cheers,
Ina

**Comment by fmichonneau** [comment]
Hello Ina,

Thanks for the feedback. It's great that you enjoyed the lesson, and we are always happy to get more feedback.

You rise a good point about importing data. I had open an issue (#268) a little while back suggesting that we switch to using the **`readr`** package given that it's much faster and `read.csv` and gives better error messages.

I think typically for countries that use `,` as the decimal separator, one could use the `read.csv2` and `read_csv2` as they already have the correct parameters to also use `;` for the separator.

Would you be willing to do a pull request on the lesson to include your suggestion?

Thanks!
