### ISSUE TITLE
Problem with date conversion in "starting with data"

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/R-ecology-lesson#295]
I'm sure this must have come up at several workshops so far, but I couldn't find any issues referencing this problem so thought I'd start a new thread. 

The last bit of http://www.datacarpentry.org/R-ecology-lesson/02-starting-with-data.html has learners converting the dates in the dataset to POSIXct objects using ymd(). However, using the code from the lesson leads to a warning message "129 failed to parse". I took a deeper look and found that all 129 of these problematic dates are data that were collected on either April or September 31st, 2000. April and September only ever have 30 days. :-D 

This seems like a great opportunity for a little quality control exercise. 

`test_ymd = ymd(dates)`
`dates[which(is.na(test_ymd))]`

Thoughts?

Pinging @kristinariemer since we're teaching together this week.

**Comment by fmichonneau** [comment]
Hi @ErinBecker 

It's actually the first time it's come up as the date parsing is a recent addition to the lesson. I agree, it seems like a good opportunity for quality control. I'll have to look into it more to see how we can incorporate into the flow of the lesson. Thanks for bringing it up!

**Comment by ErinBecker** [comment]
Thanks @fmichonneau, glad I could be of help! I'm going to try having the learners use the code I quoted above to investigate the weird dates and then replace with April 30th and Sept 30th.

What do you think?

**Comment by fmichonneau** [comment]
yes, that sounds good to me, and it gives a good opportunity to do something that they would have to do in "real life"

**Comment by ErinBecker** [comment]
Related - now that there is a "date" column, the final filtered "species_complete" dataframe should have 14 columns, not 13. 

Text from lesson: 
"To make sure that everyone has the same dataset, check that surveys_complete has 30463 rows and 13 columns by typing dim(surveys_complete)."
