### ISSUE TITLE
keyboard shortcut for pipes

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/R-ecology-lesson#296]
The http://www.datacarpentry.org/R-ecology-lesson/03-dplyr.html lesson says  "you can type the pipe with Ctrl + Shift + M if you have a PC or Cmd + Shift + C if you have a Mac." However, on my Mac keyboard, the shortcut is Cmd + Shift + M. 

Does anyone else have the same experience?

**Comment by fmichonneau** [comment]
you're correct, that's a typo.

**Comment by fmichonneau** [comment]
this has been fixed in the lesson.

**Comment by ErinBecker** [comment]
Thanks @fmichonneau!
