### ISSUE TITLE
Shiny lesson

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/R-ecology-lesson#30]
At the Federal Reserve Board workshop where we used the gap minder dataset @msmorul developed and taught a Shiny lesson

https://github.com/datacarpentry/2015-06-30-FederalReserveBoard/wiki/Shiny-Lesson

It would need a little more detail to hand to an instructor and to use the ecology dataset, but there were good comments on the lesson in the survey. It might be a module to develop as something more advanced or a demo at the end of R. It definitely has the 'wow' factor and is also useful.

**Comment by karthik** [comment]
I'm a bit reluctant to encourage topics like Shiny in DC bootcamps. We currently have a solid stack of topics that nicely build upon each other. We never get time to teach functions without which building even the most basic Shiny app becomes impossible. 

Perhaps we should collect such topics (APIs, Shiny) etc in a separate repo for the time being and see how they might fit into an advanced DC workshop in the future.

**Comment by msmorul** [comment]
For some background, the shiny demo was taught as a capstone in ~45m after
the https://github.com/resbaz/r-novice-gapminder lesson. This lesson was
modified for the fed and was slimmed down, reorganized and broken into two
3hr lessons over the two days. This lesson does provide a small into into
functions, so students weren't running shiny blind. From a teaching
standpoint it gave me an opportunity to reinforce earlier, somewhat
abstract concepts that had been taught. In addition to the wow factor that
Tracy mentioned, the overall sentiment that I got was this (shiny, or some
other unifying wrapup) helped the students see how what they learned could
be immediately useful.

The lesson itself was taught by first having them successfully recreate the
basic example through cut/paste from the shiny demo and doing a type-along
modification and re-run of the pieces one at a time to get to the finished
code in the repo. This let them see how each section of code was reflected
in the app while not having to deal w/ the frustration of starting an app
from nothing.

**Comment by fmichonneau** [comment]
I second @karthik's opinion.

In the appropriate context, it could work, but within the traditional 2 days schedule, it seems too advanced for beginners.

To reinforce concepts seen earlier, demonstrating how to use knitr/Rmarkdown might be more relevant to the participants.

**Comment by aurielfournier** [comment]
I agree with @karthik and @fmichonneau. Before we do Shiny we should do knitr/RMarkdown, but even that is probably farther than is realistic in 2 days.

**Comment by tracykteal** [comment]
I also agree that it wouldn't be a core lesson. We have talked about OYO (On Your Own) modules though, and this could be a good one. I'm just not sure how we would manage OYOs though, including where to put them and deciding what ones to do. Just like with main lessons, we wouldn't want a lot of lesson creep and would need to keep things actively maintained.

**Comment by fmichonneau** [comment]
closing here in favor of datacarpentry/lesson-ideas
