### ISSUE TITLE
dbplyr

### ISSUE THREAD

**Issue by maelle** [datacarpentry/R-ecology-lesson#300]
Again an issue instead of PR, sorry about that.

In the newest `dplyr` version there's no `src_sqlite` function,

```r
Error: The dbplyr package is required to communicate with database backends.
```

so one needs to install and load `dbplyr` first.

**Comment by fmichonneau** [comment]
I added instructions to install and load `dbplyr` a day or two ago at the top of the page. Are you using the latest version of the lesson?

**Comment by maelle** [comment]
🙈 nope sorry

**Comment by fmichonneau** [comment]
no problem, that wouldn't be the first time I overlooked something :grimacing:
