### ISSUE TITLE
Clarifying vector types and head() in 'Starting with Data in R'

### ISSUE THREAD

**Issue by gndaskalova** [datacarpentry/R-ecology-lesson#307]
In the starting with data lesson, one could add that logical vectors are also referred to as boolean, so that if people hear that tern later on/just in general, they won't get confused.

In this line of code:
head_surveys <- surveys[1:6, ] # equivalent to head(surveys)

I think the comment is slightly misleading, because the result is not equivalent to head(surveys) - we have created a new data frame that has the first 6 rows, whereas head(surveys) just shows the first six rows in the console. A more precise comment might be "# create data frame with first 6 rows, which you can see using head(surveys)" - a bit of a long comment, but reflects what is happening.

Here: 
f <- factor(c(1990, 1983, 1977, 1998, 1990))
as.numeric(f)               # wrong! and there is no warning...

One could add a sentence to explain why just doing as.numeric() is wrong.

**Comment by fmichonneau** [comment]
hi @gndaskalova and thanks for your suggestions!

`surveys[1:6, ]` is equivalent to `head(surveys)`. The `head()` function subsets the dataset, it doesn't just show the beginning. The comment refers to the right hand side of the assignment, maybe adding the full call in the comment would make things clearer?

A short explanation of why doing `as.numeric()` is incorrect would be welcome. Would you be willing to do a pull request for this?

**Comment by gndaskalova** [comment]
@fmichonneau Thanks for the quick reply!

I usually just use `head()` to see the first 6 rows, without assigning them to an object, so yes, I think this might be better:

```r
head_surveys <- surveys[1:6, ] # equivalent to head_surveys <- head(surveys)
```

Shall do the pull request now.
