### ISSUE TITLE
need to change call to "mammals" in sqlite lesson to list tables

### ISSUE THREAD

**Issue by ryanpeek** [datacarpentry/R-ecology-lesson#309]
Line 96 should probably be:
`src_dbi(mammals)`

Which results in:
`src:  sqlite 3.19.3 [/PATH/github/R-ecology-lesson/data/portal_mammals.sqlite]
tbls: plots, species, surveys`

The current code just calls `mammals` which results in a different output, and because  sentences following the code state "Just like a spreadsheet with multiple worksheets, a SQLite databse can contain multiple tables. In this case three of them are listed in the `tbls` row in the output above (then lists `plots`, `species`, and `surveys`)" we should change.

With recent updates to `dplyr/dbplyr`, it looks like this is no longer the case when you simply call the db connection. To list the tables and get an output that reflects the text here, use `src_dbi`.

Just ran into this during lesson so wanted to add an issue here...I can try to add pull request later.
Thanks!

**Comment by fmichonneau** [comment]
if you'd be willing to do a PR to correct this, that would be great!

**Comment by ryanpeek** [comment]
Yup will do...
