### ISSUE TITLE
Dates as data is outdated

### ISSUE THREAD

**Issue by vantuyls** [datacarpentry/R-ecology-lesson#313]
The Dates as Data section has some outdated text/examples (see image).
![screen shot 2017-09-29 at 12 34 49 pm](https://user-images.githubusercontent.com/9534576/31032876-af30fdc2-a512-11e7-80a4-a0fd17eb3ac8.png)

Specifially, the joke/note that the lesson makes about collecting data "in the future" is outdated as the "future" date in question in July 2017.

**Comment by fmichonneau** [comment]
isn't this intended for the spreadsheet lesson?

**Comment by vantuyls** [comment]
ah, yep, sorry. i'll move it over there.
