### ISSUE TITLE
03-dplyr: No row.names = FALSE option for write_csv

### ISSUE THREAD

**Issue by cengel** [datacarpentry/R-ecology-lesson#314]
`write_csv` does not write out row names (different from `write.csv`).

So at the end of the 03-dplyr episode: 

"Now that our dataset is ready, we can save it as a CSV file in our data_output folder. By default, write.csv() includes a column with row names (in our case the names are just the row numbers), so we need to add row.names = FALSE so they are not included:"

`write_csv(surveys_complete, file = "data_output/surveys_complete.csv",
          row.names = FALSE)`

should be something like:

"Now that our dataset is ready, we can save it as a CSV file in our data_output folder." 

`write_csv(surveys_complete, file = "data_output/surveys_complete.csv")`

**Comment by fmichonneau** [comment]
Thanks for catching this!
