### ISSUE TITLE
Incorrect dealing of missing values when reading data (02-starting-with-data)

### ISSUE THREAD

**Issue by tavareshugo** [datacarpentry/R-ecology-lesson#316]
Details follow below, but basically, in the "02-starting-with-data" lesson we should be reading 
data with the `na.strings = ""` option:

```
surveys <- read.csv('data/portal_data_joined.csv', na.strings = "")
```

-------------------------------------------

At the moment, the surveys data is read with default parameters:

```{r}
surveys <- read.csv("https://ndownloader.figshare.com/files/2292169")
```

And straight afterwards we realise something odd:

```{r}
head(surveys)
```

```
  record_id month day year plot_id species_id sex hindfoot_length weight   genus  species   taxa plot_type
1         1     7  16 1977       2         NL   M              32     NA Neotoma albigula Rodent   Control
2        72     8  19 1977       2         NL   M              31     NA Neotoma albigula Rodent   Control
3       224     9  13 1977       2         NL                  NA     NA Neotoma albigula Rodent   Control
4       266    10  16 1977       2         NL                  NA     NA Neotoma albigula Rodent   Control
5       349    11  12 1977       2         NL                  NA     NA Neotoma albigula Rodent   Control
6       363    11  12 1977       2         NL                  NA     NA Neotoma albigula Rodent   Control
```

There are empty cells for sex! Later on this gives rather puzzling results, for example:

```{r}
surveys %>%
  group_by(sex) %>%
  summarize(mean_weight = mean(weight, na.rm = TRUE))
```

```
# A tibble: 3 x 2
     sex mean_weight
  <fctr>       <dbl>
1           64.74257
2      F    42.17055
3      M    42.99538
```

Returns a row with an empty value for sex. 

For the rest of the lesson it feels like something is wrong with the original dataset
and we need to fix it (for example, filtering cases where `sex == ""`). But, really, what's 
wrong is the way we read the data to start with.

In the spreadsheet lesson we talk about how to encode missing values, and encourage 
the usage of empty cells. But we don't apply that principle here. What's
gone wrong is that we did not specify `na.string = ""` in `read.csv()`. 

I therefore propose that we correct the beginning of the "02-starting-with-data" lesson to be something 
like:

```{r}
surveys <- read.csv("https://ndownloader.figshare.com/files/2292169")
head(surveys)
```

Point to the fact sex has what looks like empty cells. Then check `?read.csv` and 
realise there's an option `na.strings = NA`. From the help we can see that:

> na.strings     a character vector of strings which are to be interpreted as NA values. 
Blank fields are also considered to be missing values in logical, integer, numeric 
and complex fields. 

We need to point out that, by default, `read.csv()` only converts empty cells to 
missing values if they are of type "logical", "integer" or "numeric". Therefore, 
we should really do:

```{r}
surveys <- read.csv("https://ndownloader.figshare.com/files/2292169", na.strings = "")
head(surveys)
```

Which rightly encodes missing values for `sex`.

**Comment by kjlquist** [comment]
I agree with this, and would add another Note to mention that it's a good idea to look at some of the additional arguments in general for functions that are used to read data (since this is a stage where a lot of problems can occur).

**Comment by aurielfournier** [comment]
We are working on moving all the lessons over to using `readr::read_csv` part of the `tidyverse` so soon this won't be an issue. But thank you both for bringing it up!
