### ISSUE TITLE
Selecting/filtering improvement: Demo *why* pipes are so helpful

### ISSUE THREAD

**Issue by jenniferthompson** [datacarpentry/R-ecology-lesson#327]
It might be helpful to have short examples of intermediate and nested methods to compare to a pipeline, like the below, so that students can better understand the benefit of the pipe. (Happy to open this as a PR if others agree.)

```
library(tidyverse)

surveys <- read_csv("data/portal_data_joined.csv")

## Example of intermediate steps
surveys2 <- filter(surveys, weight < 5)
surveys_sml <- select(surveys2, species_id, sex, weight)
## Naming things is hard (how to keep track, esp with >2 steps?); workspace is cluttered

## Example of nested functions
surveys_sml <- select(filter(surveys, weight < 5), species_id, sex, weight)
## No need to name a bunch of things, but hard to read

surveys_sml <- surveys %>%
  filter(weight < 5) %>%
  select(species_id, sex, weight)
## Most readable, no need to name a bunch of things, yay
```

**Comment by fmichonneau** [comment]
hi @jenniferthompson  -- Yes a short PR would be great!

**Comment by jenniferthompson** [comment]
Sounds great @fmichonneau! I'll work on it this week.

**Comment by aurielfournier** [comment]
I agree an example would be great. This is something I've struggled to teach on the fly several times, would be great to have as apart of the lesson
