### ISSUE TITLE
Renaming empty labels "missing"

### ISSUE THREAD

**Issue by kathy0305** [datacarpentry/R-ecology-lesson#329]
R-ecology-lesson
> Starting with data
> >Renaming factors

levels(sex) returned 3 levels "" "F" "M"
so we decided to rename "" (empty sex label) "missing"
levels(sex)[1] <- "missing" 

I think we should stay consistent of how R names/represents missing data with NA
specially that we introduced NA in the previous lesson. 
If the intention is to show the missing values in the plot, we can use NA in ""
levels(sex)[1] <- "NA" 

I just feel that they should start referring to missing values as NA's

**Comment by kathy0305** [comment]
ofcourse!
should we change it to 
levels(sex)[1] <- NA
or
levels(sex)[1] <- "NA"
?

**Comment by aurielfournier** [comment]
levels(sex)[1] <- NA

**Comment by kathy0305** [comment]
Ok, then when we 
plot(surveys$sex)
only F and M will show

**Comment by aurielfournier** [comment]
Oh. right. Hmm. 

I don't use baseplot enough to know how to make it label the NAs as something. 

@fmichonneau what are your thoughts? Should we leave it as 'missing' since the NAs don't get an x axis label with baseplot?

**Comment by BinxiePeterson** [comment]
I don't think the missing data should be excluded from the plot - it might be important to show the number of missing data versus M and F. But +1 for levels(sex)[1] <- NA to keep it consistent!

**Comment by fmichonneau** [comment]
I was traveling and couldn't comment earlier. My suggestion would be to use "undetermined" instead of "missing". This way we keep the data in the plot and we don't introduce the confusion over missing data being represented as NA.

**Comment by aurielfournier** [comment]
@kathy0305 would you be willing to write up a pull request with @fmichonneau suggestion?

**Comment by kathy0305** [comment]
Oh, sure! pull request on its way. Thanks

**Comment by fmichonneau** [comment]
this is has been implemented. Thanks @kathy0305 !
