### ISSUE TITLE
Change the title :Manipulating and analyzing data with dplyr

### ISSUE THREAD

**Issue by kathy0305** [datacarpentry/R-ecology-lesson#330]
I feel that we need to change the title from:
Manipulating and analyzing data with dplyr; Exporting data
should be:
Manipulating ,analyzing and exporting data with tidyverse

We already asked them to install tidyverse at the beginning. So this should be a title where we show them why we installed tidyverse. Of course we still mention that dplyr is a package under the tidyverse umbrella.

**Comment by aurielfournier** [comment]
Makes sense to me. We've slowly been trying to address these kinds of inconsistencies in the lessons. Thanks for catching another one. Would you be able to submit a pull request with this change?

**Comment by kathy0305** [comment]
I also feel that Formatting Dates section should be moved from Starting with Data to
Manipulating, analyzing and exporting data with tidyverse

We are asking them to use 
library(lubridate)

They never installed lubridate; they installed tidyverse

so we either ask to load tidyverse or move this whole section to the Manipulating, analyzing and exporting data with tidyverse

since lubridate is part of tidyverse, why introduce that first ?  I feel that's confusing

**Comment by fmichonneau** [comment]
I'm ok with changing the title to "Manipulating, analyzing and exporting data with tidyverse".

I agree that currently the lesson "starting with data" is a little awkward. Initially its goal was to accommodate the annoyances that the tidyverse mostly takes care of. In my opinion, this lesson needs to be re-thought carefully in the context of the concepts we need to cover for the dplyr and ggplot2 lessons and skills that are useful for data analysis.

`lubridate` is part of the tidyverse but not a core package. It means that it's installed as part of the tidyverse installation but not loaded on calling `library(tidyverse)`. We could move up the introduction to the tidyverse earlier, but it also feels clunky to start with an exception. Maybe it's best if we move this section as part of the data preparation for exporting the data?

**Comment by kathy0305** [comment]
I was studying for the instructors certification and found few parts confusing.  I think you are right, this lesson needs to be re-thought.  I wish there is a general data carpentry lesson, that deals with a general data, as I feel the only ecology about this lesson was the data. Maybe create a general lesson and have a separate more detail ecology lesson.

**Comment by fmichonneau** [comment]
The restructuring of the lesson is on its way. I'll focus on updating the title for now.
