### ISSUE TITLE
Removing missing values is inconsistent 

### ISSUE THREAD

**Issue by kathy0305** [datacarpentry/R-ecology-lesson#331]
Manipulating and analyzing data with dplyr; Exporting data
> Exporting data

```
surveys_complete <- surveys %>%
  filter(species_id != "",                  # remove missing species_id
         !is.na(weight),                       # remove missing weight
         !is.na(hindfoot_length),        # remove missing hindfoot_length
         sex != "")                               # remove missing sex
```

Why do we use  a mix of:  != and !is.na ? why not just !is.na ?
since we now use tidyverse , we read the data using `read_csv`
it converts all empty elements to NA
so we can simple use !is.na

**Comment by BinxiePeterson** [comment]
Does "!is.na" work for everything? I thought "!=" was used for character/factor data (i.e. species_id and sex), and "!is.na" is used for integers (weight and hindfoot_length). Any clarification will be appreciated!

**Comment by fmichonneau** [comment]
good catch, I think it was a left over of using `read.csv`
