### ISSUE TITLE
Error on CONTRIBUTING.md - branch from gh-pages?

### ISSUE THREAD

**Issue by khturner** [datacarpentry/R-ecology-lesson#332]
Hi all - maybe I'm missing something, but in CONTRIBUTING.Rmd it says to

> 3. Create a branch from `gh-pages` for your changes. 
> ...
> 4. Make your changes to the Rmd file.

But the .Rmd files only exist on branch `master`? Should we branch from `master` instead? Thanks!

**Comment by fmichonneau** [comment]
Yes, you are right. We recently changed the infrastructure of the lessons, but this hasn't been updated yet. If you can create a pull request to fix it, that would be great!

**Comment by khturner** [comment]
OK! PR made: https://github.com/datacarpentry/R-ecology-lesson/pull/333

Thanks!
