### ISSUE TITLE
read_csv check throughout the entire lesson set. 

### ISSUE THREAD

**Issue by aurielfournier** [datacarpentry/R-ecology-lesson#335]
Note to self to make sure we are consistently using `read_csv()` now that we are using it within the tidyverse part of the lessons.

**Comment by aurielfournier** [comment]
I was just starting to work on this, and I realized that in lesson 02 we discuss a few things that are specific to read.csv, e.g. stringsAsFactors

so if we change everything over to read_csv we need to remove that, but I'm nervous about doing that, and setting them up for confusion later on, if they do use read.csv and run into factor issues.

@fmichonneau  thoughts?

**Comment by MariekeDirk** [comment]
You can set colClasses within the function read.csv (see for example: https://www.r-bloggers.com/using-colclasses-to-load-data-more-quickly-in-r/).  Though, I would recommend using fread() from the data.table package (you can also set colClasses within this function), as it is much faster (http://zevross.com/blog/2013/11/25/data_table/).

**Comment by aurielfournier** [comment]
That is a good point @MariekeDirk , but in the past we have not been teaching all the arguments of read.csv, and IMO, that isn't the point of this lesson, the point is to teach them how to get data into R and then move onto the next thing, without setting them up for failure later on.

**Comment by MariekeDirk** [comment]
Thanks for your comment. It probably is too difficult. Another option is to change the 'wrong' classes after read.csv. I see you included an example in the lecture (changing a factor into numeric, e.g., as.numeric(levels(f))[f]), which looks like a good solution). Is this an option?

**Comment by aurielfournier** [comment]
@fmichonneau I should be able to help make that happen! Should we find a time to chat soon and figure out a timeline for making that happen?

**Comment by ha0ye** [comment]
I'm also concerned about setting up learners for crashing on read.csv if we teach read_csv in the lesson (because they look nearly-identical, even for experienced coders). Is there an upcoming bug-bbq?

**Comment by maurolepore** [comment]
I support the idea of focusing on `readr::read_csv()`. Moreover, I suggest teaching how to import data using the _Import Dataset_ menu of the _Environment_ tab in RStudio (or better https://rstudio.cloud/). If __readr__ is installed, the _Import Dataset_ menu will display the option _From text (readr)..._. It will also allow the user to browse the file-to-import, and will automatically generate the code for the user to paste on a script.

You can see all of this in action [here](https://fgeo.netlify.com/2018/03/13/2018-03-13-import-dataset/) (and [here is the source code](https://rstudio.cloud/project/23464)). Those curious will find at the end a [link to another article](https://fgeo.netlify.com/2018/03/15/2018-03-15-how-to-read-data-safely-with-only-base-r/) showing how to do a similar job but with `utils::read.csv()`(and the really _really_ curious may want to read [stringsAsFactors: An unauthorized biography](https://simplystatistics.org/2015/07/24/stringsasfactors-an-unauthorized-biography/) by Rogen Peng).

**Comment by chursaner** [comment]
Seems like we can close this issue and [this one](https://github.com/datacarpentry/R-ecology-lesson/issues/391), with the decision to use readr::read_csv. Thanks for the reasoning and resources, @maurolepore !

**Comment by aurielfournier** [comment]
Yes thank you @maurolepore!
