### ISSUE TITLE
Adhering to working directory structure

### ISSUE THREAD

**Issue by AliBerens** [datacarpentry/R-ecology-lesson#337]
There are a couple places in the lesson that don't seem to follow the working directory structure outlined in 00-before-we-start:

1.  00-before-we-start: `data-carpentry-script.R` - instead of the working directory, this file should be placed within the `scripts` directory
2. 04-visualization-ggplot2: examples with the `ggsave()` function should remind students to place their figures in the `fig_output` directory. Also, it would be beneficial to students to remind them about good naming practices for files (`name_of_file.png` doesn't really tell you anything about the file). I know that I have been guilty of poor naming too many times, which means that work that I saved is unusable even a short while later because I can remember the specifics of the output.

**Comment by aurielfournier** [comment]
Great ideas, would you be willing to make those changes and submit them as pull requests?
