### ISSUE TITLE
Data type memory (01-intro-to-r)

### ISSUE THREAD

**Issue by AliBerens** [datacarpentry/R-ecology-lesson#338]
For the Vectors and data types challenge, I think it would be useful to point out that there is no memory of the past data types. For example, how many `"TRUE"` values are in a new vector that combines `num_logical` and `char_logical` ( `comb_num_char_logical <- c(num_logical, char logical)` )? Reminder: 

```
num_logical <- c(1, 2, 3, TRUE)
char_logical <- c("a", "b", "c", TRUE)
```

As a new student, you might answer 2, since there is a `TRUE` logical value in each list. However, in the assignment of `num_logical` the data type becomes numeric, so the `TRUE` logical value is converted to the number `1`. Then, during the combination of these two vectors, the data type is converted to character, so this value is now character `"1"`.

**Comment by aurielfournier** [comment]
That is an excellent point @AliBerens. Would you be willing to write up a few lines explaining this and submit them as a pull request on the lesson?

**Comment by fmichonneau** [comment]
working on this now

**Comment by fmichonneau** [comment]
Thanks for this suggestion @AliBerens. Feel free to review how I used it to create this challenge and provide feedback. I think it's going to be useful to our learners!
