### ISSUE TITLE
no warning message for lubridate parse failure (starting-with-data)

### ISSUE THREAD

**Issue by elahi** [datacarpentry/R-ecology-lesson#344]
After the following command in the lubridate section:

``` {r}
surveys$date <- ymd(paste(surveys$year, surveys$month, surveys$day, sep = "-"))
```

The text states "Did you notice the warning message?".  Not sure if this is a problem on my machine, but I did not get a warning message (after re-installing lubridate, still no warning).  If others also notice this discrepancy, it may be worth a small change in the text.  

In addition, it may also help to build up the lubridate example a bit.  For example:

```

my_date <- ymd("2015-01-01")
str(my_date)

my_date <- ymd(paste("2015", "1", "1", sep = "-"))
str(my_date)

# What happens when we try to define an invalid date?
ymd("2017-02-30", quiet = T) # no warning, even though quiet is TRUE
?ymd

# Now let's create a date in our surveys dataset
surveys$date <- ymd(paste(surveys$year, surveys$month, surveys$day, sep = "-"))
str(surveys)

# Check for NAs 
summary(surveys$date) # yes, some dates failed to parse

# Create a character vector of our dates
surveys_dates <- paste(surveys$year, surveys$month, surveys$day, sep = "-")

surveys_dates[is.na(surveys$date)]
```

Let me know if this is worthy of a pull request.

**Comment by aurielfournier** [comment]
Hi @elahi you are right that the warning message is not longer there, ymd is just putting in the NAs without warning us now. 

I think the example you have presented is good, and would welcome a pull request

please use `TRUE` instead of `T` though, as our lessons encourage learners to write out the full words to avoid issues. 

Thanks!

**Comment by elahi** [comment]
Done, thanks for the quick response @aurielfournier .
