### ISSUE TITLE
Pull #345 is incorrect

### ISSUE THREAD

**Issue by plantarum** [datacarpentry/R-ecology-lesson#352]
I just posted a comment on pull #345, not sure if you'll get notified since it's already closed. So here's a new issue just in case.

**Comment by fmichonneau** [comment]
@plantarum, thanks for your report. The current version of lubridate is 1.7.1. I just confirmed that there is no warning produced with this version. I am going to open a bug report on lubridate as I don't see one already.

``` r
#> library(lubridate)
#> Attaching package: 'lubridate'
#> The following object is masked from 'package:base':
#> 
#>     date
packageVersion("lubridate")
#> [1] '1.7.1'
ymd("2018-02-30", quiet = TRUE)
#> [1] NA
ymd("2018-02-30", quiet = FALSE)
#> [1] NA
```
