### ISSUE TITLE
Displaying answers to challenge exercises

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/R-ecology-lesson#355]
The answers to the challenge exercises are not easily viewable.

The only way I can see to view them is to go to the github repo, then go to the Rmd file for the section, then  go to the raw view, then look for the commented out code.  This is not novice friendly.  Is there an easier way to see answers to challenge exercises? 

I'm raising this question after an email inquiry from someone trying to use these lessons for self-study.

**Comment by fmichonneau** [comment]
Yes, it's definitely an issue. I'm hoping to address this soon. I'm closing in favor of #201
