### ISSUE TITLE
Introduce tibbles earlier in Starting with Data

### ISSUE THREAD

**Issue by WeeBeasties** [datacarpentry/R-ecology-lesson#356]
---

I think that tibbles should be introduced right up front in the "Starting with Data" module. I would suggest immediately after data frames are first discussed in "Presentation of the Survey Data". It would be helpful to highlight the similarities and differences between tibbles and data frames right up front, and recognize the advantages of the former when working in the tidyverse.

This comment is in completion of my instructor training, so it may be somewhat overlapping with other issues previously reported. If desired, I could complete this issue and submit a pull request.

---

**Comment by gabrielodom** [comment]
I guess I'm a little late to this party, but my pull request (https://github.com/datacarpentry/R-ecology-lesson/pull/469) also closes this issue.

**Comment by mondorescue** [comment]
Pulled in #469 which covers this issue. I'll review #459 and incorporate as appropriate. Closing this issue.
