### ISSUE TITLE
GGplot suggestion - Lesson Contribution

### ISSUE THREAD

**Issue by sheraaron** [datacarpentry/R-ecology-lesson#357]
When introducing ggplot, I think it is good to begin with the general structure/template of how to use the function, such as:

ggplot(data = <DATA>) + 
  <GEOM_FUNCTION>(mapping = aes(<MAPPINGS>))

This way, throughout the remainder of the lesson, instructors can return to this template when introducing different types of functions (geom_point, geom_bar, etc) and students will have this template in mind if they encounter a geom_function we do not cover.

- Hatim Ali Rahman

---

---

**Comment by hrahman2** [comment]
When introducing ggplot, I think it is good to begin with the general structure/template of how to use the function, such as:
 
ggplot(data = <DATA>) + 
  <GEOM_FUNCTION>(mapping = aes(<MAPPINGS>))

This way, throughout the remainder of the lesson, instructors can return to this template when introducing different types of functions (geom_point, geom_bar, etc) and students will have this template in mind if they encounter a geom_function we do not cover. 

I added this to the beginning of the section, but please note other sections may also have to be updated if this request is approved.

**Comment by fmichonneau** [comment]
this has been implemented at some point.
