### ISSUE TITLE
Nancy Morales - Lesson Contribution

### ISSUE THREAD

**Issue by sheraaron** [datacarpentry/R-ecology-lesson#360]
https://secure.helpscout.net/file/90c8b1369adf9516/219709/1405167320/112506522/carpentries_lesson_NancyGM_UNAM/

**Comment by aurielfournier** [comment]
@sheraaron I don't have a help scout log in, is there another way you can share Nancy's contribution with us? Thanks

**Comment by fmichonneau** [comment]
This contribution was meant for a different repository; I'll forward it.
