### ISSUE TITLE
James Croft - Lesson Contribution

### ISSUE THREAD

**Issue by sheraaron** [datacarpentry/R-ecology-lesson#366]
I have proofed this lesson as part of my instructor training.
I'm still new to Git and am afraid I'll mess up. So, as per COMTRIBUTING.Rmd I am sending edits by email.

I have made some edits to R-ecology-lesson/00-before-we-start.Rmd to improve readability and have fixed some typos.

Some additional comments:
I changed the order of the last 2 bullets in "getting set up" because I think it makes sense to put the script tin the root folder before creating the sub-directory for data; and it's less likely that students will mistakenly put the script in the data folder.

There is too much white space around the "Example of a working directory structure" figure so the title is disjointed from the image.

Kind Regards,
James

James Croft, PhD
Lecturer, Motor Control and Skill Acquisition
School of Medical and Health Sciences
Edith Cowan University, JO 19.391
270 Joondalup Drive, Joondalup
Perth, WA, 6027
---

![](https://ci4.googleusercontent.com/proxy/-eyGU-eX-UqtMbnOBAoeoNOGi9yx6uLPK3Fsxnb-_4Rk2mDukuipAn3geFT4K9tHoVnC4No7553pHuxN58odPyUVlUlpfJFtxaUHkvznhV5-9NBBvg_PNffGQWrqfvK574fl7UqHOgYPqv3reTp4vwfbTm_yTRy66dGHLlwqNiAmn9uG3oXHjNCPmSOeYUFS8unohHnCz_vekddKOSB_JhQQTebj0gVodccL8P0xYg7LiuqzGU0-fKpNs3kzRXi_egrlpQ=s0-d-e1-ft#https://d33v4339jhl8k0.cloudfront.net/inline/63497/ca0d7a059cfc693e24b2148c702c680a20b0a9cf/91f7db348a6afcbcf386d54738be72685aeafd61/Screen-Shot-2018-02-22-at-9-39-12-am.png)

![](https://ci5.googleusercontent.com/proxy/92TSlti6N8UWkwRT7BsXoGcaj-hGccu8yTuPsK961cW3h2FSQ9RhDw22pfbfLWNLF0UFI0nNXaf8Qgh1Y2TdpAyU1tfEzJQoxOnyvM1H6luVye1kWZdOyGPsF9yYY70uyVrjB1GeS_gbwJ67B4-1C1x5NIHGpwrvBInc_lkAlFL_27VREoXPujcsRwI8D0aJ7Orgx25V02YplrMN9f0UwSTIXmmf-5JxLizeJlDhImEOyd1otRcEFBfpLw613WI8N3sSkw=s0-d-e1-ft#https://d33v4339jhl8k0.cloudfront.net/inline/63497/6f2d2285b34589a3c25776260bda0cf33c2585b1/384411a09ce5f6b10e9b685cebeecc81f8c4a041/Screen-Shot-2018-02-22-at-9-39-23-am.png)

**Comment by fmichonneau** [comment]
@sheraaron did this person send you a file? Is there a way to know the typos and edits they found? Thanks!

**Comment by sheraaron** [comment]
@fmichonneau no he did not. I can ask him to provide something.

**Comment by fmichonneau** [comment]
that would be great, just so that we can figure out the typos he found. Thanks!!

**Comment by sheraaron** [comment]
Hey @fmichonneau  here is the info that James provided. 
 
https://secure.helpscout.net/file/90c8b1369adf9516/219709/1453908479/116623578/text/
https://secure.helpscout.net/file/90c8b1369adf9516/219709/1453908479/116623577/text/
