### ISSUE TITLE
Change order in "Getting set up" in Before we start

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#368]
As mentioned in #366, it might be better to download the script before creating the "data" folder.

**Comment by Amrithasuresh** [comment]
@fmichonneau Simply changing the order will do? Like below. 

- Download the code handout, place it in your working directory and rename it (e.g., data-carpentry-script.R).
- Under the Files tab on the right of the screen, click on New Folder and create a folder named data within your newly created working directory (e.g., ~/data-carpentry/data)

**Comment by fmichonneau** [comment]
yes exactly. Please let us know if you need help creating your pull request. Thanks!
