### ISSUE TITLE
Pilotting the new GitHub labels

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#375]
@aurielfournier @mondorescue @anacost 

I added to the repository the proposed set of GitHub labels that we're planning to use across all repositories for the Carpentries. We are in a piloting phase and we want to start using them to see if adjustments are needed before we deploy them everywhere. We are going to test them first in a few repositories including this one until the end of the month.

It would be great if each of you went through a few issues that are currently in the repository and assign at least 2 labels for each: one in the "status" category, and on the "type" category. Depending on the context, you may also want to add the "bug-bbq", the "good first issue" or the "high-priority" labels.

I went through some of the issues as I replaced the old set labels with the new ones. 

I'd really like your feedback on how well these labels capture the type of issues that are currently in the repository, or that we have or can receive. If you feel that some labels don't capture the nature of the issue, or if the meaning of the labels is too unclear to make a call, I'd really like to hear about it.

The definition of the labels is available in this proposal: https://docs.google.com/document/d/1b3nIZ6N4IHY24JmLNQ5rkwUACEVS9Hls3auzZD7zHqk/edit

Feel free to ping me on Slack, by email or here if you have any questions or with your comments/feedback.

Thanks!

**Comment by aurielfournier** [comment]
I'll look it over this weekend.

**Comment by fmichonneau** [comment]
@aurielfournier thanks for assigning the prototype labels to the issues. I was wondering if you had any specific feedback on them, and whether there is anything we should change to make them better.

@anacost @mondorescue if you have a chance to look over the issues, and how they are labelled, I'd love your feedback as well.

Thanks!

**Comment by aurielfournier** [comment]
I thought overall they were very good. I'm still not sure what needs to be reviewed by the CAC, so that label was a bit of a mystery to me. and the 'out of scope' label made me nervous since I didn't want it to be read the wrong way by the originator of the issue/pull request. But overall I thought they were great

**Comment by fmichonneau** [comment]
I agree with your feeling regarding "out-of-scope". Do you think we should try re-word it to something else?

**Comment by aurielfournier** [comment]
most examples I can think of that would be 'out of scope' would also fit  under 'long term idea' or something along those lines. 

So a way of indicating that its not something we're going to work on/prioritize right now, but maybe we will circle back later?

**Comment by fmichonneau** [comment]
good point! I'll keep this in mind.

**Comment by fmichonneau** [comment]
closing this for now. The "beta" version of the labels are in use in the repository. If you have feedback on the labels, please leave a comment here: https://github.com/carpentries/lesson-infrastructure/issues/1
