### ISSUE TITLE
Teach tidyverse first: Get students doing powerful things quickly

### ISSUE THREAD

**Issue by maurolepore** [datacarpentry/R-ecology-lesson#378]
Broadly speaking, there are two competing approaches to teaching R to beginners: Base R first; and Tidyverse first. Today, world-class teachers recommend the tidyverse first approach (e.g. this blog by [David Robinson](http://varianceexplained.org/r/teach-tidyverse/)). Two prominent examples of this in action are the book [R for Data Science](http://r4ds.had.co.nz/) by Garrett Grolemund and Hadley Wickham; and the [course Data Challenge Lab](https://github.com/dcl-2017-04/curriculum) by Hadley Wickham and Bill Behrman. I suggest to restructure this lesson to follow the tidyverse first approach. 

For a model of what contents to demonstrate consider following the examples in the the paper [Declutter your R workflow with tidy tools, by Zev Ross, Hadley Wickham and David Robinson](https://doi.org/10.7287/peerj.preprints.3180v1).

(cc' @MikeTrizna)

**Comment by aurielfournier** [comment]
Hi @maurolepore thanks for filing an issue. 

We are currently working on rewriting our lessons to focus more on the tidyverse, and we appreciate you bringing these resources to the front of our minds again. 

If you have specific ideas about how we could implement this, please feel free to discuss them here, or submit a pull request.

**Comment by maurolepore** [comment]
Thanks @aurielfournier for considering my suggestion.

My idea about how to implement the _tidyverse first_ approach in a 1-2 day course for researchers would be to use the course _Data science in tidyverse_  by Charlotte Wickham (@cwickham: Would this be OK?):
* [Link for students to the project on rstudio.cloud](https://rstudio.cloud/project/10871) (see #380).
* [Repo of the course](https://github.com/cwickham/data-science-in-tidyverse).
* [Repo of the course solutions](https://github.com/cwickham/data-science-in-tidyverse-solutions).

I believe Charlotte taught this course as a 2-day workshop at the RStudio conference 2018. Her course is very well thought and tested -- it follows the book [R for Data Science](http://r4ds.had.co.nz/) by Garrett Grolemund and Hadley Wickham, and evolves from the course [Master the tidyverse](https://www.rstudio.com/workshops/master-the-tidyverse/) by Garrett Grolemund ([repo](https://github.com/rstudio/master-the-tidyverse)).

I think that, because of the time constrains of this Data Carpentry lesson, you may need to focus exclusively on day 1 of Charlotte's course. Although it would be nice to adapt the course to use a data set that more strongly relates to the field of your learners, the effort of doing so may not pay off. I suggest that the effort would be better invested in keeping up with fast rate at which the tidyverse is moving.

**Comment by aurielfournier** [comment]
great thank you, as we work on this next release of lessons we will keep all of this in mind

**Comment by stenhaug** [comment]
Just to add one more perspective here -- I completely agree that teaching the tidyverse first is the way to go. Looking over some of the materials discussed above, it seems that some of them are aimed at beginners but include work on fairly large datasets. I find that beginners learn much more quickly when they start on the simplest possible dataset where they can visually see exactly what is happening in the output.

**Comment by katrintirok** [comment]
Hi, I think the R lesson in data carpentry is already to large parts teaching the tidyverse with dplyr, tidyr, ggplot2 ... However, there might be a better way to structure the lesson, e.g. getting to do visualisations much earlier, maybe shorten some of the basic R stuff ... 
We also should keep in mind that the R lesson is taught together with data organisation, OpenRefine and SQL, which all should use the same data set and build upon each other.

**Comment by keatonwilson** [comment]
I'd also like to advocate for teaching tidyverse earlier - particularly the use of tibbles as ways to visualize tabular data, directly - it circumvents the "wow look at all of that output" problem in the very beginning of the Starting with Data lesson. I agree that small datasets can be useful and manageable, but the reality is that MOST real-world data that learners will eventually be faced with (frequently with their own research or work) is big and messy. I think giving students realistic data and current tools (like tibbles and the tidyverse) go a long way to promote excitement about the material and its usability.

**Comment by chursaner** [comment]
Glad to hear we're moving towards the Tidyverse approach. In particular, I would recommend replacing str from base R with [dplyr::glimpse](https://www.rdocumentation.org/packages/dplyr/versions/0.3/topics/glimpse). It's a bit nicer than str because it defaults to the width of the console and shows a preview of the data in addition to the data type.

I see str() used in [this lesson](http://www.datacarpentry.org/R-ecology-lesson/02-starting-with-data.html).

**Comment by keatonwilson** [comment]
@chursaner I'm totally in agreement with this! glimpse() > str()

**Comment by aurielfournier** [comment]
I think that is a worthwhile change. Would one of you be willing to submit a pull request with those changes?

**Comment by Dereseteshome** [comment]
I agree that small data sets can be useful and manageable, but in real-world  learners will eventually be faced with their own way. I think giving students realistic data and current tools by using  tidyverse.

**Comment by anacost** [comment]
I will close this issue, since the lesson is already being changed in this direction. Feel free to reopen a related issue or propose a pull request.
