### ISSUE TITLE
Avoid installation problems: Use rstudio.cloud (RStudio from a web browser)

### ISSUE THREAD

**Issue by maurolepore** [datacarpentry/R-ecology-lesson#380]
Students often struggle to install software, particularly R, RStudio and R packages. Some students fall behind the class even before getting to the class content. If at all, they recover with a feeling of frustration that impairs their learning. All of this can be avoided using rstudio.cloud, a free service that takes seconds to join and gives students access to RStudio from a web browser. Moreover, rstudio.cloud allows the teacher to share an entire RStudio project with the students -- eliminating the need for students to download the course content.

For example, rstudio.cloud was recently used in RStudio conference 2018 to teach an introduction to R and RStudio:
* [Intro to R & RStudio (day 1)](https://rstudio.cloud/project/13021)
* [Intro to R & RStudio (day 2)](https://rstudio.cloud/project/13632)

That course is not only an example for using rstudio.cloud as a convenient platform for teaching but it is also an example of what materials and course structure result in effective learning. I suggest you consider borrowing some content to update the Data Carpentry course.

(cc' @MikeTrizna)

**Comment by aurielfournier** [comment]
Thanks for the input @maurolepore, installation issues are often a source of frustration and I appreciate you letting us know about these resources. We'll taken this into consideration for our next lesson revamp.

**Comment by maurolepore** [comment]
Just to show what [rstudio.cloud](https://rstudio.cloud/) is almost identical to RStudio used locally.

![](https://i.imgur.com/lCImLTB.png)

![](https://i.imgur.com/xpa7KoI.png)

**Comment by fmichonneau** [comment]
Thanks for this suggestion. It's an interesting approach, but using cloud infrastructure is not currently part of our teaching approach. We have more info about this here: https://carpentries.github.io/instructor-training/22-practices/#learners-use-their-own-machines

It's something that we may reconsider in the future, and we'll definitely talk about this with the curriculum advisory committee once it's formed.
