### ISSUE TITLE
Distribute datasets as an R package

### ISSUE THREAD

**Issue by maurolepore** [datacarpentry/R-ecology-lesson#385]
Datasets for teaching are increasingly being distributed as R packages. This has great advantages:

1. R packages are easy to share with `install.packages()` (if hosted on CRAN) and with `install_github()` (if hosted on GitHub).
2. Each dataset can then be documented as an R help file.
3. R package help manage change in the data because each time the data changes meaningfully you can release a new version of the package (a [GitHub release](https://help.github.com/articles/creating-releases/) or a formal CRAN release).
4. It is straightforward to create a website for the package (with [__pkgdown__](http://pkgdown.r-lib.org/)).

For example, consider these data-packages:

* [babynames](https://cran.r-project.org/web/packages/babynames/index.html) by Hadley Wickham.
* [repurrrsive](https://cran.r-project.org/web/packages/repurrrsive/index.html) by Jenny Bryan and Charlotte Wickham.
* [gapminder](https://cran.r-project.org/web/packages/gapminder/index.html) by Jenny Bryan.

Building a data package is simple and quick. I could demonstrate this by building an R package and its website, with whatever datasets you choose.

**Comment by fmichonneau** [comment]
We are already working on packaging the data for this lesson as an R package. It's a work in progress here: https://github.com/weecology/ratdat
