### ISSUE TITLE
Formatting problem in the last challenge of the output file of "starting with data"

### ISSUE THREAD

**Issue by prosoitos** [datacarpentry/R-ecology-lesson#387]
In the output of the "starting with data" lesson, the answer to the last challenge appears at the bottom of the question. Note that this does not show on the GitHub page, but only on the output web page.

I don't know `rmarkdown` enough to address this (I use `emacs org-mode`).

**Comment by prosoitos** [comment]
Why was the issue closed? Maybe I wasn't clear in my explanations (or maybe it is already fixed but not pushed yet)?

If you go to http://www.datacarpentry.org/R-ecology-lesson/02-starting-with-data.html and look at the bottom of the last challenge, you will see what I was trying to explain (but the problem does not show on the GitHub page).

**Comment by prosoitos** [comment]
(I could have phrased things better I guess since all the challenges have their answers below them. I should have written that the answer to that particular challenge, beside its normal appearance, also appears at the bottom of the question due to problems in the coding of the formatting of a text answer in the `rmarkdown` file).

**Comment by prosoitos** [comment]
Oh, sorry. I just realized that you had actually addressed the issue :stuck_out_tongue: Sorry for the extra comments then. The lack of message confused me.

Thanks for addressing this so quickly!!! :slightly_smiling_face:

**Comment by fmichonneau** [comment]
No worries! I just wanted to make sure the lesson was rebuilt, and that my fix addressed the issue before commenting. I checked and it looks good to me. Let me know if it's not the case, and don't hesitate to re-open if needed. Thanks for spotting this!

**Comment by prosoitos** [comment]
Looking good here too :slightly_smiling_face:
