### ISSUE TITLE
Date vs. POSIXct in 'Starting with data' lesson

### ISSUE THREAD

**Issue by PeteHaitch** [datacarpentry/R-ecology-lesson#393]
This is the same issue reported in https://github.com/datacarpentry/R-ecology-lesson/pull/279, but it seems like not all instances were caught?

According to the man page, `lubdridate::ymd()` returns:

> a vector of class POSIXct if tz argument is non-NULL or Date if tz is NULL (default)

 at least as of `v1.7.3` (older versions may have had different behaviour). 

The examples in https://github.com/datacarpentry/R-ecology-lesson/blob/master/02-starting-with-data.Rmd#formatting-dates use `lubridate::ymd()` with the default `tz = NULL` and so return a _Date_, but the lesson text instead talks about _POSIXct_. 

 Would you prefer a PR with all references to _POSIXct_ switched to _Date_ or a new example created that actually returns a _POSIXct_?

**Comment by fmichonneau** [comment]
thanks for catching this! I was working on the text in this lesson and update it.
