### ISSUE TITLE
Add that all lesson content should be in repository to CONTRIBUTING

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#396]
We aim to have our lesson be as self-contained as possible and therefore images, and other external resources should be included in the repository whenever possible. A sentence about this should be added to our CONTRIBUTING guidelines.

**Comment by arokem** [comment]
Should this issue be closed? https://github.com/datacarpentry/R-ecology-lesson/issues/396#issuecomment-381251170 suggests so
