### ISSUE TITLE
Broken File URL for Chapter 02 : Starting With Data

### ISSUE THREAD

**Issue by dwbapst** [datacarpentry/R-ecology-lesson#405]
Howdy,

I seem to have found a broken URL for obtaining the data frame for Starting with Data, specifically the URL given on lines 57-58:

https://github.com/datacarpentry/R-ecology-lesson/blame/master/02-starting-with-data.Rmd#L57-L58

When I try this on my Windows machine, it says it cannot find any such file, and I get the following error:

```
download.file("https://ndownloader.figshare.com/files/2292169",
               "data/portal_data_joined.csv")
```
> Error in download.file("https://ndownloader.figshare.com/files/2292169",  : 
>cannot open destfile 'data/portal_data_joined.csv', reason 'No such file or directory'

Perhaps I caught this in midst of transferring the file location from some location other than figshare?

**Comment by dwbapst** [comment]
For what its worth, as a stop gap so I could use this lesson for my live code exercise during instructor training, I loaded the data file directly from a github repo that appears to possess this file:

surveys<-read.csv("https://raw.githubusercontent.com/kbroman/kbroman.github.io/master/datacarp/portal_data_joined.csv")

I'd make a pull request but I don't know what the permanent home for this datafile is supposed to be.

**Comment by wrathofquan** [comment]
@dwbapst Hi! Was just in the same training with you. I had a similar problem but determined that the figshare link is good but because the path is specified with './data', if you don't have a directory titled 'data' it will throw that error.

**Comment by fmichonneau** [comment]
Hi @dwbapst, as @wrathofquan mentions it seems likely that the problem comes from not having the `data` folder in your working directory. This part of the lesson is intended to be run interactively after this folder has been created. The link seems to work at this time. Feel free to re-open if you think there is something else at play here. Thanks!

**Comment by fmichonneau** [comment]
> Note that the carpentry instructor lesson directs right to the Starting with Data chapter, so it isn't clear to those coming from that that they should look to previous chapters

good point. I'll think of we can do to make this clearer.
