### ISSUE TITLE
Shorter URL for download.file()

### ISSUE THREAD

**Issue by kubu4** [datacarpentry/R-ecology-lesson#410]
The URL is too long for accurate typing by all learners (and instructors) in a classroom.

Use of a shortened URL would reduce learner error/frustration.

**Comment by fmichonneau** [comment]
hi @kubu4!  Learners shouldn't need to type the URL manually.

The URL is included in the code-handout (http:///datacarpentry.org/R-ecology-lesson/code-handout.R) that learners use to follow along during the workshop. If the instructors don't want to use the code handout for some reason, then the URL can be copied and pasted from the Etherpad (or even the lesson).

Closing, but if you have any comments or concerns about this, feel free to re-open to discuss further.

**Comment by kubu4** [comment]
Thanks for responding.

This is the first I've heard of the code handout. Interesting.

Also, good point about the Etherpad! In the various Software Capentry/Data Carpentry classes I've taught/helped at, the Etherpad usually gets forgotten/abandoned rather quickly. I'll make an effort to start promoting its usage at the classes I teach/help!
