### ISSUE TITLE
Confusing wording in challenge question

### ISSUE THREAD

**Issue by tobyhodges** [datacarpentry/R-ecology-lesson#414]
@tavareshugo and I are running a workshop at the moment, and the wording of one of the challenges in the "Starting with Data" chapter has been confusing some of our learners.

The challenge in question is the first in the section "Indexing and subsetting data frames" ([here](https://github.com/datacarpentry/R-ecology-lesson/blob/master/02-starting-with-data.Rmd#challenge-1)). The wording of part 1 is unclear to our learners. 

> Create a data.frame (surveys_200) containing only the observations from row 200 of the surveys dataset.

Is the aim to take the 200th row of the dataframe? Or to take all rows from the 200th onwards?

My guess is that the intention was to pull out just the single row. Is that correct? Let me know, and, if you agree, I will be happy to submit a PR with a proposed new wording.

Thanks for all your work on these materials!

**Comment by fmichonneau** [comment]
Yes, just the 200th row. Thanks!
