### ISSUE TITLE
Add a note on benefits of readr::read_csv over base::read.csv

### ISSUE THREAD

**Issue by joongsup** [datacarpentry/R-ecology-lesson#420]
Hi I was going to chime in one of the open issues (#391) and say introducing read_csv (from readr package) along with read.csv has many benefits, and I see many in that thread have already mentioned both read.csv and read_csv. However, there's no mention of why using read_csv might be preferable to read.csv, and since it seems a separate topic, I'm adding a new issue. In the R Ecology lesson, read_csv is not introduced until manipulating data frames, but I think it'll be much beneficial if it's introduced a lesson earlier (so in starting with data) with a short blurb/note on comparison between read_csv and read.csv, which can be any of the following

1. library(readr): we have to load the package (readr) first before using read_csv function.
2. Column names can be modified as a result of read.csv, if there's a space in column names. Using read_csv, the column names are conserved. 
3. read.csv reads character column as factor whereas read_csv reads character column as character. 
4. read_csv provides a progress bar by default.

**Comment by aurielfournier** [comment]
Hello @joongsup thanks for opening up this issue. `read.csv` and `read_csv` are certainly both important topics for our learners. Right now we focus on one first and then the other later, with the goal of not confusing learners, who are often still getting comfortable with working in a programming language, and for whom the difference between `read.csv` and `read_csv` just from a character standpoint of one having a . and one having a _ could be confusing. 

A discussion of the differences/benefits of both is important, and we encourage instructors to do that later on in the lesson when `read_csv` is introduced.

**Comment by brankokovac** [comment]
Hi @aurielfournier my opinion is that we should stick with either `read.csv` or `read_csv` and not use both. 

No matter how late `read_csv` is introduced, it could still be early for people who are only starting to learn R and have only used for a couple of hours or days. The question they may ask is - why did you tell us about `read.csv` if we need to use `read_csv` as well? From my experience, this can lead to a confusion, but also can be frustrating.

We believe that `tidyverse` is the way to go, so we don't use `base` functions to teach them how to manipulate data. Going with `readr::read_csv` would make everything consistent.

**Comment by aurielfournier** [comment]
From talking with some of the other maintainers it sounds like we are going to move the lesson towards just using `readr::read_csv` 

If either of you have any interest in working on that and submitting it as a Pull Request, that would be great, and would likely speed up the process.

**Comment by mondorescue** [comment]
How should we handle the fact that `read_csv` outputs a `tibble`? I guess to be precise, we'd have to change the "Inspecting `data.frame` Objects" section header to "Inspecting `tibble` Objects" and so on; or stick with describing what a `data.frame` is but briefly mention that `tibble` is a special kind of `data.frame`.

**Comment by brankokovac** [comment]
Sticking with `data.frame` makes sense. Every `tibble` object is a `data.frame` after all.

**Comment by anacost** [comment]
I do not agree with the importance of point "3. read.csv reads character column as factor whereas read_csv reads character column as character." It is the default for read.csv to read character column as factor. It can be changed with as.is=TRUE:
tbl <- read.csv("table-data.csv", as.is=TRUE) 
This feature as default in read.csv is great with you will want to have a categorical variable for statistics.

**Comment by aurielfournier** [comment]
Hi @anacost thanks for the input.

You are correct that if you have categorical data that you wanted treated as a factor, it is a great default. But this is often one of the defaults in R that causes many issues for new users, and often times even experienced ones who forget. That is why `read_csv` defaults to character instead, which is, based on my experience more intuitive for many new users. And can prevent strange/unexpected results when graphing/doing data management/modeling later on.

**Comment by anacost** [comment]
Hi @aurielfournier,
I understand the point for beginners who want to work with characters and want to learn a first programming language. It is very simple to work with characters. It is easier to teach characters than explain the use of factors (categorical variable). Categorical variables will be used for classification.
The importance of R programming language is related to statistical learning. Then, the main feature is a categorical variable, this is to be explained for learners who want to deal with "big data". Unless you will count letters, words.
If the decision is taken, I do not worry about as an instructor for the lesson. I take my time to explain about categorical variables, independent about the content of the lesson. This question comes during the workshop. And we are not teaching statistics in this point of the lesson.

**Comment by aurielfournier** [comment]
@anacost I agree our objective is not to teach statistics, and also our lessons are aimed very much at beginners, so teaching them how to import data in such a way that strings of characters are treated as characters makes a lot of sense, which is why we are moving towards `read_csv`.

**Comment by joongsup** [comment]
I'd be more than happy to help. So what do you think @aurielfournier, replace base::read.csv with readr::read_csv in the starting with data lesson and add a note mentioning differences between the two?

**Comment by gabrielodom** [comment]
I'm new to the Carpentries, and I'd love to help with this (replacing `read.csv()` calls with `read_csv()` calls). Which lessons have already been fixed, and which still need work? I don't see any commits referencing this issue, so I'm not sure what work has been done.

**Comment by joongsup** [comment]
I haven't had time to work on this, so please go ahead.

**Comment by gabrielodom** [comment]
I'm working re-organizing lesson 2 to make the change from `read.csv()` to `read_csv()`. Where do you think the conversation on factors should go? It doesn't make as much sense right after data import because the students will not see their characters coerced to factors/

**Comment by fmichonneau** [comment]
I think it's best to remove the section about factors at this stage. I'd like to introduce them in the ggplot2 lesson motivated by the reordering of the legend/axis labels for categorical variables.

**Comment by joongsup** [comment]
See @gabrielodom's change in #469
