### ISSUE TITLE
Adding summary function for descriptive statistics would be very helpful for beginners

### ISSUE THREAD

**Issue by msnoon** [datacarpentry/R-ecology-lesson#426]
Please delete the text below before submitting your contribution. 

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

**Comment by staceyhancock** [comment]
The summary function is introduced in 02-starting-with-data.Rmd. Where specifically are you suggesting that the summary function is added?

**Comment by msnoon** [comment]
Hi Stacey, 
You're right its already there and I somehow overlooked it. Well, we can certainly add class() function to 02-starting-with-data.Rmd and show the learner what is the class type of the data object is and how can we look at the class/type of each column which is helpful to do any operations on columns later on.
Would this suggestion be acceptable? I haven't raised an issue on it yet, I will wait for your answer.
Regards,Muhammad Noon
    On Friday, May 18, 2018, 1:33:44 PM MST, Stacey Hancock <notifications@github.com> wrote:  
 
 
The summary function is introduced in 02-starting-with-data.Rmd. Where specifically are you suggesting that the summary function is added?
