### ISSUE TITLE
About the survey data

### ISSUE THREAD

**Issue by SeanKu0102** [datacarpentry/R-ecology-lesson#430]
I have two questions about the survey data:
1. These data are based on what biological question? Do you have any hypothesis?
2. In the plot type what's the meanings of kart exclosure, rodent exclosure, and spectab exclosure?

Thanks for providing these data!

**Comment by fmichonneau** [comment]
Hi @SeanKu0102 

There is a brief overview of the data on the workshop overview site: http://www.datacarpentry.org/ecology-workshop/data/ 

If you want more details, you can look at the original publication metadata: http://esapubs.org/archive/ecol/E090/118/metadata.htm

I'm going to close this, but if you have more questions, don't hesitate to re-open/comment here!

**Comment by SeanKu0102** [comment]
Thanks!
