### ISSUE TITLE
"dplyr functions" list mangled

### ISSUE THREAD

**Issue by katrinleinweber** [datacarpentry/R-ecology-lesson#436]
In https://github.com/datacarpentry/r-socialsci/blob/06e16e0cc0bb27f98c7b0e12c5018530591c0dad/_episodes/03-dplyr-tidyr.md#what-are-dplyr-and-tidyr I think the fact that a backtick follows directly after the `-` prevents the static site generator from rendering the list correctly:

[![grafik](https://user-images.githubusercontent.com/9948149/41468053-ef1b8a12-70a8-11e8-9bc9-3db0f4fa243c.png)](http://www.datacarpentry.org/R-ecology-lesson/03-dplyr.html#what_are_dplyr_and_tidyr)

I tried different browsers, with & without JavaScript. Over on http://www.datacarpentry.org/r-socialsci/03-dplyr-tidyr/#what-are-dplyr-and-tidyr the same list looks normal.

**Comment by fmichonneau** [comment]
Thanks for spotting this @katrinleinweber!

**Comment by katrinleinweber** [comment]
Since it was actually a missing empty line, I wouldn't consider it well spotted by me ;-D
