### ISSUE TITLE
Defining color in mapping vs geom

### ISSUE THREAD

**Issue by arredondo23** [datacarpentry/R-ecology-lesson#437]
First of all, I would like to congratulate you for the fantastic work behind this R-ecology-lesson. As a future instructor I learnt a lot of new things (e.g. I was not a big fan of tidyverse before but now I could see all its potential) by preparing and going through all the material. I have a suggestion about the Chapter: 'Data visualization with ggplot2'. 

I have noticed that in some parts of the lesson colors of the plot sometimes are defined in the geom layer like:

`ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length)) +
    geom_point(alpha = 0.1, aes(color = species_id))`

whereas in other parts colors are defined in the mapping like:

`ggplot(data = yearly_counts, mapping = aes(x = year, y = n, color = species_id)) +
    geom_line()`

Maybe the first time that 'color' is used in the lesson both cases/scenarios could be explained. 

Once again, great work!

Sergio.

**Comment by fmichonneau** [comment]
Hello @arredondo23 

  Would you be up to writing a pull request to include this explanation? It is something I explain when I teach this lesson, but it would be a good addition to have in the text.

Thanks!

**Comment by arredondo23** [comment]
Sure! I will add an explanation and do a pull request. 

Sergio.
