### ISSUE TITLE
Define and describe opjects in R before we create the weight_kg object

### ISSUE THREAD

**Issue by EliMoore25** [datacarpentry/R-ecology-lesson#438]
New Instructor making contribution:

At the beginning of this lesson we create the weight_kg object before objects are defined.  I think it would be helpful to define and describe objects just below the 12/7 operation.  It is confusing to me to start creating an object and working with it before objects are defined.  Then the "<-" object creation command will have more initial meaning.

**Comment by anacost** [comment]
Hi @EliMoore25,
thank you for your contribution!
What kind of definition do you miss about weight_kg?

**Comment by anacost** [comment]
I will close this issue, since I have not gotten any answer. Please feel free to explain it later in another issue.
