### ISSUE TITLE
Confusion in exporting data in dplyr part

### ISSUE THREAD

**Issue by semacu** [datacarpentry/R-ecology-lesson#443]
This is just to report that the two sentences:

*Let’s start by removing observations for which the `species_id` is missing. In this data set, the missing species are represented by an empty string and not an `NA`.* [...]

located in [Exporting data](https://github.com/datacarpentry/R-ecology-lesson/blob/master/03-dplyr.Rmd#exporting-data) within the dplyr part look a bit confusing to me. The code chunk that follows does not include any filtering on the `species_id` column, only `weight`, `hindfoot_length` and `sex`:

```r
surveys_complete <- surveys %>%
  filter(!is.na(weight),           # remove missing weight
         !is.na(hindfoot_length),  # remove missing hindfoot_length
         !is.na(sex))                # remove missing sex
```

Perhaps removing these first two sentences of the paragraph would help the trainee?

**Comment by mondorescue** [comment]
@semacu Thanks for catching this. I agree with you that it is confusing since the code doesn't match the text about removing observations with missing `species_id`. Would you be willing to put a pull request with your suggested correction?

**Comment by semacu** [comment]
Many thanks @mondorescue!
Yes - please find changes [here](https://github.com/datacarpentry/R-ecology-lesson/pull/445/commits/75b17e0146e9a150b268705632d0c1d98371f668)
