### ISSUE TITLE
small typo but might cause confusion to newbies

### ISSUE THREAD

**Issue by amadlung** [datacarpentry/R-ecology-lesson#449]
Please delete the text below before submitting your contribution. 

---
In lesson 1, the following is stated:
RStudio interface screenshot. Clockwise from top left: Source, Environment/History, Console, Files/Plots/Packages/Help/Viewer.
 If you go clockwise, then Files/Plot/etc comes before Console.

---

**Comment by Temityoalawiye** [comment]
Typo can really cause confusion when live coding. Care must be taken to cross check all spellings before running. As little as ''dot or comma'' mistake can cause problem for someone new to coding.
