### ISSUE TITLE
replace gridExtra with patchwork

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#450]
Once [`patchwork`](https://github.com/thomasp85/patchwork) gets released on CRAN, use it to combine multiple ggplot plots instead of relying on `gridExtra`.

**Comment by camillanovaglio** [comment]
Hi, 

I'd like to work on this as my first issue to checkout. Is this about replacing gridExtra with patchwork in 04-visualisation-ggplot2.Rmd line 591 and following example? 

Thanks

**Comment by fmichonneau** [comment]
@camillanovaglio, @johnsonra recently contributed the fix for this. If you have other ideas on how to build upon this contribution or improving the ggplot2 lesson in general, we'd love to review your contribution! Thank you!

**Comment by camillanovaglio** [comment]
Great, thanks! I have just sent a contribution to another topic.
