### ISSUE TITLE
"as.factor" vs "factor" / “mutate" vs "summarize" / a typo in the illustration for "inner_join"

### ISSUE THREAD

**Issue by andrew66882011** [datacarpentry/R-ecology-lesson#454]
1. In "Starting with data" subsection "Factors", it's worth mentioning the difference between "as.factor" and "factor". 

"as.factor" will leave factor levels and ordered-ness alone while factor() will not:

f <- factor("red", levels=c("red","blue", "yellow")

factor(f)
#[1] red
#Levels: red

as.factor(f)
#[1] red
#Levels: red blue yellow

2. In "Manipulating, analyzing and explorting data with tidyverse", it's worth mentioning the difference between "mutate" and "summarize"

"The key difference between mutate() and summarize() is that the former always returns a data frame with the same number of rows, while the latter reduces the number of rows."  from https://cyberhelp.sesync.org/data-manipulation-in-R-lesson/2016/07/26/

3. In "SQL databases and R" there is a typo in the illustration for "inner_join": in the down-left diagram, "Weight" should be "2.9" and "1.2"

Jianjun

**Comment by tavareshugo** [comment]
Just adding some check boxes as this is really 3 issues:

- [ ] Enhancement: explain difference between `as.factor()` and `factor()`
- [ ] Enhancement: explain difference between `mutate()` and `summarise()`
- [ ] Fix: typo in schematic of `inner_join()` (submitted pull request #473 for this one)

**Comment by tobyhodges** [comment]
Thanks everyone for contributing to this discussion. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As this issue relates to content in a version of the lesson before that update took place, I will close it. Please open a new issue if you believe that some or all of the changes being discussed here are remain relevant to the redesigned lesson, linking to this thread where relevant.
