### ISSUE TITLE
Diagram of long/wide format data frames in reshaping data section

### ISSUE THREAD

**Issue by janejpark** [datacarpentry/R-ecology-lesson#455]
In Data Manipulation > Reshaping with gather and spread, the diagram of the wide and long format data frames would be even more useful for complete novices if the two formats were labelled as such. Even though visually, one is clearly wide or long, it would be that much more clear for newcomers with labels.

**Comment by chriseshleman** [comment]
Hi. I took a stab at fixing this. I branched the lesson and then basically pulled the relevant section from the lesson (it's section 3, dplyr) and did a little out-of-software image work, then pushed — should do the trick.
