### ISSUE TITLE
Lesson Contribution by Samual Langton

### ISSUE THREAD

**Issue by sheraaron** [datacarpentry/R-ecology-lesson#456]
Under the Manipulating data frames lesson there is a section entitled Selecting columns and filtering rows. Currently this section aims to teach students how to subset data frames by using the 'select' and 'filter' functions. However, the lesson does not cover the use of the 'slice' function, which is also part of the dplyr package used during the lesson. Earlier on in the course, students will have learnt how to subset by rows using square brackets, in base R. Introducing the 'slice' function would therefore not be too challenging for students, but it keeps the material consistent with the tidyverse. I would therefore recommend the following example to be added under the Selecting columns and filtering rows. I have used backward quotation marks (``) as per rmarkdown code, so if you like my idea, you can just copy and paste this into the rmakdown script:

To choose observations by specific row numbers using `dplyr` you can use the `slice` function. This achieves the same thing as the square brackets we used earlier for indexing, but `slice` is integrated into the tidyverse. For instance, this would select the first ten rows of the surveys data frame:

`slice(surveys, 1:10)`

I know this is a relatively minor contribution, but it's an important one if the lessons are going to follow the tidyverse (and I think it's fantastic that, in general, the lessons do follow the tidyverse).

**Comment by mondorescue** [comment]
Noted Samual Langton's contribution about introducing the `slice` function for our `tidyverse` version of the lesson. Closing this issue.
