### ISSUE TITLE
Connect R with SQL

### ISSUE THREAD

**Issue by Generalkhun** [datacarpentry/R-ecology-lesson#461]
Hello, I want to connect R with database using 'DBI' package. At first, I connect via 'dbconnect' using code:

data.sqlite <- dbConnect(SQLite(), "file1.sqlite")

and its work fine. But when I want to open another database file ( .sql) instead by using

data.sql <-dbConnect(MySQL(), "file2.sql")

Its didn't work and showed error :

"Error in .local(drv, ...) : 
Failed to connect to database: Error: Can't connect to MySQL server on 'localhost' (0)"

I am new to this package and also to SQL language. So, do I need to set any other arguments or I have misunderstood something? 
Thanks

**Comment by sbamin** [comment]
@Generalkhun is SQL server running on localhost? localhost is typically the machine where you are running R code.

**Comment by fmichonneau** [comment]
sqlite is a self-contained database system. The entire database is in a single file that lives on your hard drive.

MySQL is a different beast. To use it on your computer you need to run (and set up) a MySQL server that you'll be able to connect to via localhost.

It depends on how large your dataset is and what you need to do with it, but for a single-user and less than 1 million rows per table, the lightweight sqlite is probably sufficient over MySQL (or other database systems).

**Comment by mondorescue** [comment]
@Generalkhun I'm going to close this issue. If you have further questions, feel free to reopen it.
