### ISSUE TITLE
Recommend turning off 'save your workspace' in RStudio?

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/R-ecology-lesson#463]
I've run into this issue where students have accidentally saved their workspace, and then things hadn't worked right when they open a new notebook. Also an issue in reproducibility. Do we want to add this recommendation on turning off 'save your workspace' in Preferences?

https://twitter.com/hadleywickham/status/1032665959734108160

**Comment by fmichonneau** [comment]
I think it used to be part of the lesson but I don't see it anymore. I always set up learners to disable this feature in the workshops I teach. It'd be good to add it back.

**Comment by orchid00** [comment]
let's do it!
we could reuse the picture: https://pbs.twimg.com/media/DlSsVJwXgAIe2qx.jpg
