### ISSUE TITLE
Cannot rmarkdown::render_site() this repo missing '/usr/local/bin/update-copyright.py'

### ISSUE THREAD

**Issue by MilesMcBain** [datacarpentry/R-ecology-lesson#465]
I was trying to render this repo's site without the TOC so I could have a more print friendly version for the lesson I am instructing.

It went mostly okay except `knitr` fell over in CITATION.Rmd due to the missing .py file.

Otherwise great job with this lesson, and I am looking forward to teaching it! :+1:

**Comment by fmichonneau** [comment]
The update-copyright is a system dependency that you can install with `pip install update-copyright`. I have been working on the tools for the citation information associated with the lesson though, so we might not this anymore.

Don't hesitate to let us know how your teaching goes!
