### ISSUE TITLE
Potentially confusing question in Inspecting Data Frames Challenge

### ISSUE THREAD

**Issue by amlatimer** [datacarpentry/R-ecology-lesson#471]
A minor issue came up while I was teaching the "Starting With Data" lesson. After inspecting the data frame, there is a Challenge which asks, among other things: "How many species have been recorded during these surveys?"

This is straightforward kind of question to answer, but what is a bit confusing is that there are both "species" and "species_id" columns in the data set. If you think about it a bit, it's clear the answer is that you should use "species_id" column, because some species names are repeated in multiple genera. But thinking about this and discussing it with the class seemed to me to add cognitive load that was not helpful to meeting the goal of the lesson. 

I suggest substituting the question:

**Comment by fdavenport** [comment]
The revised question could read: "How many species have been recorded in these surveys? Is this the same as the number of species_id recorded?" 
The correct answer would read something along the lines of: "There are 40 different species in the surveys data.frame. However, there are 48 different levels of species_id."

**Comment by katrintirok** [comment]
I also tripped about this in a recent workshop. As an ecologist I am more likely to think that I would need to check either genus and species column combined or the species_id column. However, we taught this workshop also with instructors and participants without a background in biology which can end up in confusion on instructor and participant side. What about changing the challenge towards: "How many genera have been recorded in the surveys?" This would practice the same thing and avoid confusion.

**Comment by amlatimer** [comment]
Yes, Katrin, I agree with that solution! It works to say “species_id” but then it’s confusing what that means, and so I agree it’s simpler to pose the question the way you did and ask how many genera have been recorded in the surveys. We just tripped over this again last week! No big deal but should be easy to fix I hope.
Andrew

**Comment by fmichonneau** [comment]
addressed with #663
