### ISSUE TITLE
Could add examples of layers in ggplot2 in newlines

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/R-ecology-lesson#472]
Submitted by Tim Stearns

---

Ideas for Chapter 5: Data visualization with ggplot2 episode

The chapter accurately describes the ggplot2 plot building procedure as typically an iterative process.  I wholeheartedly agree with this statement, but I feel it would help users if the authors also provided an example of how a ggplot2 object can have layers added on to it via being called again in a new line instead of having one continuous line with multiple layers added via the + operator.

 

The below code is taken from the lesson and refers to layering:

 

#Assign plot to a variable

surveys_plot <- ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length))

 

#Draw the plot

surveys_plot + geom_point()

 

Layering involves the initial creation of a ggplot2 object via using the ggplot() function on the data to be visualized.  This initial step lays the foundation for the plot and additional statements can be added (layered on) so as to customize the plot to your preference.

 

In the above code, layering is achieved by using only the + operator.  Often times, I find it very helpful to add layers to a plot object individually so as to evaluate each level of customization and ensure that the plot is being properly adjusted; this is cumbersome to do with the use of only + as it requires continually editing and rerunning the single line of plot code.  Instead of writing a single line of code, using the code mentioned above, one can evaluate the effect of an added layer by either overwriting the original plot object (i.e., surveys_plot) or creating a new object with the new level of customization (e.g., surveys_plot_1).  Using this method, a user can evaluate the effect of a layer on an individual basis that does not require them to constantly edit and rerun the single line defining the ggplot2 plot.

 

Example code:

#Add a layer of customization to the plot object to convert it to a scatterplot

surveys_plot <- surveys_plot + geom_point()

 

OR

 

#Create a new ggplot2 object that displays the data as a scatterplot

surveys_plot_1 <- surveys_plot + geom_point()

 

The above code could serve as the basis for a coding Challenge. For example, creating a scatterplot and changing the X-axis range from 0 to 100 by adding a layer to the plot that calls the xlim() function.

 

Example code:

#Use the ggplot2 scatterplot object and change the x-axis range from 0 to 100 using the xlim() function

#Previously provided code to specify scatterplot:

surveys_plot <- surveys_plot + geom_point()

 

#Code to edit above object with X-axis set to 0 to 100.

surveys_plot <- surveys_plot + xlim(0,100)

 

The above code is equivalent to the below single line of code, but the above code gives the user the option to allow the user to see each layer/change individually instead of taking place all at once (as would occur with the below code).

 

surveys_plot <- surveys_plot + geom_point() + xlim(0,100)

 

This method may not be overly helpful when working with only a few layers (in fact, it may be unnecessary), but it becomes almost essential when creating publication quality images that typically deal with 10+ layers that incorporate many customizations.  Furthermore, if you work in an environment where others are constantly providing input and changes to your plots, it becomes much easier to add/exclude/edit/view portions of the plotting code when layers are added on a line-by-line basis rather than embedded within a single line of code.

While it’s not necessary for all examples provided in this lesson to be written using this suggested method, I feel an example (as mentioned above) should be offered in the Building your plots iteratively portion of the chapter so users are exposed to this helpful alternative.

**Comment by michaelaw18** [comment]
I disagree and think that relabeling each new iteration another variation of "surveys_plot" may become cumbersome and lead to confusion later in the code. I agree with the sentiment that adding each layer should be carefully considered, and we should emphasize teaching that way in the lesson. I would urge students to keep the layers visible by continuing to add to the main ggplot2 object. Perhaps teaching with heavy commenting could address some of these comments, where you would suggest running the code after adding each layer and then adding the comment description which would result in this:

surveys_plot 
+geom_point()  #Adds points to the plot
+xlim(0,100) #setting x-axis parameter to display from 0 to 100

**Comment by tobyhodges** [comment]
Thanks everyone for contributing to this discussion. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As this issue relates to content in a version of the lesson before that update took place, I will close it. Please open a new issue if you believe that some or all of the changes being discussed here are remain relevant to the redesigned lesson, linking to this thread where relevant.
