### ISSUE TITLE
Clarifying arguments for download.file function

### ISSUE THREAD

**Issue by shorinola** [datacarpentry/R-ecology-lesson#474]
Background info: This contribution relates to the “starting with Data” section of the Data Analysis and Visualization in R for Ecologists lesion. In this section, trainees are shown how to use the download.file() function to download a dataset for the lesion as below: 
`download.file("https://ndownloader.figshare.com/files/2292169",` `“data/portal_data_joined.csv”)`
Contribution: As this is the first time trainees will be using this function to download data from the web, I think it should be clarified that this function takes in two arguments; the first argument being the url and the second argument being the destination file. The way the arguments are currently written ("https://ndownloader.figshare.com/files/2292169", “data/portal_data_joined.csv”) it might all be mistaken for one url or two url links separated by a comma and not the url and destination file.

**Comment by anacost** [comment]
Hi @shorinola ,
thank you for your contribution.
How would anyone believe that "data/porta_data_joined.csv" is an url link?

Maybe it can be presented like in the lesson for "R for reproducible scientific analysis: Exploring Data frames" (http://swcarpentry.github.io/r-novice-gapminder/05-data-structures-part2/index.html) where the second argument is preceded by "destfile =".

**Comment by mondorescue** [comment]
@shorinola I think your point is valid about the possible confusion. A few of my research assistants have said that the quotes and commas visually blending together and the `"data/portal_data_joined.csv")` part of the code doesn't register as being on a newline after starring at the computer screen for long hours. I think @anacost suggestion of explicitly stating the second parameter `destfile=` is a great idea to mitigate the possible mistake. Feel free to make a pull request with the suggested change by @anacost. In the meantime, I will close this issue.
