### ISSUE TITLE
Issue with download.file function in 'Starting with data' section

### ISSUE THREAD

**Issue by pantoum** [datacarpentry/R-ecology-lesson#476]
I noticed that I was having difficulty accessing the data set that is it become the 'surveys' data frame. 

If the command was altered from
# download.file("https://ndownloader.figshare.com/files/2292169", "data/portal_data_joined.csv") #
to 
# download.file("https://ndownloader.figshare.com/files/2292169","combined.csv") #

then it seems to work for me.

Thanks!

**Comment by j450h1** [comment]
I think this is because in **setup.R**, it attempts to create a data folder for you if one does not exist. I guess you didn't run this piece of code.

```
## file structure
if (! file.exists("data")) dir.create("data")

if (!file.exists("data/surveys.csv")) {
    download.file("https://ndownloader.figshare.com/files/2292172",
                  "data/surveys.csv")
}
```

**Comment by mondorescue** [comment]
@pantoum The `download.file("https://ndownloader.figshare.com/files/2292169", "data/portal_data_joined.csv")` code is setup assuming students followed through instructions in [Organizing your working directory](https://datacarpentry.org/R-ecology-lesson/00-before-we-start.html#organizing_your_working_directory), which then the students would have a `data` directory created to save the data as `portal_data_joined.csv` in the `data` directory.
