### ISSUE TITLE
Consider using read_csv() rather than using read.csv()

### ISSUE THREAD

**Issue by Br-Johnson** [datacarpentry/R-ecology-lesson#480]
In the 'starting-with-r' lesson, is there a reason not to use read_csv() as opposes to read.csv()? I suppose it comes down to whether or not the lessons want to introduce the readr package, and the tidyverse early on. read_csv() is much faster for large datasets compared to read.csv(), read_csv() also treats strings more consistently. Using read_csv() you can also point directly to urls, perhaps obviating the need for download.file().

**Comment by anacost** [comment]
Hi @Br-Johnson, thank you for your comment.
I disagree about treating strings more consistently. read.csv() has default to read strings as factors, which is more valuable for classification of data.
In read.csv() you can also point directly to URL (https://stat.ethz.ch/R-manual/R-devel/library/utils/html/read.table.html).

As mentioned in (https://github.com/swcarpentry/r-novice-gapminder/issues/442), this should be a discussion for the Advisory Committee.

**Comment by mondorescue** [comment]
@Br-Johnson Your comment is duly noted. We are working on changing over to using tidyverse hence using `read_csv()` consistently throughout the lesson (see issue #335).
