### ISSUE TITLE
consider reordering learning objectives for Starting with Data

### ISSUE THREAD

**Issue by sshiver** [datacarpentry/R-ecology-lesson#481]
This is a great lesson that is clearly written and easy to follow.  It seems to me that the learning objectives are out of order.  "Describe what a data frame is" is listed first, but this objective is completed after loading external data from a .csv, which is the second objective.

This lesson might be improved by moving the "What are data frames?" paragraph to the beginning of the lesson and verbally describing them before moving to loading data.  Alternatively, the lesson objectives may need to be reordered.

**Comment by fmichonneau** [comment]
Thanks for catching this! We re-ordered the learning objectives to match the content of the lesson.
