### ISSUE TITLE
Introduction to R

### ISSUE THREAD

**Issue by benextol** [datacarpentry/R-ecology-lesson#483]
It is important to make the class know that the assignment symbol(<-) is the same as equal to(=).
The equal to symbol should be clearly differentiated from the double equal to symbol(==)
It should be stated in the lessons that once an object has been assigned, it shows in the environment

**Comment by anacost** [comment]
Hi @benextol, thank you for your contribution!
The assignment operator is explained right after the first object (weight_kg) is assigned the value 55 in "Creating objects in R". 
The double equal is introduced in "Conditional subsetting" and the difference is explained after the logical/boolean data types are introduced.
