### ISSUE TITLE
Acceptable file formats recognized in R 

### ISSUE THREAD

**Issue by Ayansina** [datacarpentry/R-ecology-lesson#484]
Hi all,
I just want to make a suggestion:
1. That the audience must be taught the acceptable file formats recognized in R before starting R lessons. 
2. How to convert data sets to acceptable formats.
3. Familiarity with signs and symbols used in each package

**Comment by AbuFaozan** [comment]
Hi
Thanks for your suggestions. I'm in agreement with your suggestions, most especially that of number 1 and 2. Additionally, there maybe no need compiling signs and symbols used in different packages. I feel relevant symbols should be introduced when it is applicable during the session to avoid a bit of mixed up and learning stress. The more the signs and symbols are used in practice, the more we get familiar with their functions.

**Comment by fmichonneau** [comment]
Thanks for your suggestion. After discussing with the other maintainers, we think this is outside the scope of this lesson.
