### ISSUE TITLE
file number

### ISSUE THREAD

**Issue by FelipeCarrillo** [datacarpentry/R-ecology-lesson#485]
Hi;
Kind of silly question but couldn't figure it out. I am going through the exercises here:
https://datacarpentry.org/R-ecology-lesson/02-starting-with-data.html
How do you know the file number? For example this one 2292169 belongs to the combined.csv file.
I went here: https://figshare.com/articles/Portal_Project_Teaching_Database/1314459
but couldn't find that number or the number for other files anywhere.

**Comment by mondorescue** [comment]
The "file number" is an auto generated url shortcut by the Figshare platform. It is not something that we control or generate. You can find out what the "number" of the file is by clicking on the file itself and on the bottom of the webpage, you should find in the tab the "file number."
