### ISSUE TITLE
Lesson Contribution: Muwonge Abubaker

### ISSUE THREAD

**Issue by sheraaron** [datacarpentry/R-ecology-lesson#488]
In the "Data Analysis and Visualization in R for Ecologists"; under section 'Manipulating, analyzing and exporting data with tidy verse', and sub-section 'Selecting columns and filtering rows',

To select all columns except certain ones, put a "-" in front of the variable to exclude it. Besides using below this:
select(surveys, -record_id, -species_id)

You can as well use the following command below:
select(surveys, -c(record_id, species_id)) # write a vector of columns to be exclude using c function preceded by "-"

**Comment by fmichonneau** [comment]
using this type of syntax isn't encouraged. We could introduce the variable selector functions (e.g., `ends_with()`) instead.
