### ISSUE TITLE
Lesson Contribution: Hassan Ali

### ISSUE THREAD

**Issue by sheraaron** [datacarpentry/R-ecology-lesson#489]
In this lesson:(Data Carpentry, R-ecology-lesson/03/Manipulating data frame /Selecting columns and filtering rows) which can be found following this link: https://datacarpentry.org/R-ecology-lesson/03-dplyr.html

In this lesson: to select columns of a data frame, using select(), the code was written as follows: select(surveys, plot_id, species_id, weight)

My contribution to improve the code would be to use a vector as follows: select(surveys, c(plot_id, species_id, weight)) by using c().

---

**Comment by fmichonneau** [comment]
this type of syntax isn't encourage in the tidyverse.
