### ISSUE TITLE
Clarifying repo purpose and contributions 

### ISSUE THREAD

**Issue by anacost** [datacarpentry/R-ecology-lesson#491]
swcarpentry/r-novice-inflammation/issues/401
@diyadas suggests that we add more information on the readme of the lesson. 
It seems like changes have started there. So we should update our lesson as well. 
I copy here part of her initial comment:

if they landed on our page by "browsing GitHub," vs. coming through the Carpentries. I did not have this issue because I was directed to this repo by the Carpentries, but it's not immediately clear that our repo is for a website (unless people know where to look) and most issues as filed don't directly link to the issue in question - potential new contributors have to be very clear on what "episodes" are and where the issue is.

Can we change:

    The description (not changeable by us maintainers but something to send upward): "Repo creates a website for the Software Carpentry introduction to R for novices using inflammation data"
    Change the beginning of the README to specify that this repo generates the lesson website (and link to the lesson again!)
    Change the issue template to ask that people link to the episodes, so that when we tag "good first issue" new contributors know where to start (??) ... or we could do this as maintainers in our response to issues.

**Comment by katrinleinweber** [comment]
Please have a look at #403 and comment there or on #401 if anything is still missing.

**Comment by anacost** [comment]
Closing this issue with commit 
https://github.com/datacarpentry/R-ecology-lesson/commit/5877617581b4a7e45f8df72f6a86da7f1ebfe502
from carpentries/style PR 
https://github.com/carpentries/styles/pull/395
