### ISSUE TITLE
Suggestion: Introduce seeking more information on R functions at the same time as introducing functions

### ISSUE THREAD

**Issue by liiskolb** [datacarpentry/R-ecology-lesson#494]
While preparing for a workshop as a helper I discovered that introducing the help interface might be too early in the schedule. Currently it is in the "Before we start" section and shows how to search more information on R functions. However, the term "function" is introduced only in the second section, "Introduction to R". 

I think that the help seeking would fit better to the part "Functions and their arguments" in "Introduction to R". This way it feels a bit more intuitive. And we will not overcrowd students with knowledge we don't apply right away. 

Kind of: so far we have seen running commands -> functions are sets of commands -> there are thousands of ready-made functions you can use in R -> you can seek more information about them using _?_ or the _help pane_

**Comment by fmichonneau** [comment]
Thanks for your suggestion. We are planning a revised version of this lesson where we will teach concepts as they arise rather than front-loading the lesson. We'll make sure to incorporate this change in the upcoming update.
