### ISSUE TITLE
Lesson Contribution 

### ISSUE THREAD

**Issue by sheraaron** [datacarpentry/R-ecology-lesson#504]
I have found a grammatical error in the "Ecology Curriculum". The lesson is "Data Analysis and Visualization in R for Ecologists". The error is in the subsection titled "Manipulating Data Frames" under "split-apply-combine data analysis and the summarize() function".

There is a sentence that reads:

"When grouping both by sex and species_id, the last few rows are for animals that escaped before their sex could be determined and weighted."

Use of the word "weighted" is confusing. We are talking about the body weights of various animals, not some sort of weighted mean or weighted regression or something like that.

This sentence should instead read:

"When grouping both by sex and species_id, the last few rows represent animals that escaped before their sex and body weights could be determined."

**Comment by sheraaron** [comment]
1. In the "Starting with data" chapter, "read.csv" is introduced to learners. However, not arguments of that function are introduced, such are "sep", "header", etc. These arguments are important and would provide learners with more information on that command.

2. At the bottom of that chapter, the data type of factors are introduced while it is not introduced about how to transfer the data type and the reason for transformation. For example, we'll transfer the factors to numeric or vice versa under quite some circumstances in data analysis and it will benefit the learners if they know why and how.

**Comment by anacost** [comment]
Thank you, @sheraaron, for this remark! It has been fixed in the lesson.
