### ISSUE TITLE
Lesson Contribution

### ISSUE THREAD

**Issue by sheraaron** [datacarpentry/R-ecology-lesson#505]
1. In the "Starting with data" chapter, "read.csv" is introduced to learners. However, not arguments of that function are introduced, such are "sep", "header", etc. These arguments are important and would provide learners with more information on that command.

2. At the bottom of that chapter, the data type of factors are introduced while it is not introduced about how to transfer the data type and the reason for transformation. For example, we'll transfer the factors to numeric or vice versa under quite some circumstances in data analysis and it will benefit the learners if they know why and how.

**Comment by fmichonneau** [comment]
1. Function arguments are explained in the "Introduction to R" section and we don't want to overwhelm learners about all the options available for `read.csv` at this point of the workshop.

2. We opened #517 to address this point.
