### ISSUE TITLE
Change plurality for line 27?

### ISSUE THREAD

**Issue by doujouDC** [datacarpentry/R-ecology-lesson#506]
HI,

https://github.com/datacarpentry/R-ecology-lesson/blob/bc928f6cda893f12535f4a5797f90cdb6aa58b2a/03-dplyr.Rmd#L27

Should it not read

"Use summarize, group_by, and count to split a data frame into groups of observations, apply a summary statistic for each group"

OR

Use summarize, group_by, and count to split a data frame into groups of observations, apply summary statistics for each group"

Best

Doug

**Comment by anacost** [comment]
Hi @doujouDC 
thank you!
