### ISSUE TITLE
Suggestion for line 62

### ISSUE THREAD

**Issue by doujouDC** [datacarpentry/R-ecology-lesson#510]
https://github.com/datacarpentry/R-ecology-lesson/blob/9921bcd933bed88588c3608b3a1ac2d7d10e6b11/03-dplyr.Rmd#L62

Perhaps this should be: This time **we** will use the tidyverse package to read the data and avoid having to set stringsAsFactors to FALSE

**Comment by anacost** [comment]
thank you, @doujouDC, for your contribution!
