### ISSUE TITLE
Add a d to comprise

### ISSUE THREAD

**Issue by doujouDC** [datacarpentry/R-ecology-lesson#511]
https://github.com/datacarpentry/R-ecology-lesson/blob/9921bcd933bed88588c3608b3a1ac2d7d10e6b11/03-dplyr.Rmd#L523

Perhaps this should be: We'd need to create a new table where each row (the unit) is comprise**d** of values of variables associated with each plot.

**Comment by anacost** [comment]
thank you, @doujouDC , for this contribution!
