### ISSUE TITLE
Extracting records with missing date information

### ISSUE THREAD

**Issue by DanielleQuinn** [datacarpentry/R-ecology-lesson#514]
I would like to suggest a change to the last part of the "Starting with Data" episode.

The objective is to create a subset of the data frame that has missing dates. Using the code below (found in the current lesson) creates a data frame that contains only the relevant information (i.e. date components).

is_missing_date <- is.na(surveys$date)
date_columns <- c("year", "month", "day")
missing_dates <- surveys[is_missing_date,  date_columns]

I think that it would be simpler for learners and likely more practical to extract all columns of the data frame where date is missing.

is_missing_date <- is.na(surveys$date)
missing_dates <- surveys[is_missing_date,  ]

or even

missing_dates <- surveys[is.na(surveys$date), ]

This approach removes the extra step of creating a vector of date_columns and would be a more authentic task -  if you were really trying to see which records were missing dates and possibly figure out why, you would likely want to see the rest of the data associated with those records.

**Comment by fmichonneau** [comment]
Thanks for the suggestion @DanielleQuinn
