### ISSUE TITLE
Suggestion: change column "genus" to "genera" either in dataset or with rename() function

### ISSUE THREAD

**Issue by baeolophus** [datacarpentry/R-ecology-lesson#518]
I suggest either adding a short code piece to use the rename() function to change the column "genus" to "genera" (thus alerting the learners to their relationship here, while adding a new function) or changing the column name in the original dataset.  Otherwise, I've found that using the correct plural for genus confuses learners who are not biologists.  Although it's the R ecology lesson and one might assume biology knowledge, at my institution we use it for learners from multiple disciplines who are not familiar with the plural genera.

**Comment by anacost** [comment]
Hi @baeolophus,
thank you for your suggestion!
Would you like to send us a pull request with the rename() function?

**Comment by martinjeanphd** [comment]
Hi,
I am willing to propose a modification here (as my first issue for checkout), but first, I need to fully understand what's need to be done. 
Here what I am getting from @baeolophus 's suggestion:
- replace all instances of "genus" to "genera" in the training material;
- add some explanation of the usage of the rename() function and why it is needed.

Am I right?

Thanks,

**Comment by baeolophus** [comment]
Almost yes, but not quite.  The dataset has the column name "genus" and the metadata at the beginning of the lesson defines this.  But later in the lesson   So the manual should say that we use rename() to change "genus" (in the original dataset) to plural "genera" in the [data manipulation lesson](https://datacarpentry.org/R-ecology-lesson/03-dplyr.html).  A different way of resolving this would be to not add new code, but to parenthetically note that genera is the plural of genus at its first use in that lesson.

**Comment by kimh11** [comment]
Hi @baeolophus, great suggestion on incorporating genera/genus to the lesson. I thought I'd give this a shot as my checkout process.

Found 3 possible places to add this in:

1. The first mention of "genera" is in [Manipulating data](https://datacarpentry.org/R-ecology-lesson/03-dplyr.html) section "Reshaping with gather and spread":

> Note that now the NA genera are included in the re-gathered format. Spreading and then gathering can be a useful way to balance out a dataset so every replicate has the same composition.

We could add a comment here to clarify that `genera ("genera" is the plural form of "genus")`. 

OR

2. Address it at the same time as issue #471. Change the challenge question in [Starting with data](https://datacarpentry.org/R-ecology-lesson/02-starting-with-data.html) with "How many genera have been recorded in the surveys?" as suggested by [katrintirok](https://github.com/datacarpentry/R-ecology-lesson/issues/471#issuecomment-461557741) and make a note that genera is plural of genus.

OR

3.  Comment on genera/genus and add the rename() function in [Manipulating data](https://datacarpentry.org/R-ecology-lesson/03-dplyr.html) section "Pipes" and change all code referring to genus to genera after this point:

```
The column heading "genus" is a singular noun, but the dataset includes many different ones and should be changed to "genera", which is the the plural form. To rename this column, use rename(). 
This function takes the data frame as the first argument followed by the re-assignment of the column name (new column name = existing column name). 
You can use the pipe to send the surveys dataset through rename() to change the column name and assign it back to surveys data frame. 

surveys <- surveys %>% rename(genera = genus)
```

What do you think would be the better option? I'm leaning towards option 2 if the challenge question is going to be changed as it seems the most natural there and I think column headings are usually singular. But, happy to try creating a pull request on any of the options!

**Comment by martinjeanphd** [comment]
I agree that your second option would be appropriate.

**Comment by baeolophus** [comment]
I agree that option #2 sounds best.  Thank you!

**Comment by Teebusch** [comment]
I don't understand why you are suggesting to use the plural form as a column name?
As far as I know, column names in tidy data frames are in the singular form. I can't find a reference for it, but I'm almost certain this is a "good practice" I've read somewhere.
See also in the data set used in the lesson: year, month, day, NOT years, months, days. Plurals are only used when an individual cell contains a plurality of things, usually a count. For example "cases", "incidents", "visitors".

**Comment by TheSillyBadger** [comment]
I agree. Keeping the column name singular seems to the most consistent. This issue looks resolved

**Comment by Teebusch** [comment]
I'll close this because I believe we all agree that a column name in plural for a column that contains "singular" data could be confusing.
