### ISSUE TITLE
Factor lesson

### ISSUE THREAD

**Issue by aurielfournier** [datacarpentry/R-ecology-lesson#521]
While teaching the starting with data lesson the past two days I found myself having to do some real verbal gymnastics to not say the words 'sex object' while discussing the vector of 'male' and 'female' 

Would it be at all possible to pick another subject for that object? We could use months, or species, or something, so I can never accidentally say the word 'sex object' in front of 30 people again, or have someone tell me after that it was weird, and distracting.

**Comment by mondorescue** [comment]
I think we can switch it to *taxa* from *sex*. Other objects have too many levels.

**Comment by murraycadzow** [comment]
I'll also add that "yearly_sex_counts" in the data visualisation - plotting time series data is also awkward to be saying multiple times in front of people

**Comment by anacost** [comment]
Hi @aurielfournier 
would you be happy with the update from issue #108 ?
How would you feel about saying "the variable sex" in front of people?

**Comment by aurielfournier** [comment]
I like it! thanks!
