### ISSUE TITLE
Suggestions to improve tidyverse-first/01-visualizing-ggplot.Rmd

### ISSUE THREAD

**Issue by reblake** [datacarpentry/R-ecology-lesson#522]
Substantive comments to improve logical flow, text, and included code for ggplot lesson on tidyverse-first branch: 
1) Move lines 79 - 84 up to below line 64.
2) Use text and example from lines 111 - 117 to replace lines 66 - 76
3) Choose to use `surveys_plot` for the rest of the lesson after line 100, or don't introduce this until much later in the script. Consistency is key to make it clear for learners.  
4) Re-structure the part on iteratively building plots to focus around things learners will want to do: add regression line, add more data with another geom, change colors, change line color/thickness, change text size, move labels around on the plot, annotate plot, etc.
5) Include an actual example of a custom theme built by modifying an existing theme such as `theme_bw()`.  Potentially have learners further modify this custom theme example to make their own custom theme.  
6) Make the sections all of a similar type.  For example, faceting is something you can do to many type of plots, but boxplot is a specific type of plot.

**Comment by tavareshugo** [comment]
I've written [this lesson](https://tavareshugo.github.io/data_carpentry_extras/ggplot2_prelude/intro_ggplot2.html) ([source Rmd](https://github.com/tavareshugo/data_carpentry_extras/blob/master/ggplot2_prelude/intro_ggplot2.Rmd)), which I think could be largely copied on to the new `tidyverse-first` branch. 

The narrative flows as:

* Build a basic graph
* Change geometries "manually"
* Change geometries _based on data_ (with `aes()`)
* Overlay multiple geometries
* Control aesthetics for individual geometries
* Control scales

In my view, the original lesson did not clarify enough the difference between defining an aesthetic _inside_ or _outside_ of `aes()`. I think this is made clearer in this lesson. 

The original also did not really talk much about scales, but I've given it its own section, clarifying the generic use of `scale_<aesthetic>_<type>`, and then with examples of continuous and discrete scales. 

I haven't incorporated the more detailed customisation (themes) nor the facets here (we were doing that after _data manipulation_ session). I actually think it's nice to break the plotting into two modules, to intercalate with `dplyr` and better see the connection between data manipulation and graphics for interactive data exploration.

**Comment by tobyhodges** [comment]
Thanks both for contributing to this discussion. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As this issue relates to content in a version of the lesson before that update took place, I will close it. Please open a new issue if you believe that some or all of the changes being discussed here are remain relevant to the redesigned lesson, linking to this thread where appropriate.
