### ISSUE TITLE
Change comma to period

### ISSUE THREAD

**Issue by whit1951** [datacarpentry/R-ecology-lesson#525]
On the home page (https://datacarpentry.org/R-ecology-lesson/index.html) under the "Contributor" heading, change the end of the sentence to a period rather than a comma. So the final line reads: "The list of contributors to this lesson is available **here.**" rather than: "The list of contributors to this lesson is available **here,**"

**Comment by anacost** [comment]
Thank you, @whit1951, for your contribution. We have corrected it.
