### ISSUE TITLE
Typo in a link address

### ISSUE THREAD

**Issue by RodenLuo** [datacarpentry/R-ecology-lesson#527]
In this page: http://datacarpentry.org/R-ecology-lesson/04-visualization-ggplot2.html#challenge15

Search for "Use the RStudio **ggplot2 cheat sheet** for inspiration. Here are some ideas:"

The link to "**ggplot2 cheat sheet**" lacks an "h" in the beginning.

**Comment by mondorescue** [comment]
@RodenLuo thank you for catching this typo. I've addressed it with PR #528
