### ISSUE TITLE
No tables in mammals database

### ISSUE THREAD

**Issue by anikap2** [datacarpentry/R-ecology-lesson#529]
I'm working through the tutorial on SQL databases in R and the line `src_dbi(mammals)` shows that the database does not contain any tables so all further code on the `survey` table does not work. Can you confirm that the mammals database contains the same tables as the examples? Thanks!

**Comment by mondorescue** [comment]
@anikap2 I was able to verify that the sqlite database contains all the necessary tables. Please check that you have downloaded the correct file.

**Comment by mondorescue** [comment]
@anikap2 I'm going to close this issue. If you have further questions, feel free to reopen it.
