### ISSUE TITLE
update link description to windows install file

### ISSUE THREAD

**Issue by EcoTopic** [datacarpentry/R-ecology-lesson#530]
In the text a suggestion is made to select the installation file "**RStudio x.yy.zzz - Windows XP/Vista/7/8**". On the Rstudio site this file is now "**RStudio x.yy.zzz - Windows Vista/7/8/10**".

line 88 and 89 in the index.rmd file

It might help to change this in the text to avoid confusion for novices.

**Comment by anacost** [comment]
thank you, @EcoTopic, for your contribution!

We have updated it in index.Rmd
