### ISSUE TITLE
I would introduce histogram, density plot and violin plot before going to boxplot directly in  "Data visualization with ggplot2"

### ISSUE THREAD

**Issue by bishwaG** [datacarpentry/R-ecology-lesson#533]
I would introduce histogram, density plot and violin plot without going to boxplot straight. I would also mention what histogram and density plots tells and why we can use boxplot to tell the same thing and even more information about our data. I have only used 3 species for demonstration.

First I would take only one species to make a histogram.
```r
# subset only NL species
subset_surveys <- subset(surveys_complete, species_id == "NL")

## Histogram need only x in aes()
# color=grey adds color between bars.
# If you want to fill the bars with a color for example fill="red" can be put inside geom_histogram
ggplot(data = subset_surveys, mapping = aes(x = weight)) +
  geom_histogram(color="grey")
```
![image](https://user-images.githubusercontent.com/27332974/55947916-19214900-5c58-11e9-8011-cf895250e32a.png)

I would also show how to compare histograms.
```r
## combining two histograms
#subset three species
subset_surveys <- subset(surveys_complete, species_id == "NL" | species_id == "DS" | species_id == "DO")

# fill=species_id fills the bars based on species
ggplot(data = subset_surveys, mapping = aes(x = weight, fill=species_id)) +
  geom_histogram(color="gray", position="identity", alpha=0.2) 
```
![image](https://user-images.githubusercontent.com/27332974/55947950-2b02ec00-5c58-11e9-8b77-5cfc81c36ed1.png)

I would tell that putting too many histogram in one plot looks messy. Density plots provides neat visualization instead.

```r
ggplot(data = subset_surveys, mapping = aes(x = weight, fill=species_id)) +
  geom_density(alpha=0.2) 
```
![image](https://user-images.githubusercontent.com/27332974/55947985-3e15bc00-5c58-11e9-8c61-75dd77b4de47.png)

I would now introduce violin plot and mention that how it can substitute histogram and density plots.

```r
ggplot(data = subset_surveys, mapping = aes(x = species_id, y = weight, fill=species_id)) +
  geom_violin(alpha=0.2) 
```
![image](https://user-images.githubusercontent.com/27332974/55948014-4bcb4180-5c58-11e9-9370-e0b64904e5ba.png)

 After introducing boxplot I will combine jitter, violin plot and boxplot.
 
 ```r
 ggplot(data = subset_surveys, mapping = aes(x = species_id, y = weight, color=species_id)) +
  geom_jitter(alpha=0.1) +
  geom_violin(alpha=0.3, width=1) +
  geom_boxplot(width=0.1)
 ```
![image](https://user-images.githubusercontent.com/27332974/55948036-584f9a00-5c58-11e9-9b9d-e647f4261e7b.png)

**Comment by mondorescue** [comment]
Thanks @bishwaG your suggestion looks great. You're suggestion will be considered for the tidyverse version of the lesson.
