### ISSUE TITLE
Lesson suggestions (submitted by email from trainee)

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/R-ecology-lesson#536]
The following are my contributions in R lesson, as the last check out step to become an instructor.
First the lesson is a bit difficult for a beginner to follow. Example the session "before we start" should be part of introduction session by summaries into a short sentences,the way its in the "introduction to R" for a beginner to follow.
Second: In the session "manipulating data frames", before: library("tidyverse"), I suggest to add, install.packages("tidyverse"). This step have been mentioned in the previous lesson by provided a link to follow, but not all will able to follow or to get that, and then short sentence which says do this step or install this package if you have not done so in the previous lesson.

**Comment by dklinges9** [comment]
I had the same thought when I recently went through the lesson. The only point in the lesson that the command `install.packages()` is mentioned is briefly at the bottom of the "Home" index....and it isn't quite mentioned with full context (the page says to type the command into the console, but what the "console" is hasn't actually been introduced yet.
In an actual in-person workshop, using `install.packages()`would certainly come up at least once, but for learners playing from home it might be nice to mention again.

I [submitted a pull request](https://github.com/datacarpentry/R-ecology-lesson/pull/538) in response to the above comment and my thoughts presented here.
Note that I didn't include a code chunk with `install.packages()`, as this would have required setting a CRAN mirror and looking through the repo it seems as if this is something intentionally avoided...

**Comment by fmichonneau** [comment]
fixed by #538
