### ISSUE TITLE
Inconsistent use of quotation marks in library loading

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/R-ecology-lesson#543]
(Contributed through email for Instructor checkout)

There is inconsistency between the syntax used to load libraries between loading lubridate in the date section of Starting with data (https://datacarpentry.org/R-ecology-lesson/02-starting-with-data.html) and loading tidyverse in the Manipulating data frames lesson (https://datacarpentry.org/R-ecology-lesson/02-starting-with-data.html).

For consistency I think it should either stick to using no quote marks or both should have quote marks.

**Comment by mondorescue** [comment]
Duly noted and will check for consistency.
