### ISSUE TITLE
Command for 02-starting-with-data

### ISSUE THREAD

**Issue by zhejyang** [datacarpentry/R-ecology-lesson#544]
i have a thought that can make this function connect to a practical level. 

By starting with getwd() function which allows beginner to know where they at in the computer system, Its important for the next steps. "User/TJ".

I tried this on my computer
I created a folder on my desktop called "data". then use the download.file function. it will run, but it will have a warning message and no file in the folder.
warning message see blew
 "In download.file(url = "https://ndownloader.figshare.com/files/2292169",  :
  URL https://ndownloader.figshare.com/files/2292169: cannot open destfile 'data/portal_data_joined.csv', reason '**No such file or directory**' destfile is working on the **current working** directory.  

Unless you changing to current working directory by "destfile = "User/TJ/desktop/data/portal_data_joined.csv")".

**Comment by mondorescue** [comment]
@zhejyang Thank you for the feedback. We anticipate that the instructor has guided their students to be in the correct working directory prior to downloading the data file, or that the student is working through the lesson sequentially from the beginning as the *Before we start* chapter tells the student how to they should setup their working directory (using `setwd()` and checking with `getwd()`).
