### ISSUE TITLE
Variable `plot_type`

### ISSUE THREAD

**Issue by bryandmartin** [datacarpentry/R-ecology-lesson#552]
A variable in the data, `plot_type` caused some confusion in the workshop. When students are just learning about plotting, they assumed that `plot_type` was describing the type of plot (as in the plot generated with ggplot), rather than a covariate in the data describing a physical thing. Perhaps it could be renamed to `exclosure_type` or something similar.

**Comment by CaitlinBate** [comment]
I agree that this could be confusing in the Data Visualization section. However, when the dataset is imported in Starting with Data, all variables are defined and the dataframe is explored through several functions (```head()```  ```str()```  ```names()``` etc.) to provide familiarity with the dataset. This variable is also used to illustrate ```stringsAsFactors=FALSE```, increasing understanding that its a variable and not a description of a graph type.

Did this confusion arise with students who did not continue linearly through the lesson and instead began (after a break) with the Data Visualization episode? Perhaps after a break it is worth re-familiarizing with the dataset again.

Or, of course, a re-name is also possible! I suggest ```quadrat_type``` or ```transect_type``` as options that may be more intuitive to ecologists. 

In my opinion, learners should be familiar with these column names before Data Visualization and  ```plot-type``` isn't used in the Data Visualization episode (thankfully) so the plot vs. plot_type confusion may be lessened. Not sure if this is worth an update but would like to hear what others think!

**Comment by Teebusch** [comment]
In section "Starting with Data" > "Loading the survey data" instructors have an opportunity to go through the columns of the data frame and clarify any potential confusions (what is a "plot", what is "genus", ...?). If the learners are not ecologists, this would be the place to do it. Maybe the table with the variables should be expanded a bit, `plot_ID -- ID of a particular plot (i.e., a section of the area that was surveyed)`

One could also add a note to the instructor notes, such as :

> "If the learners are not familiar with the ecology terminology used in the data set, it might be a good idea to briefly review it here. in particular "genus" and "plot" have caused some confusion to learners in the past.
