### ISSUE TITLE
suggestions about view() [submitted by email]

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/R-ecology-lesson#559]
Here is a small piece I would like to add on in R for the ecology lesson (data carpentry). The episodes are Starting with data : https://datacarpentry.org/R-ecology-lesson/02-starting-with-data.html and Manipulating data: https://datacarpentry.org/R-ecology-lesson/03-dplyr.html.

When following the episode Starting with data, I have several times failed to run the function View(surveys). In my training class, we did not get it also. Finally, I figured out that the first letter of the function View() is capitalized. But because the capital "V" and the lower case "v" look so similar, it is hard to caught the difference. 

The tricky part is that after installed the package "tidyverse" following the next episode Manipulating data, the issue then was gone. The reason is that the first letter of the function view() in the package "tidyverse" is lower case this time. So after install the package "tidyverse", either using lower case or upper case of the first letter to call the function View()/view() works.

Thus, I think it is better to add a sentence after introducing the function View() in the episode Starting with data and another sentence in the next episode Manipulating data. 

In the episode Starting with data, the sentence could be "Notice that the first letter of View is capitalized." 

Then, in the next episode Manipulating data, when use the function view() to preview the data, I suggest to use lower case "view" to distinguish the difference with the previous episode. Then add a sentence after introducing the function view() to mention the difference.

Use lower case view() for the syntax.

The added sentence could be: "Notice that the first letter of the function view() could be lower case if you called the package 'tidyverse'."

**Comment by fmichonneau** [comment]
addressed with #663
