### ISSUE TITLE
comment on the lesson (checkout)

### ISSUE THREAD

**Issue by Viibii** [datacarpentry/R-ecology-lesson#561]
The format of these comments is:
- first I quote the fragment in question or refer to a particular line in the github file
- then, following the COMMENT, I write my comment/suggested correction

intro to R
https://github.com/datacarpentry/R-ecology-lesson/blob/master/01-intro-to-r.Rmd

line 100 (weight_kg <- 55) #  but putting parenthesis around the call prints the value of `weight_kg`

COMMENT  why is this there? have never seen parentheses used like that (at least not in R). This seems to be increasing cognitive load and in my opinion does not need to be there

line 119
COMMENT Full stop missing between "objects" and "For"

Line 173 Functions are “canned scripts” that automate more complicated sets of commands including operations assignments, etc. 

COMMENT  I would remove "including operations assignments". In my view this is unnecessary to understand what is written later and increases cognitive load. 

Line 320
COMMENT  double space between 'types' and 'that'

Line 584
COMMENT  was the concept of a "script" ever explained? If not then we have not 'learned how to write scripts'... I don't think the idea/definition of a script was ever introduced.

02-starting with data
https://github.com/datacarpentry/R-ecology-lesson/blob/master/02-starting-with-data.Rmd

Line 53
COMMENT  at this point it becomes confusing for many people (I run this workshop before). I think here the text should remind everyone about the idea of a working directory, specifically instruct people to make a data folder in their working directory, and only then proceed with download instructions.

Line 101
COMMENT  I don't think anyone in a typical audience (very often non native speakers, like me) will understand what a 'wrapper function' is.  The word 'wrapper' is a jargon word, and one I think that doesn't have to be introduced to the students at all. We could say 'are actually VARIANTS of the main 'read.table()'

Line 111
COMMENT  'splitted' should be corrected to 'split' . The third form of split is split.

Line 253
COMMENT I think it would be worth elaborating, i.e. instruct people to type something and then press tab to complete

Line 325
COMMENT As a non-native speaker, I cannot assess this well, but I am not sure everyone immediately knows what an integer is. Maybe a better idea is to say 'numbers: 1, 2, 3, etc.". You also say in this line "treating them[levels] as strings". The word 'strings' to refer to character vectors was rarely mentioned previously, and I suggest replacing it with "character vector'.

Line 388 and 389
COMMENT I really struggle to understand the code in line 389. Every time I have to break it down for myself into small steps. This means that it cannot be the 'recommended way' to perform this operation (if a competent practitioner struggles... Although I might just be less competent than I think...). If the recommended way is half-incomprehensible, while the way shown in line 388 is easy, then line 388 should be the recommended way. I think line 388 code has the advantage of reminding/teaching the learner about the inner workings of R (i.e. what is explained above - that R sees levels as a series of integers, so you need to first convert them into text, and only then into an actual number.) Line 388 is easy to explain. If you really insist line 389 code is the recommended way, please explain in the instructor notes, why? And just also explain this code step by step.  I know it is explained already, but I don't really get this. The fact that you have to explain this line of code in a long paragraph means it is not the most intuitive way to do things...

04-Data visualization with ggplot2
https://github.com/datacarpentry/R-ecology-lesson/blob/master/04-visualization-ggplot2.Rmd

Line 620
COMMENT I think setting up folder structure should happen at the beginning of this workshop, and not here in the middle. It's confusing. Potentially even we should do this at the 'intro to R/before we begin" stage.

**Comment by mondorescue** [comment]
@Viibii Thanks for the feedback. We will incorporate them into the lesson as appropriate.
