### ISSUE TITLE
Provide copy of surveys_complete.csv

### ISSUE THREAD

**Issue by rgaiacs** [datacarpentry/R-ecology-lesson#568]
The [visualisation part of the lesson](https://datacarpentry.org/R-ecology-lesson/04-visualization-ggplot2.html) uses `surveys_complete.csv` but this file is created during the [manipulating data part of the lesson](https://datacarpentry.org/R-ecology-lesson/03-dplyr.html). Could we have a copy of `surveys_complete.csv` available to download for learners and instructors that are starting from the data visualisation? Thanks!

**Comment by rgaiacs** [comment]
This is a duplicated of https://github.com/datacarpentry/R-ecology-lesson/issues/558.

**Comment by tobyhodges** [comment]
Thanks @rgaiacs for opening this, and hello! 👋 The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As this issue relates to content in a version of the lesson before that update took place, I will close it. The new version of the lesson includes a direct link to download the CSV.
