### ISSUE TITLE
Update data to v9 of Portal Project Teaching Database

### ISSUE THREAD

**Issue by rgaiacs** [datacarpentry/R-ecology-lesson#569]
The lesson says

```
Data files for the lesson are available and can be downloaded manually here: https://doi.org/10.6084/m9.figshare.1314459
```

and later instruct the learners to run

```
download.file(url="https://ndownloader.figshare.com/files/2292169",
              destfile = "data_raw/portal_data_joined.csv")
```

When I look at https://figshare.com/articles/Portal_Project_Teaching_Database/1314459 (https://doi.org/10.6084/m9.figshare.1314459 redirects to it), I couldn't find the link `https://ndownloader.figshare.com/files/2292169` neither the file `portal_data_joined.csv`.

Can we update the lesson to use v9 of Portal Project Teaching Database. And also save the file with a name that matches what learners will find in figshare?

**Comment by tobyhodges** [comment]
The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As this issue relates to content in a version of the lesson before that update took place, I will close it. [The current content accesses the Portal dataset via the `ratdat` package](https://datacarpentry.org/R-ecology-lesson/instructor/visualizing-ggplot.html#setup).
