### ISSUE TITLE
Replace gather() & spread() with pivot_longer/_wider()

### ISSUE THREAD

**Issue by katrinleinweber** [datacarpentry/R-ecology-lesson#580]
Just a pointer to https://github.com/datacarpentry/r-socialsci/issues/104, because also relevant here.

Since this will requires update to img/[gather](https://github.com/datacarpentry/R-ecology-lesson/blob/master/img/gather_data_R.png)_... & [spread](https://github.com/datacarpentry/R-ecology-lesson/blob/master/img/spread_data_R.png)_data_R.png: Where those generated from shareable source files for #305, @ab604? If so, please consider pushing them into `img/` as well.

cc @chriseshleman & @mondorescue because of #501

**Comment by katrinleinweber** [comment]
Since this will require update to img/[gather](https://github.com/datacarpentry/R-ecology-lesson/blob/master/img/gather_data_R.png)_... & [spread](https://github.com/datacarpentry/R-ecology-lesson/blob/master/img/spread_data_R.png)_data_R.png: Where those generated from shareable source files for #305, @ab604? If so, please consider pushing them into `img/` as well.

cc @chriseshleman & @mondorescue because of #501

**Comment by katrinleinweber** [comment]
Once the graphics get updated, it might make sense to replace `plot_id` with `plot_type`. IMHO, it's more self-explanatory than than the id, which an earlier example even de`select`s.

**Comment by ab604** [comment]
Hi, Apologies for the delay. Life stuff. I've re-made them for `pivot_longer` and `pivot_wider` now. The original files are Adobe Illustrator files. What's the best way to share these? And for the PNG's

**Comment by katrinleinweber** [comment]
Also GitHub, I would suggest. [rstudio/cheatsheets](https://github.com/rstudio/cheatsheets/) & [tidyverse/tidyr](https://github.com/tidyverse/tidyr/tree/273a8b727ddc90ab1caa6e6aafc3c8c068a06095/vignettes) also include Keynote files, to facilitate easy PRs to those *plus* the final PNGs.

**Comment by cjlortie** [comment]
in this episode, what about providing a link to the RStudio public facing cheatsheets for the new learners. https://rstudio.com/resources/cheatsheets/ When you see them all, it is pretty great. Episode currently links directly to the pdf and asks to download so users cannot see them (and get inspired :) ).

**Comment by Teebusch** [comment]
> in this episode, what about providing a link to the RStudio public facing cheatsheets for the new learners. https://rstudio.com/resources/cheatsheets/ When you see them all, it is pretty great. Episode currently links directly to the pdf and asks to download so users cannot see them (and get inspired :) ).

@cjlortie This suggestion is not related to the original one (which is about moving from`gather`/`spread` to `pivot_`). It would be better to make a separate issue for it. Anyways, I think pointing out that cheatsheets are accessible from RStudio's help menu would be a good option.

@ab604 Do you think you could commit the files or add them as an attachment to this issue? I can do the editing/converting and uploading for you if you don't have the time. Illustrator would be fine. SVG is probably better in general, because it's a more open format than AI (same goes for Keynote, which is Apple specific).

**Comment by Teebusch** [comment]
https://github.com/gadenbuie/tidyexplain
This could be useful for remaking the figures

**Comment by fmichonneau** [comment]
updated in #809
