### ISSUE TITLE
topic for the repository

### ISSUE THREAD

**Issue by dpshelio** [datacarpentry/R-ecology-lesson#581]
Please, consider adding a `lesson` topic to the repository. To do so you can [follow the help about how to add topics to the repository](https://help.github.com/en/articles/classifying-your-repository-with-topics). Check out the topics that the [Genomics R intro lesson](https://github.com/datacarpentry/genomics-r-intro) has gotten to add others that may be relevant to this lesson.

This will help people to know which repositories are lessons and also could be used to automate analysis of the repositories.

**Comment by fmichonneau** [comment]
Adding GitHub Topics is not within the scope of the GitHub permissions for Maintainers. We are coordinating an effort to standardize GitHub Topics across all our repositories. We are seeking input and feedback from Maintainers on the list of proposed topics. Please see the Request For Comments (RFC) in this GitHub issue: https://github.com/carpentries/maintainer-RFCs/issues/5
