### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dmontecino** [datacarpentry/R-ecology-lesson#582]
Hi...

Question related to this post https://datacarpentry.org/R-ecology-lesson/05-r-and-databases.html#creating_a_new_sqlite_database

what I do not quite get is that if we want to avoid handling large amounts of data, then why would I want to load the datasets (large .csv files) to create the db? 

I would like to know if I can just "call" the location of the dataset and create the db as a file. Is that possible. 

Best

**Comment by PeterSmyth12** [comment]
The aim is to avoid having to drag the complete contents of the large dataset into the R environment. data frames inflate the true size of the data anyway.

By creating the database file (and in SQLite it is just a file) with the data in it. We can send our queries either as SQL strings or via dplyr fucntions to the database engine which processes the query and returns the results. So the R environment only needs to accommodate the results, which might be a filter or an aggregation, both of which will typically be much smaller than the full dataset contents.

In larger environments the database and database engines could be in different machines to your R environment, a database server for example. In this case you are completely offloading all of the processing to a more capable server than your desktop and you only have to process the results.

**Comment by mondorescue** [comment]
@dmontecino I'm going to close this issue since @PeterSmyth12 has provided an excellent response to your inquiry. However, feel free to re-open this issue if you have more questions related to the response or to your original inquiry. Thanks.
