### ISSUE TITLE
In 03-dplyr.Rmd, difficult to see weight column changes in mutate portion of the lesson

### ISSUE THREAD

**Issue by taylorreiter** [datacarpentry/R-ecology-lesson#587]
During the section working with mutate:

```
surveys %>%
  mutate(weight_kg = weight / 1000,
         weight_lb = weight_kg * 2.2)
```
And
```
surveys %>%
  filter(!is.na(weight)) %>%
  mutate(weight_kg = weight / 1000) %>%
  head()
````

It is really difficult to see the `weight*` columns while teaching when we zoom RStudio screen to make larger text on the porjector, so only the first few columns are printed to the console. While teaching this workshop recently at UC Davis, we added a select command to enable to view how the `weight*` columns were changing:

```
surveys %>%
  filter(!is.na(weight)) %>%
  mutate(weight_kg = weight / 1000) %>%
  select(weight, weight_kg) %>%
  head()
```

**Comment by mondorescue** [comment]
@taylorreiter Great feedback. I think this is a great tip to include in the [instructor notes](https://github.com/datacarpentry/R-ecology-lesson/blob/master/instructor-notes.md). Would you be willing to make a pull request?

**Comment by abhijna** [comment]
Hello, could I give this a try as part of my instructor training checkout?

**Comment by fmichonneau** [comment]
@abhijna yes please! That would be great!
