### ISSUE TITLE
Discrepancy: suggested directories vs. workshop directories

### ISSUE THREAD

**Issue by nathantaitano** [datacarpentry/R-ecology-lesson#594]
In the "Before we start" section, the lesson begins by suggesting the use of `documents/` and `scripts/` subdirectories in addition to `data/` and `data_raw/`. However, the workshop itself doesn't apply this useful directory structure. It may be more consistent to create these two folders, and to give people practice orienting their scripts to run out of the `scripts/` subdirectory. An update would require file references to begin with `../` (with an explanation in the text and given by the instructor). I've attached a file of the proposed directory structure here.
<img width="780" alt="SuggestedDirStruc" src="https://user-images.githubusercontent.com/7685727/72133783-267a7980-3337-11ea-8ec7-90e8a426054c.png">

**Comment by Teebusch** [comment]
This is a useful directory structure for real projects, and the merits of this are discussed in the lesson text.
However, I'd say that a balance has to be struck between doing things the right way and overwhelming learners (novice programmers!). I think the way this is currently done is fine. Creating unused directories with similar names and storing the main script file in a subdirectory is asking for trouble.

**Comment by Teebusch** [comment]
Since i think there are very good reasons to keep this as it is and there has been no feedback from @nathantaitano or anyone else I'm closing this issue.
