### ISSUE TITLE
Lesson Contribution

### ISSUE THREAD

**Issue by sheraaronhurt** [datacarpentry/R-ecology-lesson#598]
This is being submitted on behalf of trainee for their lesson contribution. 

"The transparency determines the degree to which you can see through it and add transparency to graphics to customize the look of your charts or reveal details about an object that are otherwise hidden. In order to control the transparency of an object using the alpha function and set the properties to a scalar value in the range [0,1].A value of 0 means completely transparent, a value of 1 means completely opaque, and values between 0 and 1 are semitransparent."

**Comment by mondorescue** [comment]
Noted. Thanks!
