### ISSUE TITLE
Unfinished/Missing paragraph

### ISSUE THREAD

**Issue by DanielBrett** [datacarpentry/R-ecology-lesson#599]
There appears to be a missing description in the "Split-apply-combine data analysis and the summarize() function" section of the "Manipulating, analyzing and exporting data with tidyverse" section of the workshop.  The sentence is begun with "The summarize() function" and then is blank.  I suspect the rest of the description was lost.

Thanks,

Daniel Brett

**Comment by mondorescue** [comment]
**The summarize() function** text is the heading of the paragraphs that follow. It is correct. We might consider making it obvious that it is a heading and not an incomplete sentence by tinkering with the style format.

Thank you for your contribution.
