### ISSUE TITLE
Variable name issue in 04-visualization-ggplot2.Rmd - ggsave example

### ISSUE THREAD

**Issue by karlbenedict** [datacarpentry/R-ecology-lesson#602]
The `ggsave` example (lines 629-646) includes the following:

```
my_plot <- ggplot(data = yearly_sex_counts, 
                  mapping = aes(x = year, y = n, color = sex)) +
geom_line() +
facet_wrap(vars(species_id)) +
...
```

The creation of `yearly_sex_counts` earlier in the lesson (lines 385-386) is included as:

```
yearly_sex_counts <- surveys_complete %>%
  count(year, genus, sex)
```

The `ggsave` should reference `genus` instead of `species_id` as that is the defined variable name in the `yearly_sex_counts` data frame.

**Comment by mondorescue** [comment]
@karlbenedict thanks for catching this. PR #603 accepted. Closing this issue.
