### ISSUE TITLE
Evaluate impact of R 4.0.0 to the content of the lesson

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#608]
go through the lesson and evaluate how R 4.0.0 changes impact what we teach (among other things, it should simiplify the teaching of `stringsAsFactors`)

**Comment by cjlortie** [comment]
Great, yes, I just updated and was going to use this lesson shortly. in the 'starting with data' episode, the plot(surveys$sex) did not work for me becausenew R 4.0.0 build read in this vector character not factor.

**Comment by fmichonneau** [comment]
addressed with #663
