### ISSUE TITLE
Adding quotation marks

### ISSUE THREAD

**Issue by elizabethwilliams8** [datacarpentry/R-ecology-lesson#610]
As the final requirement of my checkout procedure, I am sending the following suggestion. In the Data Analysis and Visualization in R for Ecologists lesson, quotation marks are not used for packages called in the library() command. There is a closed issue suggesting that the authors pick either quotation marks or none, but apparently none were selected (see [here](https://github.com/datacarpentry/R-ecology-lesson/issues/543)). While quotation marks are not required, this is an example of non-standard evaluation (see [here](http://adv-r.had.co.nz/Computing-on-the-language.html#nse-downsides)). I recommend the authors consider adding quotation marks so that new users get in the habit of using them and avoid potential problems with non-standard evaluation.

**Comment by fmichonneau** [comment]
Thanks for this suggestion!
