### ISSUE TITLE
Adding error bars to data visualization

### ISSUE THREAD

**Issue by janahilsenroth** [datacarpentry/R-ecology-lesson#611]
The lesson could be updated to include the use of error bars. This would require two changes. 

(1) In the "manipulating data" section, this

surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight))

could be replaced with:
female_wgt <- surveys %>%
  filter(sex=="F" & !is.na(weight)) %>% 
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            sd_weight = sd(weight))

(2) In the "visualizing data" after plotting time series, you could add in a quick section on bar plots. We can use bar plots to compare discrete categorical data. 

ggplot(data=female_wgt, aes(x=species_id, y=mean_weight))+
  geom_bar(stat="identity")

Then we can add error bars to showcase the variability in those mean weights:
ggplot(data=female_wgt, aes(x=species_id, y=mean_weight))+
  geom_bar(stat="identity")+
  geom_errorbar(aes(ymin=mean_weight-sd_weight, 
   ymax=mean_weight+sd_weight))

Error bars are critical to most of our figures as ecologists. I also think this emphasize the point that we build plots in an iterative process using ggplot.

**Comment by mondorescue** [comment]
@janahilsenroth I agree. Error bars are important and almost necessary for most charts. Would you be willing to submit a **pull request** on this issue?

**Comment by tobyhodges** [comment]
Thanks both for contributing to this discussion. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As this issue relates to content in a version of the lesson before that update took place, I will close it. Please open a new issue if you believe that some or all of the changes being discussed here are remain relevant to the redesigned lesson, linking to this thread where appropriate.
