### ISSUE TITLE
No extras tab on navigation bar, hard to find instructor notes

### ISSUE THREAD

**Issue by TheoAcker12** [datacarpentry/R-ecology-lesson#615]
The format for this lesson does not include an Extras dropdown on the top navigation bar like other lessons, and I cannot see any other way to access instructor notes from within the lesson. The only place I can find the notes is in the table with all the lessons on [the overall curriculum page](https://datacarpentry.org/lessons/#ecology-workshop).

**Comment by mondorescue** [comment]
@TheoAcker12 Thank you for pointing this out. The maintainer team will look into adding menu items for instructor notes and references similar to the other lessons.
