### ISSUE TITLE
long vs wide format for ggplot

### ISSUE THREAD

**Issue by SichongP** [datacarpentry/R-ecology-lesson#626]
In Visualizing Data part of the lesson, it reads:

> ggplot2 functions like data in the ‘long’ format, i.e., a column for every dimension, and a row for every observation.

Shouldn't it be 'wide' format? Long format is where all variables are stacked in a single column.

**Comment by fmichonneau** [comment]
ggplot2 does like data in the long format (for instance all the levels for a treatment should be in the same column) but I agree that the statement "a column for every dimension" might be misleading. Would you have a suggestion to improve the wording here?

**Comment by kaijagahm** [comment]
I've heard long format described as "every column is a variable; every row is an observation" before. Would that work? If so, I can open a PR.

**Comment by tobyhodges** [comment]
Thanks everyone for contributing to this discussion. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As this issue relates to content in a version of the lesson before that update took place, I will close it. Please open a new issue if you believe that some or all of the changes being discussed here are remain relevant to the redesigned lesson, linking to this thread where appropriate.
