### ISSUE TITLE
Resolution to issues of axes text not appearing when plotting with ggplot2

### ISSUE THREAD

**Issue by rachellombardi** [datacarpentry/R-ecology-lesson#627]
With teaching a recent workshop, we came across an issue where several individuals with old Macs could not get their axes text to show up when starting the ggplot2 lesson (no error was outputted, the plot axes just never showed up).  Our workshop coordinator mentioned that they had previously encountered this issue and believe that it is due to R not being able to find the default Arial font. 

To resolve this issue of no axes text, there are two approaches: (long way) Go to Finder Search for "Font Book" and open it. Look for the Arial font and, if it is greyed out, turn it on. This eliminates the warning and enables R to produce the appropriate labels.

(short way) Add `+ theme(text = element_text(family = "serif"))` to the ggplot2 code. 

Perhaps we could either add a note to the lesson or to the Instructor Notes?

**Comment by mondorescue** [comment]
This would be good to add to the Instructor Notes. @rachellombardi would you be willing to add your tip to the [Instructor Notes](https://github.com/datacarpentry/R-ecology-lesson/blob/main/instructor-notes.md) markdown?
