### ISSUE TITLE
Resolution to issue of plot(as.factor(surveys$sex)) not showing axes

### ISSUE THREAD

**Issue by rachellombardi** [datacarpentry/R-ecology-lesson#628]
With teaching a recent workshop, we came across an issue where several individuals with old Macs could not get their axes labels to show up when calling the plot() function (no error was outputted, the plot axes just never showed up).  Our workshop coordinator mentioned that they had previously encountered this issue and believe that it is due to R not being able to find the default Arial font. 

To resolve this issue of no axes text: Go to Finder Search for "Font Book" and open it. Look for the Arial font and, if it is greyed out, turn it on. This eliminates the warning and enables R to produce the appropriate labels.

Alternatively, we had success with this issue when plotting with ggplot2 by specifying a specific font type using theme. I'm not sure if there is an equivalent to plot(), but if there is, that could be a shorter workaround. 

Perhaps we could add a note to the Instructor Notes for how to resolve this if it comes up?

**Comment by mondorescue** [comment]
@rachellombardi would you be willing to also add this to the Instructor Notes?
