### ISSUE TITLE
Typo in "Intro to R"

### ISSUE THREAD

**Issue by marklcrowe** [datacarpentry/R-ecology-lesson#631]
Hi, I think there might be a typo in the Functions and their arguments section of Intro to R. The code example has 'ten <- sqrt(weight_kg)', but the explanatory text says 'Here, the value of ten is given to the sqrt() function, the sqrt() function calculates the square root, and returns the value which is then assigned to the object weight_kg'. 

I believe that the code for that explanatory text should be 'weight_kg <- sqrt(ten)'.

**Comment by fmichonneau** [comment]
Thank you so much for spotting this typo.
