### ISSUE TITLE
Checkout Lesson Contribution - Improving the transition from Base R to the `tidiverse`

### ISSUE THREAD

**Issue by camilavargasp** [datacarpentry/R-ecology-lesson#645]
I suggest explaining a little further about the transition from Base R to the `tidiverse`. Even though the lesson mentions 3 good issues that the `tidyverse` addresses. I think that as stated in the lesson is still confusing for learners to understand this transition.
I suggest two things in the introduction to Manipulating data section.
1. State that the tidyverse helps in the legibility of the code. This means that the code is easier to read and therefore easier to find errors or improvements to your code. This also helps with transparency and reproducibility. To make this point clear, at the end of the section I would add an exercise comparing code with base R and the `tidyverse`.
2. Along the same line, I suggest mentioning that the reason for switching from `read.csv` to `read_csv` is that `read_csv` is much faster for large csv files.

I think that small conceptual details make a big difference when learning any programming language.

**Comment by fmichonneau** [comment]
addressed with #663
