### ISSUE TITLE
code handout download link not working

### ISSUE THREAD

**Issue by Teebusch** [datacarpentry/R-ecology-lesson#662]
Since the CI fix (#652) the download link for the code handout has stopped working. The link points to [https://datacarpentry.org/R-ecology-lesson/code-handout.R](https://datacarpentry.org/R-ecology-lesson/code-handout.R), but the file doesn't seem to exist there. Both the link in the navbar and in the lesson do not work.

**Comment by fmichonneau** [comment]
Thanks for bringing this up, I think it's working now :tada:
