### ISSUE TITLE
Change site template to Distill?

### ISSUE THREAD

**Issue by Teebusch** [datacarpentry/R-ecology-lesson#668]
The current theme has some issues and I'm wondering whether it would be worthwhile to switch to a [Distill for RMarkdown website](https://rstudio.github.io/distill/)

Problems with the current theme:

- it uses Bootstrap 3, which has been discontinued quite a while ago. An upgrade to Bootstrap 4 [is not likely to happen anytime soon](https://github.com/rstudio/rmarkdown/issues/1260)
- screenreaders have issues with the heading (#612)
- The responsive navbar doesn't work properly (#614)
- There are some issues with typography and layout that I would summarize as "it looks rather messy"

Advantages of Distill:

- much cleaner, more pleasant layout and typography
- allows footnotes and asides (note in margins) and some other things.
- automatically links to function documentation in code segments
- stable but under active development 
- require little additional configuration for CI (building / deploying), as far as I can tell
- showcase a great feature of R - building pretty websites/blogs easily

Anticipated issues with switching to Distill:

- Build / deployment process would have to be updated
- Potential issues with custom RMarkdown `build_site()` hooks, in particular the questions and answers div's. ~~However, maybe [this package](https://github.com/ijlyttle/codefolder) solves this.~~  

I'd be happy to look into this and make a PR. I'd probably need some help with updating the build process and GH actions, though. Any thoughts or objections to this, @datacarpentry/r-ecology-lesson-maintainers ?

**Comment by fmichonneau** [comment]
Thanks for this suggestion @Teebusch. We (well... mostly @zkamvar) are currently working on a new lesson template. It's still a few months out but it's probably best to not invest time in addressing issues with this template given the work that is being put into creating a general solution that will work well for all our lessons.

**Comment by Teebusch** [comment]
I see! Well, in my enthusiasm for Distill I already gave it a try. 😅 
[I've deployed it on GH pages of my fork of the repository](https://teebusch.github.io/R-ecology-lesson/)

There are some things left to do, but I managed to do the worst part (getting it to deploy). Maybe a couple of hours of work.

Would you consider reviewing / merging a PR for this once it is done, even with the new template around the corner?
I find it more motivating to work on a "pretty" document like this, and in the process i can clean the .Rmd's a bit, so the switch to the new template will hopefully be smoother.

**Comment by zkamvar** [comment]
My two cents on this: 

This lesson in particular is a bit divergent from the other Carpentries lessons in that it does not structurally conform to the standard template (e.g. challenge and solution blocks are formatted differently) for historical reasons.

At the moment, the template I'm working on should allow for regular Rmarkdown documents to be rendered in the Carpentries style with no problems. I have a mostly automated conversion system in place that will ease the transition from the old template to the new template, but it will take some extra work to convert this template (difficulty level: low to moderate).

I also see the following factors that could influence how this moves forward:

1. The time needed to convert the current state of the lesson may very well be the same amount of time needed to convert the distill version
2. The accessibility is improved with the distill lesson
3. The instructors and learners of this lesson will be going through not one but two major changes to the the layout of the lesson if distill is implemented
4. Supporting a new template structure may require extra time and effort for the maintainers given that distill is a newcomer on the web template field. (n.b. while this point is also true for the coming lesson template, we are designing it such that any fixes can be done in a centralized location and updated seamlessly)

**Comment by Teebusch** [comment]
Thank you @zkamvar !

To me your 3rd point is the most compelling argument for *not* moving to Distill. People rely on the lesson and too frequent layout change may not be appreciated. On the other side, the accessibility and legibility improves quite a bit with Distill. Personally, I think the Distill layout is similar enough to the current one for this not to be an issue, and the benefits outweigh the cost, but I'm open to other opinions!

**About points 1 and 4:**
Distill ran pretty much out of the box with the old Rmd files. The only significant *required* changes to the Rmd's were the objective and challenge blocks. These were formatted as comments within code blocks and I changed them all to [custom Rmd blocks](https://desiree.rbind.io/post/2019/making-tip-boxes-with-bookdown-and-rmarkdown/), (using `:::`), which is the preferred way to do this anyway. This actually improves the legibility of the raw Rmd, because code chunks appear as regular code chunks in the Editor, and (without knowing your template system), I suspect that the updated blocks will be easier to convert (re point 1). That being said, we can use the new files with custom blocks without using distill.

There are some other changes required to move auxiliary information where it should be (code of conduct, instructor notes, ...), but I've implemented most of these already and am willing to put in the rest of the work.

**Comment by zkamvar** [comment]
> The only significant _required_ changes to the Rmd's were the objective and challenge blocks. These were formatted as comments within code blocks and I changed them all to [custom Rmd blocks](https://desiree.rbind.io/post/2019/making-tip-boxes-with-bookdown-and-rmarkdown/), (using `:::`), which is the preferred way to do this anyway.

How _interesting_! This was one of the three potential solutions to the special block quote conundrum (there are so many people that get "Unexpected > > " warnings from Jekyll). **If you are interested, your input on the official survey would be greatly appreciated (expected time: 15-30 minutes): https://zkamvar.github.io/glowing-chainsaw**

Given that, I suspect it will smooth over the issue in point 1, but point 4 still stands as a barrier since the responsibility would lie with the maintainers.

All that said, I'm glad we both are thinking along similar lines :)

**Comment by Teebusch** [comment]
I did the survey. I have a clear preference for fenced divs.

> Given that, I suspect it will smooth over the issue in point 1, but point 4 still stands as a barrier since the responsibility would lie with the maintainers.

of which I am one 😎 
I suspect that once it's up and runnning, the maintenance is the same as now. And I'd be happy to get it up and running.  But it will still require some work from the others to review pull request etc., so there's no point in doing it if it's not an unanimous decision.

**Comment by zkamvar** [comment]
> I did the survey. I have a clear preference for fenced divs.

Thank you for taking the time to give your input! I had a feeling that would be the case :smile_cat:

**Comment by Teebusch** [comment]
I will close this issue. I assume it's best to save our energy for transitioning to the new official tmeplate. :)
