### ISSUE TITLE
Small edit to comment in Indexing and subsetting data frames

### ISSUE THREAD

**Issue by wdahdul** [datacarpentry/R-ecology-lesson#673]
In the example for subsetting data frames by calling their column names directly, the second row has comment “#Result is a vector”:
```
surveys["species_id"]       # Result is a data.frame
surveys[, "species_id"]     # Result is a vector
surveys[["species_id"]]     # Result is a vector
surveys$species_id          # Result is a vector
```
 I think the comment should be changed to "#Result is a data.frame", as str() shows the following:
```
> str(surveys[, "species_id"])
tibble [34,786 × 1] (S3: tbl_df/tbl/data.frame)
 $ species_id: chr [1:34786] "NL" "NL" "NL" "NL" ... 
```

**Comment by mondorescue** [comment]
You are correct. Since we are in **tidyverse**, importing the data with `read_csv()` gives us a tibble. Therefore, `surveys[, "species_id"]` does return a data frame instead of a vector.

Would you be willing to put in a Pull Request?

**Comment by PaulaNietoG** [comment]
Hello, as I believe this has not been edited yet, I'd be happy to create the pull request and follow @wdahdul 's suggestion myself.

**Comment by wdahdul** [comment]
@PaulaNietoG Yes, please create the pull request. Thank you!

**Comment by PaulaNietoG** [comment]
Done!
