### ISSUE TITLE
Updating gather() and spread() to pivot_longer() and pivot_wider()

### ISSUE THREAD

**Issue by lsw5077** [datacarpentry/R-ecology-lesson#676]
This issue refers to the Manipulating data/Reshaping with gather and spread section of the R-ecology lesson. The Reshaping section teaches the data manipulation functions gather() and spread() for moving data between long format and wide format. In the latest version of the tidyverse, gather() has been replaced by pivot_longer() and spread() by pivot_wider(). 

Though the new functions are similar, pivot_longer() and pivot_wider() have new features and more descriptive argument names. It would probably help students to update the section to include the new functions. I recognize that this would a non-trivial update and would be happy to help with it if needed.

**Comment by Teebusch** [comment]
Thank you for the suggestion! I agree that it would be good to update the lesson. Would you be willing to make a pull request with the changes you suggest? I'd be happy to review it.

**Comment by anacost** [comment]
I believe this is mentioned in #580 
It would be a good improvement.

**Comment by lsw5077** [comment]
Thanks for the replies! I would be happy to draft an update.

**Comment by fmichonneau** [comment]
implemented in #809
