### ISSUE TITLE
formatting dates section

### ISSUE THREAD

**Issue by ramay** [datacarpentry/R-ecology-lesson#678]
In the formatting dates section, it will be useful to mention the other functions that be used to have a different date format like  `dmy()`, `ydm()` etc. 
As a lot of people have difficulty with dates and most dates are not stored in separate column could be worth showing an example with `as.date()` function.

**Comment by Teebusch** [comment]
Thank you for the suggestion @ramay! 

I think a note like this could be useful. Maybe something along the lines of 

> lubridate has many useful functions,  to extract dates from and to different string representations, convert between timezones, calculate time differences and more. See the documentation or the [lubridate cheat sheet](https://github.com/rstudio/cheatsheets/raw/master/lubridate.pdf) for an overview.

Would you be willing to make a pull request with your suggested changes?

This would also be a good place to remind learners that the cheat sheets can be accessed through the help menu (related to #679)

**Comment by Teebusch** [comment]
related to #606
