### ISSUE TITLE
Missing line of code in solution code chunk (Episode 2)

### ISSUE THREAD

**Issue by kevinrue** [datacarpentry/R-ecology-lesson#687]
The following line should be added as part of the solution at https://github.com/datacarpentry/R-ecology-lesson/blob/636df05ed64929dcf8595883eebe5fa947722287/02-starting-with-data.Rmd#L436 to match the challenge.

```r
surveys$taxa <- factor(surveys$taxa)
```

I'm happy to submit a PR.

**Comment by fmichonneau** [comment]
> I'm happy to submit a PR.

That would be great! Thank you
