### ISSUE TITLE
Difference in syntax highlighting for comments starting with # and ##

### ISSUE THREAD

**Issue by Bisaloo** [datacarpentry/R-ecology-lesson#695]
It looks like comments are not recognized by the syntax highlighting parser when they start with `##`. Example from 

https://datacarpentry.org/R-ecology-lesson/01-intro-to-r.html

![image](https://user-images.githubusercontent.com/10783929/111986287-0c792100-8b0e-11eb-9535-25ee8ef709b2.png)

However, when I knit this page locally, I get two different colours:

![image](https://user-images.githubusercontent.com/10783929/111987041-fa4bb280-8b0e-11eb-8a54-9e7c1af0bae3.png)

Is it intended?

**Comment by mondorescue** [comment]
@Bisaloo The web site is rendered with the pygment syntax highlighter (result: your first screenshot). If you don't specify that when you are knitting it, then you'll get the default color scheme, which is the second screenshot.

**Comment by Bisaloo** [comment]
Thanks for the explanation about the different result locally and on the web page!

The main question was mainly about the fact that `# comment` and `## comment` produce different colours, as shown in the two screenshots.

**Comment by fmichonneau** [comment]
Thanks for the report @Bisaloo! 

I don't think it comes from us because we don't modify the highlighting, so might be it's worth reporting upstream?

**Comment by Bisaloo** [comment]
I thought about it but I cannot reproduce with a simple Rmd file. Maybe I'm going to far upstream?

````r
rmd_test <- tempfile(fileext = ".Rmd")
png_output <- tempfile(fileext = ".png")

write(
'---
title: "Untitled"
output: html_document
---

```{r}
# test comment
## test comment
```
',
rmd_test)

# Capture and display the resulting HTML file
webshot::rmdshot(rmd_test, png_output)

magick::image_read(png_output)
````

![image](https://user-images.githubusercontent.com/10783929/113737815-a809b480-96fe-11eb-875f-922a91b3fb60.png)

**Comment by fmichonneau** [comment]
It looks like the bug was fixed upstream, as the latest build shows the comments as expected:

![Screenshot from 2021-04-06 16-53-22](https://user-images.githubusercontent.com/5502922/113777139-ad640080-96f8-11eb-813a-7dd695afff7c.png)
