### ISSUE TITLE
Lesson Contribution - Download Data Error

### ISSUE THREAD

**Issue by Talishask** [datacarpentry/R-ecology-lesson#697]
I'm a member of The Carpentries staff and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

---

I noticed that the name of the data file has changed and does not work as written in the lesson plan. The file is called "combined.csv."

Thus, in "Downloading Data" the code should read:

```
 download.file(url = "https://ndownloader.figshare.com/files/2292169",
              destfile = "combined.csv")
```

And in the subsequent "Reading the data into R" section, the line of code for reading in the csv should be:

`surveys <- read_csv("combined.csv")`

By making these changes, I was able to read in the data without getting error messages.

**Comment by mondorescue** [comment]
@Talishask thanks. Their contribution has been noted. Similar issues were reported, and most of reporters were getting errors because they skipped the "Before We Start" section and not have the right folders. I'll close this issue now.
