### ISSUE TITLE
Editing R & SQl lessons

### ISSUE THREAD

**Issue by lwasser** [datacarpentry/R-ecology-lesson#7]
hi @emhart and @fmichonneau . I am going through the SQL lesson now. I have some suggestions to clean things up a bit and will test things this week. For example i think we need to close the connection each time we open it. I have some other ideas as well - all quite minor.

How would you prefer we move forward with editing this lesson and the SQL one? Should I PR on this repo, and suggest changes that way?

Thanks Ted for all of your work on this lesson! it's looking great.
Whatever you guys prefer, i'm happy to do.
leah :)

**Comment by emhart** [comment]
Why do you need to close the connection every time?

**Comment by lwasser** [comment]
i may misunderstand this but don't you have to close the connection after opening it? so after section ONE where they import data from the portal db, you'd close the connection?

Then you open a new connection next that is to a NEW db that they create - you'd close that when you're done with it as well? Isn't that good practice?

**Comment by lwasser** [comment]
with H5 files if you leave them open sometimes you get issues when you try to use them in other programs. i just assumed DB connections are similar.

**Comment by emhart** [comment]
I don't think you need to.  Maybe good practice when you're done with the connection to close it.  But I don't close my connections most of the time.   Which isn't to say that what I do day in day out constitutes best practices :smiling_imp:   But I'm not answering your question, I think make changes and send a PR and we can comment on the PR.  Do you close the connection everytime in the python lesson?

**Comment by fmichonneau** [comment]
Hi @lwasser,

My understanding if that one needs to close connections when the script is done with all the queries to the database that are required, and you are ready to use the data in R. Closing the connection frees up resources (including memory, according to the help file).

I think we put a good emphasis on closing connection in the lesson as it stands, but if you feel we should talk about it more, or if you have other suggestions, we'll take your PR :)

**Comment by fmichonneau** [comment]
We're in the process of updating this lesson to use dplyr to interact with the database, and dplyr takes care of managing the connection for the user, so I'm going to close this issue.
