### ISSUE TITLE
small code issue in Instructor Notes re required packages

### ISSUE THREAD

**Issue by alicejohnstone** [datacarpentry/R-ecology-lesson#701]
In the Instructor notes section "Required packages" for learner issues with tidyverse package installation it suggests a workaround as individual package installation, however the code is missing the character vector requirement so could cause confusion for learners if it is accidently provided with this code as it will create errors if used as-is. 
Currently:

`install.packages("readr", "lubridate", "dplyr", "tidyr", "ggplot2", "dbplyr")`

it should show as:

`install.packages(c("readr", "lubridate", "dplyr", "tidyr", "ggplot2", "dbplyr"))`

**Comment by mondorescue** [comment]
@alicejohnstone Thanks for catching this. Would you be interested in doing a PR with the fix?
