### ISSUE TITLE
error in write_csv command lesson 3 dplyr

### ISSUE THREAD

**Issue by rjstevick** [datacarpentry/R-ecology-lesson#702]
https://github.com/datacarpentry/R-ecology-lesson/blob/3476ca360f89c3b45f61cfce79febf8949578018/03-dplyr.Rmd#L765-L772

At the end of Lesson 3 dplyr, the `write_csv()` command accepts the file name under argument `path`, not `file`.
This is especially confusing, since `write.csv` accepts the file name as `file`.

When the code is run as written, the following error is generated:
`Error in write_csv(surveys_complete, file = "data/surveys_complete.csv") : 
  unused argument (file = "data/surveys_complete.csv")`

**Suggestion:**
Change lines 766 and 771 to
`write_csv(surveys_complete, path = "data/surveys_complete.csv")`

**Comment by mondorescue** [comment]
@rjstevick What version of **readr** are you using? The [write_csv documentation](https://readr.tidyverse.org/reference/write_delim.html) states that the `path` parameter is deprecated.

**Comment by rjstevick** [comment]
@mondorescue 
I'm terribly sorry, I should have checked that before submitting... Looks like I have readr v1.3.1, and `file` is used as of v1.4.0. I've updated all my packages to use for my next lesson!

> write_csv(surveys_complete, path = "data/surveys_complete.csv")
Warning message:
The `path` argument of `write_csv()` is deprecated as of readr 1.4.0.
Please use the `file` argument instead.
