### ISSUE TITLE
Change "Here" links to Accessible format

### ISSUE THREAD

**Issue by jsgro** [datacarpentry/R-ecology-lesson#707]
**"Here" links** are not recommended in order to make text or buttons more "Accessible" (see *e.g.* [accessibility-posters-set.pdf](https://github.com/UKHomeOffice/posters/blob/master/accessibility/dos-donts/posters_en-UK/accessibility-posters-set.pdf) shown in [Instructor training lesson](https://carpentries.github.io/instructor-training/).) 

I noted the following 3 links that could benefit changing to a better format with minimal changes with the suggestions shown below.

On the Home page tag: https://datacarpentry.org/R-ecology-lesson/index.html#Update_R_and_RStudio the following phrase 

 * "Note: It is not necessary to remove old versions of R from your system, but if you wish to do so you can [check here](https://cran.r-project.org/bin/windows/base/rw-FAQ.html#How-do-I-UNinstall-R_003f)." could be written as 
 * "Note: It is not necessary to remove old versions of R from your system, but if you wish to do so you can check [How do I UNinstall R?](https://cran.r-project.org/bin/windows/base/rw-FAQ.html#How-do-I-UNinstall-R_003f)."

On page tag: https://datacarpentry.org/R-ecology-lesson/00-before-we-start.html#Asking_for_help the phrase:

* "There are also some topic-specific mailing lists (GIS, phylogenetics, etc…), the complete list is [here](https://www.r-project.org/mail.html)." could be written as:
* "There are also some topic-specific mailing lists (GIS, phylogenetics, etc…), the complete list is on [R Mailing Lists](https://www.r-project.org/mail.html)."

On page tag: https://datacarpentry.org/R-ecology-lesson/instructor-notes.html#R_Version the phrase 

* "you can read more about this [here](https://developer.r-project.org/Blog/public/2020/02/16/stringsasfactors/index.html))" could be rewritten as: 
* "you can read more about this here: [stringsAsFactors](https://developer.r-project.org/Blog/public/2020/02/16/stringsasfactors/index.html).)"

As a side note, while these changes would benefit "accessibility" they are also typically suggested in the case of search engine optimization (SEO.)

**Comment by Teebusch** [comment]
Thank you for this suggestion! This is indeed and important issue! I've changed the text (took the liberty to deviate from your suggestions a bit.)
