### ISSUE TITLE
add 'instructor notes' for this set of lessons

### ISSUE THREAD

**Issue by k8hertweck** [datacarpentry/R-ecology-lesson#71]

**Comment by ErinBecker** [comment]
+ 1 

I'm working on helping direct instructor attention towards fixing up/contributing to instructor notes. Currently don't have a link to provide for instructor notes for this lesson. Please add - even a blank document.

**Comment by aurielfournier** [comment]
Its a work in progress but here is what we have so far. 

https://github.com/datacarpentry/R-ecology-lesson/blob/instructor_notes/instructor_notes.md

**Comment by ErinBecker** [comment]
Thanks Auriel!

**Comment by k8hertweck** [comment]
Thanks for getting started on this! I'll be working on targeting important points to include in instructor guides (based on common questions received from instructors) after the Bug BBQ.

**Comment by ErinBecker** [comment]
@k8hertweck The guidelines the mentoring and maintainers groups have come up with so far are [here](https://github.com/datacarpentry/datacarpentry.github.io/blob/erinbecker-instructor-notes/pages/guidelines_instructor_notes.md). 

Since many of the DC instructor notes are blank or very sparse at this point, Tracy has suggested transforming these guidelines into a template to help keep formats similar across lessons as notes get added. Hopefully I'll have this up and ready for people to use before the Bug BBQ.

**Comment by wrightaprilm** [comment]
Sorry, ignore that! Wrong issue window.

**Comment by k8hertweck** [comment]
A template would be awesome! I'm hesitant to make this a priority during the Bug BBQ, though, as we have a bit of work left to do in the DC lesson content.

**Comment by fmichonneau** [comment]
hi all,

I just taught the lesson and found many places where it could be improved. I have started the process of incorporating these changes, but there is more to do.

I agree with @k8hertweck that it might be difficult to have this done during the Bug BBQ as the instructor notes should be written by instructors who have experience teaching the lesson.

**Comment by ErinBecker** [comment]
@k8hertweck @fmichonneau I agree - there's a lot of other important work to be done during the Bug BBQ. @gvwilson suggested that, if we want a big push on instructor notes, it may be good to try to time that shortly after the Bug BBQ, to capitalize on our existing community momentum. I meant that hopefully I'll have them ready by the time of the Bug BBQ so we can start directing attention to the instructor notes *shortly after* the BBQ.

**Comment by tracykteal** [comment]
Agree that we can hold off on this until after the lesson release.
