### ISSUE TITLE
read_csv vs read.csv

### ISSUE THREAD

**Issue by jpgannon** [datacarpentry/R-ecology-lesson#710]
When introducing read_csv() I think it could be helpful to mention that read.csv() exists and is different. I often have students confuse the two and then have issues later, especially when they have dates in their data.

**Comment by vanilink** [comment]
I agree that there may be confusion for new learners with regards to read_csv() and read.csv(). In fact this and related issue s have been discussed multiple times before, e. g. #268 #335 #420 #480 #553 #555 #663 #682 (side note, you can search for previous issues by removing the _is:open_ tag from the issues filters). 
From my understanding, as of #663 the whole lesson switched over to the tidyverse function readr:_read_csv() However, I agree with @jpgannon and others that there may still be possible confusion, both on the instructor and learner side, especially when considering coding outside of the carpentries. This may further be a good opportunity to alert learners new to coding that exact spelling is extremely crucial (another opportunity is the before-mentioned "View()" vs "view()" debate). 
Here is the current wordage of the "Starting with data" episode:

> Reading the data into R
> The file has now been downloaded to the destination you specified, but R has not yet loaded the data from the file into memory. To do this, we can use the read_csv() function from the tidyverse package.
> 
> Packages in R are basically sets of additional functions that let you do more stuff. The functions we’ve been using so far, like round(), sqrt(), or c(), come built into R; packages give you access to additional functions. Before you use a package for the first time you need to install it on your machine, and then you should import it in every subsequent R session when you need it.

I suggest to add some wording for clarification and to introduce the term "base R", such as:

> Reading the data into R
> The file has now been downloaded to the destination you specified, but R has not yet loaded the data from the file into memory. To do this, we can use the read_csv() function from the tidyverse package.
> 
> Packages in R are basically sets of additional functions that let you do more stuff. The functions we’ve been using so far, like round(), sqrt(), or c(), come built into R; packages give you access to additional functions **beyond base R. The corresponding function to read_csv() from the tidyverse package is read.csv() from base R. We don't have time to cover their differences but notice that the exact spelling determines which function is used.** Before you use a package for the first time you need to install it on your machine, and then you should import it in every subsequent R session when you need it.

**Comment by Teebusch** [comment]
Hi @jpgannon @vanilink 
I've made a PR with the changes suggested by @vanilink , #736 
Would you kindly have a look if you agree with them?

**Comment by fmichonneau** [comment]
sorry I merged the PR before seeing this message. Please let us know if you have any feedback on the changes made by @Teebusch, @jpgannon and @vanilink

**Comment by jpgannon** [comment]
Looks good to me! Thanks!
JP

**Comment by vanilink** [comment]
Thank you so much @jpgannon @Teebusch @fmichonneau ! What a smooth experience. I'm glad we could improve the clarity of the materials together. No more comments from my side :)
