### ISSUE TITLE
instructor-notes: necessary_packages.R link broken

### ISSUE THREAD

**Issue by andriizayac** [datacarpentry/R-ecology-lesson#713]
Hi, 
I believe the following pull request (https://github.com/datacarpentry/R-ecology-lesson/commit/c30ebf60493a46f370ce3e5aefb1467e5dac7538#diff-11a6537c35790c75760aae1b21a0a4c10209cb023b7543384da7f7c0ac96e8cb) integrated the `required_packages.R` script into the _instructors-notes.md_. The link from the course website to the list of necessary packages still exists though but is dead (https://github.com/datacarpentry/R-ecology-lesson/blob/main/needed_packages.R). Might be good to update the _instructor-notes.md_ either to revive the link or delete it altogether to avoid any confusion.

**Comment by Teebusch** [comment]
Thank you, @andriizayac! Well spotted!
