### ISSUE TITLE
Repetition in "Getting set up"

### ISSUE THREAD

**Issue by jkkishore85** [datacarpentry/R-ecology-lesson#739]
I found that introduction to the concepts "Working Directory" and “Projects” are repeating in the sections **Getting setup** and **Working directory**  in the episode 00-before-we-start.Rmd. I was wondering if these sections can be modified to avoid the confusion.

Just a suggestion.

**Comment by Teebusch** [comment]
Hi @jkkishore85, thank you for your suggestion! It sounds like a good idea. Would it be possible for you to make a pull request where you make the changes you'd suggest? It would be a great help!

(For reference, link to the episode: https://datacarpentry.org/R-ecology-lesson/00-before-we-start.html#Getting_set_up)

**Comment by tobyhodges** [comment]
Thanks both for contributing to this discussion. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As this issue relates to content in a version of the lesson before that update took place, I will close it. Please open a new issue if you believe that some or all of the changes being discussed here remain relevant to the redesigned lesson, linking to this thread where appropriate.
