### ISSUE TITLE
Define "bitstream"

### ISSUE THREAD

**Issue by sbreitbart** [datacarpentry/R-ecology-lesson#748]
Under the "Vectors and Data Types" challenge, the word "bitstream" is used. It'd be helpful if a short definition was included in parentheses next to it. I've never come across this word after years of learning R so I'd expect novices would be confused too.

**Comment by Teebusch** [comment]
Thank you for this suggestion @sbreitbart. I agree, that it could use a better explanation. This is the text in question:

> The other 4 atomic vector types are:
> 
> "logical" for TRUE and FALSE (the boolean data type)
> "integer" for integer numbers (e.g., 2L, the L indicates to R that it’s an integer)
> "complex" to represent complex numbers with real and imaginary parts (e.g., 1 + 4i) and that’s all we’re going to say about them
> "raw" for **bitstreams** that we won’t discuss further


<https://datacarpentry.org/R-ecology-lesson/01-intro-to-r.html#Challenge9> (right before the schalleng)

**Comment by arungapatchka** [comment]
Would this work as a definition: a bitstream is a binary sequence (1's and 0's) of digital data consisting of a string of bits?

**Comment by sbreitbart** [comment]
I think that's a great starting place- I'd suggest something that slowly introduces new information like, "a bitstream is a sequence of 1's and 0's (or, bits) and which is recognized as a form of digital data".

**Comment by helenmary** [comment]
Hi! I'd like to tackle this. Drawing on the Library of Congress digital collections glossary ([link](https://www.loc.gov/programs/digital-collections-management/about-this-program/glossary/)), what about moving in this direction?

- `"raw"` for bitstreams, sequences of 1's and 0's ("bits") that constitute digital data but may or may not make up a standalone file; we will not discuss these further here

**Comment by Teebusch** [comment]
Hmm, I'm wondering whether a rather advanced concept like this should really be explained in the lesson, esecially since it is of no use in the rest of the lesson. Could we just link to a definition like the one from the Library of Congress? 
Perhaps, add a definition to the [Carpentries glossary](https://glosario.carpentries.org/en/) and link to that?[ (link to Github project)](https://github.com/carpentries/glosario)

**Comment by fmichonneau** [comment]
> Perhaps, add a definition to the Carpentries glossary and link to that? (link to Github project)

I like this idea!

**Comment by tobyhodges** [comment]
Thanks everyone for contributing to this discussion. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As this issue relates to content in a version of the lesson before that update took place, I will close it. Please open a new issue if you believe that some or all of the changes being discussed here remain relevant to the redesigned lesson, linking to this thread where appropriate.
