### ISSUE TITLE
Replace dimension by variable in the file 04-visualization-ggplot2.Rmd 

### ISSUE THREAD

**Issue by spholmes** [datacarpentry/R-ecology-lesson#749]
Would it not better to use the word **variable** on line 59 in the file 04-visualization-ggplot2.Rmd

 to describe the columns as later on we use columns and not dimensions, this is to keep coherence throughout the lesson, dimensions can be confusing because in R the dimensions are the number of indices in the array.

**Comment by fmichonneau** [comment]
Thank you for the suggestion @spholmes!
