### ISSUE TITLE
Streamline bullets at end of "Before we start" episode

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/R-ecology-lesson#753]
The last two bullets on this page  (https://datacarpentry.org/R-ecology-lesson/00-before-we-start.html) both link to the same blog post (https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/).  I'd suggest having it just referenced once.

**Comment by Teebusch** [comment]
Well spotted! Thank you! I agree that this needs to be fixed.
