### ISSUE TITLE
Broken link in Intro to R episode

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/R-ecology-lesson#754]
The link from the word "differences" in the intro to R episode does not work.
See https://github.com/datacarpentry/R-ecology-lesson/blob/main/01-intro-to-r.Rmd#L55

**Comment by Teebusch** [comment]
Thank you, well spotted! There are a couple of other blog posts that describe the differences. I suppose we should try to find one that explains it well and use it instead.

**Comment by natforsdick** [comment]
Would this be a helpful link? It walks through some examples of the differences. https://renkun.me/2014/01/28/difference-between-assignment-operators-in-r/

**Comment by fmichonneau** [comment]
Thanks for the fix @natforsdick!

**Comment by Teebusch** [comment]
Thanks a lot, @natforsdick!
