### ISSUE TITLE
broken link on  R/SQL episode

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/R-ecology-lesson#757]
In the SQL databases and R episode (https://datacarpentry.org/R-ecology-lesson/05-r-and-databases.html) 
the link to the tidyverse join page is broken.  
See https://github.com/datacarpentry/R-ecology-lesson/blob/main/05-r-and-databases.Rmd#L349

**Comment by Teebusch** [comment]
Thank you! (and thank you for all your work here!) 
It looks like the page has moved and the now link is https://dplyr.tidyverse.org/reference/mutate-joins.html
