### ISSUE TITLE
Don't call things easy

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/R-ecology-lesson#759]
In the [SQL databases and R episode](https://datacarpentry.org/R-ecology-lesson/05-r-and-databases.html) we say that  "Creating a new SQLite database with dplyr is easy."  Calling things "easy" is contrary to the teaching methods used by The Carpentries where we do not want to assume a learner will find something easy.

**Comment by Teebusch** [comment]
Thank you, @maneesha. You are absolutely right. This needs to be fixed. Perhaps we can write something like "can be done with a single command" or "...one line of code", or remove this phrase completely. 

I had a look around and it seems like the words "easy" / "easier" are used 7 times in that chapter alone, and a few more times in the other chapters. Maybe we should try to purge the word from the whole lesson while we are at it?

**Comment by mobilegenome** [comment]
Hi @maneesha and @Teebusch, I think this an important point and I'd be happy to take over this task if you don't mind. 
Before I start, I just wanted to check that you haven't started working on it, so we avoid redundancy or stepping upon another toes :)

**Comment by Teebusch** [comment]
Hi @mobilegenome, you are definitely more than welcome to work on this!

**Comment by fmichonneau** [comment]
closed with #772
