### ISSUE TITLE
Output of read_csv()

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/R-ecology-lesson#761]
In the [Starting with data](https://datacarpentry.org/R-ecology-lesson/02-starting-with-data.html) episode, the lesson tells us that after calling `surveys <- read_csv("data_raw/portal_data_joined.csv")` we will get a message that says `Parsed with column specification` followed by the column name and data type. However in the example (and in my own work) the output header is just `Column specification`.  This should be clarified so learners don't think there is something wrong.

**Comment by Teebusch** [comment]
Thank you @maneesha, well spotted. I can replicate this on my machine (latest tidyverse package version, more or less)

The output I get is 
```r
surveys <- read_csv("data_raw/portal_data_joined.csv")
Rows: 34786 Columns: 13                                                                                                                                       
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (6): species_id, sex, genus, species, taxa, plot_type
dbl (7): record_id, month, day, year, plot_id, hindfoot_length, weight

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
```

This matches what we see in the lesson output and what you describe.
I think the sentence in the text is a leftover from a previous version of `read_csv()` (or from the time when the lesson still used `read.csv()` -- I'm not quite sure...)

Anyways, I think this sentence ("You will see the message Parsed with column specification, followed by each column name and its data type. ") can be removed without replacement.
