### ISSUE TITLE
Unanswered questions in "Starting with data" episode

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/R-ecology-lesson#763]
The [Starting with data](https://datacarpentry.org/R-ecology-lesson/02-starting-with-data.html) episode ends with these two questions but the questions are not answered for the learner.

> Why did these dates fail to parse? If you had to use these data for your analyses, how would you deal with this situation?

The second question may be more subjective.  It would help to have the first one answered here, to note that the dates refer to 31st day of 30-day months.

**Comment by Teebusch** [comment]
Thank you @maneesha. I've noticed this, too, and I think there should be an answer. Perhaps the second part of the question could be rephrased like  "Can you think of some ways to deal with this situation in a real analysis?" and the answer could give a few possible solutions without having to cover all possibilities.

There are a few other challenges with missing answers, by the way  Issue #718 and PR #724)

**Comment by fmichonneau** [comment]
closed with #782
