### ISSUE TITLE
Term 'tbl_df' is used without explanation

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/R-ecology-lesson#765]
In the [Manipulating data episode](https://datacarpentry.org/R-ecology-lesson/03-dplyr.html) it says

> You may also have noticed that the output from these calls doesn’t run off the screen anymore. It’s one of the advantages of tbl_df over data frame.

This is the first place the term `tbl_df` is used in this lesson, and it is not clear that this means tibble.

**Comment by Teebusch** [comment]
Thank you, @maneesha. This is a really good point. I think we can remove the entire sentence 

> "You` may also have noticed that the output from these calls doesn’t run off the screen anymore. It’s one of the advantages of tbl_df over data frame."

- Before we switched from `read.csv()` to `read_csv()` the imported data was a data frame. I think now it is a tibble right away, so there never should be any "running off the screen" in the first place. 
- [Earlier in the lesson,](https://datacarpentry.org/R-ecology-lesson/02-starting-with-data.html#What_are_data_frames) we say that tibble is a special type of data frame, but the difference doesn't matter for the lesson, so we won't discuss it. I think we can stick with that decision here. 
- I also don't think this comment is particularly useful to the learners.

**Comment by tobyhodges** [comment]
Thanks both for contributing to this discussion. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As this issue relates to content in a version of the lesson before that update took place, I will close it. Please open a new issue if you believe that some or all of the changes being discussed here remain relevant to the redesigned lesson, linking to this thread where appropriate.
