### ISSUE TITLE
add mention of ggThemeAssist in the plotting lesson?

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#77]
See: https://github.com/calligross/ggthemeassist

**Comment by aurielfournier** [comment]
My initial reaction to this is very mixed but this does seem to help bridge the difficulties of all the different theme arguments. I'm just not a big GUI fan, but it would help.

**Comment by Pakillo** [comment]
Perhaps it can be mentioned at the end ('More resources' links), together with [ggedit](https://cran.r-project.org/web/packages/ggedit/index.html).

I'm no big fan of these GUIs either, but in my (short) experience new users get very intimidated to modify themes based on `?theme` (shocked by element_text, element_rect, etc). And seeing that they can change appearance much easier interactively, helps a lot. And you get back the code that implements those changes, so not that bad...

I vote for linking to both packages in the end, and perhaps mentioning them in one sentence in the main text.

**Comment by anacost** [comment]
Both have been added to the tidyverse-first branch (ggThemeAssist and ggedit). (#400)
