### ISSUE TITLE
Use () when calling functions

### ISSUE THREAD

**Issue by orchid00** [datacarpentry/R-ecology-lesson#80]
I suggest to use parenthesis after function names, when cited in the text. This mainly to differentiate them from arguments.

**Comment by fmichonneau** [comment]
Yes! It's already listed as a formatting guideline in [CONTRIBUTING](https://github.com/datacarpentry/R-ecology-lesson/blob/gh-pages/CONTRIBUTING.md#formatting-of-the-material). If you notice places where they are missing, please comment or send a PR. Thanks!

**Comment by orchid00** [comment]
Cool, thanks! I started, and i'll be sending pull requests. You can close this issue.
