### ISSUE TITLE
Colorblind friendly plotting

### ISSUE THREAD

**Issue by brownsarahm** [datacarpentry/R-ecology-lesson#814]
Colorblind learners cannot tell if their code works in the visualization episode.  it would be good to also teach how to change the pallete to a friendly one or at least also change the line style.

**Comment by phillybroadbent** [comment]
The RColorBrewer library has colourblind friendly palettes, which can be accessed from `display.brewer.all(colorblindFriendly=TRUE)` .  To improve accessiblity for colourblind users further, the `colourblindr` package provides colour palettes that are accessible to users with different types of colour blindness. This information could be added to the customization section of the lesson.

**Comment by tobyhodges** [comment]
Thanks both for contributing to this discussion. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As this issue relates to content in a version of the lesson before that update took place, I will close it. Colourblindness is addressed in the context of colour palettes in [the _Changing Scales_ section](https://datacarpentry.org/R-ecology-lesson/visualizing-ggplot.html#changing-scales) of the current content. Please open a new issue if you believe that further improvements could be made in this regard, linking to this thread where appropriate.
