### ISSUE TITLE
05-r-and-databases line 75 wording suggestion

### ISSUE THREAD

**Issue by CronicSloth** [datacarpentry/R-ecology-lesson#815]
Hey yall currently line 75 of the R ecology lesson says: 

The SQLite database is contained in a single file `portal_mammals.sqlite`
that you generated during
[the SQL lesson](https://datacarpentry.org/sql-ecology-lesson/00-sql-introduction/index.html).
If you don't have it, you can download it from Figshare into the `data_raw` subdirectory using: 

If I'm correct on my terminology, I think that the SQL lesson it is referring to is a part of the SQL Episode so it could be reworded as that. 

Also I'm pretty sure when I took this workshop at my institution, we covered R before we covered SQL and that seemed to work very well so this could be adjusted to read "that you will generate during" Or it could be changed to make it more universal to those putting on this lesson without doing the entire Ecology workshop by changing the wording to: "that is generated during." This way less participants might get confused or feel like they missed something if this lesson does not follow the SQL lesson

**Comment by tobyhodges** [comment]
Thanks @CronicSloth for opening this issue. I'm sorry it has taken so long to receive a response. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. One significant change is that the content on interacting with databases has been removed. As this issue relates that content, I will close it. Please open a new issue if you have suggestions for how the updated lesson could be improved.
