### ISSUE TITLE
Last line of Exploring Plots Ecology R lesson

### ISSUE THREAD

**Issue by ereverman** [datacarpentry/R-ecology-lesson#816]
The line:
```
ggsave("plot_combined.png", plot_combined, width = 10, dpi = 300)
```
seems to be missing height parameters and doesn't plot correctly.

Changing to:
```
ggsave("plot_combined.png", plot_combined, width = 15, height = 10, dpi = 300)
```

Fixes the issue

**Comment by tobyhodges** [comment]
Thanks @ereverman for opening this issue. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As your suggestion relates to content in a version of the lesson before that update took place, I will close it. Please open a new issue if you believe that the changes suggested here remain relevant to the redesigned lesson, linking to this thread where appropriate.
