### ISSUE TITLE
`src_dbi()` has been superseded/deprecated

### ISSUE THREAD

**Issue by Aariq** [datacarpentry/R-ecology-lesson#818]
https://github.com/datacarpentry/R-ecology-lesson/blob/ac8b94ee5d1a806a85280093a497cf433e08ba32/05-r-and-databases.Rmd#L110

According to the documentation `dbplyr::src_dbi()` is superseded and `dplyr::src_dbi()` is deprecated.  Looking at the `dbplyr` documentation, it looks like the recommended way to do this is with `DBI::dbListTables(mammals)`

**Comment by SichongP** [comment]
https://dbi.r-dbi.org/reference/dblisttables

**Comment by tobyhodges** [comment]
Thanks @Aariq for opening this issue. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. One significant change is that the content on interacting with databases has been removed. As this issue relates that content, I will close it. Please open a new issue if you have suggestions for how the updated content could be improved.
