### ISSUE TITLE
Bullets misformatted in episode 2

### ISSUE THREAD

**Issue by edbennett** [datacarpentry/R-ecology-lesson#824]
At the very bottom of the episode on _Starting With Data_, there is a paragraph containing a series of points separated by asterisks. This appears to be because the RMarkdown file is missing the blank line that should separate a bulleted list from surrounding paragraphs.

**Comment by DataNarrator** [comment]
I submitted a pull request #829 to improve markdown

**Comment by edbennett** [comment]
Note that I already opened #825 that would fix this issue (although GitHub didn't link it here)
