### ISSUE TITLE
Inconsistent spelling of `summarize`

### ISSUE THREAD

**Issue by edbennett** [datacarpentry/R-ecology-lesson#826]
For various reasons, R (or `dplyr`) permits both `summarize` and `summarise` to be used for summarising data. However currently almost of the lesson uses `summarize`, with just one section of episode 3 using `summarise`, with no explanation that this does the same thing.

This may confuse or at least distract learners. For example, they may think that R will automatically correct some or all minor spelling errors in function names, or worry that `summarise` will do something subtly different to `summarize`.

I would suggest that either this should be made consistent throughout, or an explanation should be added as to why this difference is allowed. For simplicity of teaching this lesson, I'd strongly prefer the first option.

**Comment by kiyab11** [comment]
If the switch between summarize and summarise becomes a distraction reguarding them being the same function override the variable with the one you are more comfortable using.  For examples,

summarize <- summarise
summarise <- summarize

Hope this helps.

**Comment by edbennett** [comment]
As I understand it, both already mean the same thing in R, so I don't think that that override would do anything. My issue isn't with the R language, but with the lesson being inconsistent.
