### ISSUE TITLE
`pivot_longer()` runs the same code for column selection twice

### ISSUE THREAD

**Issue by mikemahoney218** [datacarpentry/R-ecology-lesson#830]
Hi folks!

I believe the `pivot_longer()` section here should be using `:` to select columns, rather than `-plot_id`:

https://github.com/datacarpentry/R-ecology-lesson/blob/8e955fe543878ab51254a1c5857904c0ed0a6de9/03-dplyr.Rmd#L601-L608

Later in the lesson, the text says "we could have also used `-`", which makes me think this is an accident of copy and paste and the former should have used `:`:

https://github.com/datacarpentry/R-ecology-lesson/blob/8e955fe543878ab51254a1c5857904c0ed0a6de9/03-dplyr.Rmd#L616-L624

Happy to contribute a PR if this is unintentional.

**Comment by tobyhodges** [comment]
Thanks @mikemahoney218 for opening this issue. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As your suggestion relates to content in a version of the lesson before that update took place, I will close it. Please open a new issue if you have suggestions for how the new content could be improved.
