### ISSUE TITLE
Clarity suggestion in seeking help

### ISSUE THREAD

**Issue by BenMarmont** [datacarpentry/R-ecology-lesson#831]
The seeking help section says to type ?mean() when you want help or push f1 when hovering over the function. I suggest adding where you would type ?mean() for clarity.

I have modified the first sentence below:

If you need help with a specific function, let's say `mean()`, you can type
`?mean` in the console or press <kbd>F1</kbd> while your cursor is on the function name.
Alternatively, you could type '?mean() 'in the source editor to preserve the help command. If you are searching for help via the help tab in the file explorer pain don't include the leading question mark.

**Comment by tobyhodges** [comment]
Thanks @BenMarmont for opening this issue. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As your suggestion relates to content in a version of the lesson before that update took place, I will close it. Please open a new issue if you have suggestions for how the new content could be improved.
