### ISSUE TITLE
Fix typing errors in `before-we-start`

### ISSUE THREAD

**Issue by rodrigarc** [datacarpentry/R-ecology-lesson#838]
Hi, 

I was going through the lesson to find potential errors that could be fixed with the writing itself. I came across only a few, which shows how good this lesson is. I am creating the issue before forking anything to first check if they are worth changing or not. I had time to go only through one Rmarkdown in detail though.

1. File `00-before-we-start.Rmd'

    - Line 225, change verb form to infinitive: change `Later, when you start create more` to `Later, when you start to create more`
    - Line 290, add comma: change `by typing, copy-pasting or sent from the script editor` to `by typing, copy-pasting, or sent from the script editor`
    - Line 313, add preposition: `use the help panel to search help directly` to `use the help panel to search for help directly`
    - Line 325, move comma: change `to complete function's argument names, object, names and file names` to `to complete function's argument names, object names, and file names`
    - Line 363, add comma: change `In that case it might help to` to `In that case, it might help to`
    - Line 464, misspelled word: change `useful R packages and tipps` to `useful R packages and tips`

**Comment by tobyhodges** [comment]
Thanks @rodrigarc for opening this issue. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As your suggestion relates to content in a version of the lesson before that update took place, I will close it. Please open a new issue if you have suggestions for how the new content could be improved.
