### ISSUE TITLE
Making a suggestion to improve the website (hovering menu bar).

### ISSUE THREAD

**Issue by UtopianYoungChung** [datacarpentry/R-ecology-lesson#848]
As I followed through with the lesson, I kept navigating back to the top to find the menu at the top-left corner of the page.
I would suggest making a hovering menu bar for easier navigation through the lessons.

**Comment by zkamvar** [comment]
Hello, this is not something that the maintainers of this lesson have control over. There is a relevant issue in {varnish} about this, please follow there for updates: https://github.com/carpentries/varnish/issues/16
