### ISSUE TITLE
Using the word 'type' for executing code could be confusing

### ISSUE THREAD

**Issue by klbarnes20** [datacarpentry/R-ecology-lesson#851]
I'm a member of The Carpentries Core Team and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

-------------------------------------------------

In episode 2, starting with data,  at least a couple of times, the instructions for executing or running the code is 'type'. I think this could be confusing for someone who is new to programming. One particular line talks about 'typing' the code straight into the console to install packages.Does typing a code in the console run it? To avoid the confusion that might arise, I suggest using a more uniform language throughout the lesson.

**Comment by tobyhodges** [comment]
Thanks @klbarnes20 for opening this issue. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As the suggestion relates to content in a version of the lesson before that update took place, I will close it.
