### ISSUE TITLE
information about seeing the content of the data not accurate

### ISSUE THREAD

**Issue by bienflorencia** [datacarpentry/R-ecology-lesson#853]
In the section [Reading the data into R](https://datacarpentry.org/R-ecology-lesson/02-starting-with-data.html#reading-the-data-into-r) of the episode 'Starting with data', there is inaccurate information being shown.

The text says:
"We can see the contents of the first few lines of the data by typing its name: surveys. By default, this will show you as many rows and columns of the data as fit on your screen. If you wanted the first 50 rows, you could type print(surveys, n = 50)"

But, because it is a tibble, the object displays by default ten rows. I suggest the following text modification:

- "By default, this will show **10 rows and as many** columns of the data as fit on your screen".

I saw that this lesson was corrected before (#761), and I understand the confusion might come from changing from `read.csv()` to `read_csv()`. However, the information is not entirely accurate at the moment.

I also believe this part is unnecessary or could be improved.

"If you wanted the first 50 rows, you could type print(surveys, n = 50)"

**Comment by tobyhodges** [comment]
Thanks @bienflorencia for opening this issue. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As your suggestion relates to content in a version of the lesson before that update took place, I will close it. Please open a new issue if you have suggestions for how the new content could be improved.
