### ISSUE TITLE
replace strikethrough with subscript for the log10

### ISSUE THREAD

**Issue by avallecam** [datacarpentry/R-ecology-lesson#859]
Regarding this line

https://github.com/datacarpentry/R-ecology-lesson/blob/38dbdd64197c41dca1b854708d3cd8a724fae400/episodes/04-visualization-ggplot2.Rmd#L318

I assume that the intention of using `log~10~` is to create a subscript, not a strikethrough. [A previous commit adding the `~10~`](https://github.com/datacarpentry/R-ecology-lesson/commit/c3f440ddc8c759a861f9b65c4c6a91b40e9cd78a#diff-0a06bbc4ad45310078b23ea3bac5b8e00470bb7fc4dd0a48eee5d356c0f7f161R258) support this observation.

**Comment by zkamvar** [comment]
You just found a bug from the transition! I've opened #861 to fix it.
