### ISSUE TITLE
Suggestion to update package cache

### ISSUE THREAD

**Issue by zkamvar** [datacarpentry/R-ecology-lesson#860]
On 2023-06-06, this lesson was supposed to receive an automated pull request that updated the packages used in this lesson so that you could inspect the changes. Due to an upstream change in the Posit Package Manager URL, this did not happen because the GitHub Action that would create the pull request halted.

This action will run again on 2023-07-04, but **if you want to run it earlier**, you
should be able to go to the Actions tab and [manually run](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow?tool=webui) The `03 Maintain: Update Package Cache` workflow. 

One of the promises of The Workbench is that the setup is reliable and there are no surprises when it comes to building lessons that use R Markdown. The package cache ensures reproducibility, but because the lessons need to move with the flow of the R ecosystem, we built in a way to update the packages automatically via pull request. These pull requests will happen every month on the first Tuesday of the month and will only update components inside the `renv/` folder of your lesson. This will trigger a rebuild of all the episodes of your lesson so that you can detect instances where outputs have changed because of the new package versions.

**Comment by tobyhodges** [comment]
Closing this as the package cache is now being updated.
