### ISSUE TITLE
Suggestion: adding short description of custom functions in the 'Introduction to R' episode

### ISSUE THREAD

**Issue by kbice** [datacarpentry/R-ecology-lesson#862]
I think adding a short description of custom functions to the section that talks about functions in the 'Introduction to R' episode would be helpful especially for people wanting to implement specific operations to their data.

**Comment by tobyhodges** [comment]
Thanks @kbice for opening this issue. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As your suggestion relates to content in a version of the lesson before that update took place, I will close it. Please open a new issue if you have suggestions for how the new content could be improved.
