### ISSUE TITLE
Missing solution in R for Ecologists - part 5 ggplot2

### ISSUE THREAD

**Issue by FenneRiemslagh** [datacarpentry/R-ecology-lesson#868]
Hi, In the Data Analysis and Visualisation in R for Ecologists - part 5 Data visualization with ggplot2 - the last challenge of the boxplot exercise has no solution. Maybe we can add the following code? Please adjust as you see fit!
ggplot(data = surveys_complete, mapping = aes(x = species_id, y = hindfoot_length)) +
geom_jitter(alpha = 0.3, aes(color = plot_id)) +
geom_boxplot(outlier.shape = NA)
Best, Fenne

**Comment by tobyhodges** [comment]
Thanks @FenneRiemslagh for opening this issue, @bencomp for catching the need for it to be transferred, and @zkamvar for handling that. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As the suggestion relates to content in a version of the lesson before that update took place, I will close it. Please open a new issue if you have suggestions for how the new content could be improved.
