### ISSUE TITLE
Introduce the script document earlier in the episode

### ISSUE THREAD

**Issue by froggydame22** [datacarpentry/R-ecology-lesson#874]
### How could the content be improved?

During my Carpentries instruction demo, a couple of us picked the 'Introduction to R' episode in the Data Analysis and Visualisation in R for Ecologists and one of the things that came up during our teaching reflections was that it would be more intuitive for learners to be introduced to the R script at the very beginning of the episode rather than after the part about creating objects in R. 
It messes with the flow of teaching to take a step back and talk about creating and saving a script and then going back to talk about functions. 

### Which part of the content does your suggestion apply to?

https://datacarpentry.org/R-ecology-lesson/01-intro-to-r.html, Intro to r episode

**Comment by tobyhodges** [comment]
Thanks @froggydame22 for opening this issue. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. As your suggestion relates to content in a version of the lesson before that update took place, I will close it. Please open a new issue if you have suggestions for how the new content could be improved.
