### ISSUE TITLE
Code Handout R Ecology Lesson

### ISSUE THREAD

**Issue by etacke** [datacarpentry/R-ecology-lesson#876]
The link to the code handout from the R Ecology Lesson is not working--when clicked get "page not found".

**Comment by zkamvar** [comment]
This has a pull request to fix it: https://github.com/datacarpentry/R-ecology-lesson/pull/871

In the meantime, there is a button at the bottom of the sidebar that will link to the handout.

**Comment by tobyhodges** [comment]
Thanks @etacke for opening this issue. The lesson underwent a major update and reorganisation when https://github.com/datacarpentry/R-ecology-lesson/pull/887 was merged. The current version of the lesson does not include the code handout, so I am going to close this issue. Please open a new issue if you believe it would be helpful to include a handout for the redesigned lesson.
