### ISSUE TITLE
Remove lubridate from list of packages to install during setup

### ISSUE THREAD

**Issue by tobyhodges** [datacarpentry/R-ecology-lesson#894]
As pointed out my @mikemahoney218 in #879, `lubridate` is now part of the combined `tidyverse` package. In [the lesson setup instructions](https://datacarpentry.org/R-ecology-lesson/index.html#install-required-r-packages), we state that it should be installed alongside `tidyverse`:

> install.packages(c("tidyverse", "lubridate", "ratdat"))

Although I doubt the redundancy is doing much harm, it seems that this can be simplified to include only `tidyverse` and `ratdat`

**Comment by doujouDC** [comment]
@tobyhodges I will work on this on Friday

**Comment by doujouDC** [comment]
@tobyhodges would you recommend that I simply remove lubridate or provide some context about this now being part of the tidyverse. Wickham mentions this "Lubridate is part of core tidyverse, but it also exists as a standalone package" in R4DS

**Comment by tobyhodges** [comment]
I think it can be safely removed altogether. The primary audience for the setup instructions is novice learners who just want to get everything ready for a workshop, and who may not have a mental model yet for packages, the tidyverse etc. As such, Beyond the fundamental steps that should be taken to prepare for the workshop, any discussion would be unnecessary IMO, perhaps even counterproductive.
