### ISSUE TITLE
lubridate is a core tidyverse package

### ISSUE THREAD

**Issue by sjw46** [datacarpentry/R-ecology-lesson#895]
In the summary and setup episode, tidyverse and lubridate are both listed as packages that will be needed in the lesson. Instructions are given for how to install both packages and the learners are asked to load both packages.
But lubridate is a core tidyverse package, isn't it? So isn't is automatically installed with tidyverse and loaded with tidyverse?

https://datacarpentry.org/R-ecology-lesson-alternative/index.html#install-required-r-packages

**Comment by tobyhodges** [comment]
Thanks for raising this, @sjw46. I opened #894 before transferring yours into this repository, so I will close this as a duplicate.
