### ISSUE TITLE
Explain better what goes into `group_by()`

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#92]
Every time I teach dplyr, I see learners try to put the continuous variable they want to summarize in the `group_by()` call (they confuse the concept of `select()` and `group_by()`). I have tried to explain this in several different ways but I haven't found a good way to make it stick. Does anyone have suggestions to clarify this better?

**Comment by fmichonneau** [comment]
from hadley: https://twitter.com/hadleywickham/status/741372862984900608

**Comment by jennybc** [comment]
It seems like talking explicitly about rows (`group_by()`) vs columns (`select()`) could be part of helping them sort this out. To my knowledge, I've never actually seen this specific bit of confusion ... and I've seen a lot of confusion 😅. In my teaching, it's `group_by() + do()` that is very challenging.  Which I now plan to sidestep mostly via `purrr`.

**Comment by fmichonneau** [comment]
we've adjusted a few things in the lessons, and it doesn't seem to be an issue anymore.
