### ISSUE TITLE
possible typo in data frame lesson

### ISSUE THREAD

**Issue by gvwilson** [datacarpentry/R-ecology-lesson#97]
From Lindsay Brin:

~~~
colors <- c("red", "green", "blue", "yellow")
counts <- c(50, 60, 65, 82)
new_dataframe <- as.data.frame(cbind(colors, weights))
class(new_dataframe)
~~~

In the new data frame, it should be colors and counts, not colors and weights.

Also, it says to check it with class(), but then talks about automatic conversion of data types, which you would learn by checking it with str() rather than class().

**Comment by aurielfournier** [comment]
Great catch, made the suggested changes.
